### ISSUE TITLE
.pkl or .pickle file is not supported in v2 sklearn server

### ISSUE THREAD

**Issue by gaodan-fang** [kserve/kserve#1606]
/kind bug

**What steps did you take and what happened:**
Build a sklearn model and save as `.pickle`, store the model in pvc and create a sklearn inferenceservice with pvc `storage_uri` , the model can be download succssfully through the `storage-initializer` but can't be loaded by the `kfserving-contianer`.  
```
oc logs grade-mlmodel-kfserving-predictor-default-rpfvq-deploymentt25k6 -c storage-initializer
[I 210509 18:30:47 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/mlmodel-kfserving/results/grade_sklearn_ensemble_GradientBoostingClassifier] dest_path[ [/mnt/models]
[I 210509 18:30:47 storage:43] Copying contents of /mnt/pvc/mlmodel-kfserving/results/grade_sklearn_ensemble_GradientBoostingClassifier to local
[I 210509 18:30:47 storage:221] Linking: /mnt/pvc/mlmodel-kfserving/results/grade_sklearn_ensemble_GradientBoostingClassifier/model.pickle to /mnt/models/model.pickle
```

```
oc logs grade-mlmodel-kfserving-predictor-default-rpfvq-deploymentt25k6 -c kfserving-container
Traceback (most recent call last):
  File "/usr/local/bin/mlserver", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mlserver/cli/main.py", line 61, in main
    root()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mlserver/cli/main.py", line 18, in wrapper
    return asyncio.run(f(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/mlserver/cli/main.py", line 57, in start
    await server.start(models)
  File "/usr/local/lib/python3.7/site-packages/mlserver/server.py", line 28, in start
    await asyncio.gather(*load_tasks)
  File "/usr/local/lib/python3.7/site-packages/mlserver/repository.py", line 23, in load
    await model.load()
  File "/usr/local/lib/python3.7/site-packages/mlserver/models/sklearn.py", line 37, in load
    self._model = joblib.load(model_uri)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 577, in load
    with open(filename, 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/mnt/models'
```

**What did you expect to happen:**
Which according to the example https://github.com/kubeflow/kfserving/tree/master/python/sklearnserver/sklearnserver/example_models, `.pickle` file should be supported.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: 1.6.2
- Knative Version: v0.18.0
- KFServing Version: v0.5.0-rc2
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): openshift 4.6.23
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@gaodan-fang Looks like you are using v2 version of sklearnserver, Can you paste the full inference service yaml?

**Comment by gaodan-fang** [comment]
Yes, i was using the v2 protocol

**Comment by adriangonz** [comment]
Hey @gaodan-fang, the SKLearn server for V2 currently only supports `model.joblib` as a file name. This is highlighted in this example that walks you through model deployment with the V2 protocol:

https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/v2

Regardless of that, I think this could be a good addition so I've opened an issue in MLServer to add support for this:

https://github.com/SeldonIO/MLServer/issues/191

**Comment by gaodan-fang** [comment]
@adriangonz Thanks for the quick update! As you mentioned 
> Note that, regardless of the file name, the runtime will still expect a file serialised using joblib.
Is there any particular reason MLServer won't support `pkl` serizlised file ? If not, does MLServer has the plan to support in the near feature?

**Comment by adriangonz** [comment]
Hey @gaodan-fang , when you say `pkl` serialised file, can you clarify how it gets serialised? Just to expand on this point, there are a few different libraries that can be used to serialise Python objects (e.g. `pickle`, `joblib`, `cloudpickle`, `dill`, etc.). They are all very similar in functionality, but the serialised objects aren't compatible between them.

To serialise Scikit-Learn models, you can potentially use any of them. However, they recommend using [`joblib` in their docs](https://scikit-learn.org/stable/modules/model_persistence.html#python-specific-serialization). This is the expected format by MLServer.

Maybe, could you share a snippet on how does the model get serialised?

**Comment by gaodan-fang** [comment]
Yes, the example like

```
import pickle 
filename = 'model.pickle'
pickle.dump(model, filename)
```
I know the joblib is recommended in sklearn, but sometimes user just prefer to use `pickle` than `joblib` as both them has their own [advantages](https://stackoverflow.com/questions/12615525/what-are-the-different-use-cases-of-joblib-versus-pickle). And we don't want to restrict the customer which method they should use.
