### ISSUE TITLE
aix-explainer fails with "No address associated with hostname"

### ISSUE THREAD

**Issue by edi-bice-by** [kserve/kserve#1655]
/kind bug

Deployed latest from docs/samples/explanation/aix/mnist/aix-explainer.yaml to user namespace (not default) on Kubeflow 1.3 on GCP behind IAP security.

Trying to produce an explanation via

MODEL_NAME=aix-explainer
SERVICE_URL=https://kubeflow.endpoints.saas-ml-dev.cloud.goog
SERVICE_URL=https://kubeflow.endpoints.saas-ml-dev.cloud.goog
python query_explain.py ${SERVICE_URL}/v1/models/${MODEL_NAME}:explain "${SERVICE_HOSTNAME}" "${TOKEN}" 1001

... returns 500 and produces this error on the pod logs

[I 210607 20:22:17 model:74] Calling explain on image of shape ((28, 28, 3),)
[E 210607 20:22:18 web:1793] Uncaught exception POST /v1/models/aix-explainer:explain (127.0.0.1)
    HTTPServerRequest(protocol='http', host='aix-explainer-explainer-default.edi-bice.kubeflow.endpoints.saas-ml-dev.cloud.goog', method='POST', uri='/v1/models/aix-explainer:explain', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/aixexplainer/aixserver/model.py", line 88, in explain
        segmentation_fn=segmenter)
      File "/usr/local/lib/python3.7/site-packages/aix360/algorithms/lime/lime_wrapper.py", line 64, in explain_instance
        self.explanation = self.explainer.explain_instance(*argv, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/lime/lime_image.py", line 199, in explain_instance
        batch_size=batch_size)
      File "/usr/local/lib/python3.7/site-packages/lime/lime_image.py", line 262, in data_labels
        preds = classifier_fn(np.array(imgs))
      File "/aixexplainer/aixserver/model.py", line 48, in _predict
        resp = loop.run_until_complete(self.predict(scoring_data))
      File "/usr/local/lib/python3.7/site-packages/nest_asyncio.py", line 70, in run_until_complete
        return f.result()
      File "/usr/local/lib/python3.7/asyncio/futures.py", line 181, in result
        raise self._exception
      File "/usr/local/lib/python3.7/asyncio/tasks.py", line 251, in __step
        result = coro.throw(exc)
      File "/kfserving/kfserving/kfmodel.py", line 98, in predict
        body=json.dumps(request)
      File "/usr/local/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
        future.result()
      File "/usr/local/lib/python3.7/site-packages/tornado/simple_httpclient.py", line 344, in run
        source_ip=source_ip,
      File "/usr/local/lib/python3.7/site-packages/tornado/tcpclient.py", line 265, in connect
        addrinfo = await self.resolver.resolve(host, port, af)
      File "/usr/local/lib/python3.7/site-packages/tornado/netutil.py", line 399, in resolve
        None, _resolve_addr, host, port, family
      File "/usr/local/lib/python3.7/asyncio/futures.py", line 263, in __await__
        yield self  # This tells Task to wait for completion.
      File "/usr/local/lib/python3.7/asyncio/tasks.py", line 318, in __wakeup
        future.result()
      File "/usr/local/lib/python3.7/asyncio/futures.py", line 181, in result
        raise self._exception
      File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/usr/local/lib/python3.7/site-packages/tornado/netutil.py", line 382, in _resolve_addr
        addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
      File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno -5] No address associated with hostname
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/kfserving/kfserving/handlers/http.py", line 110, in post
        response = (await model.explain(request)) if inspect.iscoroutinefunction(model.explain) else model.explain(request)
      File "/aixexplainer/aixserver/model.py", line 107, in explain
        raise Exception("Failed to explain %s" % err)
    Exception: Failed to explain [Errno -5] No address associated with hostname
[E 210607 20:22:18 web:2243] 500 POST /v1/models/aix-explainer:explain (127.0.0.1) 166.78ms

**Environment:**

GCP+IAP

- Istio Version:
- Knative Version:
- KFServing Version: 
- Kubeflow version: 1.3
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Tomcli** [comment]
Hi @edi-bice-by, does your cluster with IAP can run this basic sk-learn example?
https://github.com/kubeflow/kfserving/tree/master/docs/samples/v1beta1/sklearn/v1

For some Dex authorization, we still have to disable the istio sidecar in order to run the model properly. Maybe you can add the `sidecar.istio.io/inject: "false"` annotation like the below example
https://github.com/kubeflow/kfserving/tree/master/docs/samples/istio-dex

**Comment by yantriks-edi-bice** [comment]
I figured out predictors, can deploy them without disabling istio, query them externally etc., but no luck with explainers of any kind. It seems explainer overrides kfmodel incorrectly and ends up listening on a predictor host, though the requests come in with the proper explainer hostname etc. 

root@cifar10-explainer-default-00001-deployment-5f975bd99f-7gjgp:/# ps xfaww
    PID TTY      STAT   TIME COMMAND
     22 pts/0    Ss     0:00 /bin/bash
     42 pts/0    R+     0:00  \_ ps xfaww
      1 ?        Ssl    0:28 python -m alibiexplainer --model_name cifar10 --http_port 8080 --predictor_host cifar10-predictor-default.edi-bice --storage_uri /mnt/models AnchorImages --batch_size 40 --stop_on_first True

`[I 210716 14:28:05 explainer:50] Predict URL set to cifar10-predictor-default.edi-bice
[I 210716 14:28:05 kfserver:151] Registering model: cifar10
[I 210716 14:28:05 kfserver:121] Setting asyncio max_workers as 5
[I 210716 14:28:05 kfserver:128] Listening on port 8080
[I 210716 14:28:05 kfserver:130] Will fork 1 workers
[E 210716 19:07:03 web:1793] Uncaught exception POST /v1/models/cifar10:explain (127.0.0.1)
    HTTPServerRequest(protocol='http', host='cifar10-explainer-default.edi-bice.kubeflow.endpoints.saas-ml-dev.cloud.goog', method='POST', uri='/v1/models/cifar10:explain', version='HTTP/1.1', remote_ip='127.0.0.1')`

Note the predictor one uses tensorflow_model_server and doesn't mess with predictor/explainer host just port

root@cifar10-predictor-default-00001-deployment-8bd596cbc-jwsqg:/# ps xfawww
    PID TTY      STAT   TIME COMMAND
    109 pts/1    Ss     0:00 /bin/bash
    121 pts/1    R+     0:00  \_ ps xfawww
     99 pts/0    Ss+    0:00 /bin/bash
      1 ?        Ssl    0:24 /usr/bin/tensorflow_model_server --port=9000 --rest_api_port=8080 --model_name=cifar10 --model_base_path=/mnt/models --rest_api_timeout_in_ms=60000
