### ISSUE TITLE
Alibi sample explainer in crashloop

### ISSUE THREAD

**Issue by lsuanet** [kserve/kserve#1786]
/kind bug

**What steps did you take and what happened:**

When deploying the Alibi explainer sample from the docs, the explainer container lands into a crash-loop:

```
2021-09-01 09:55:43.720824: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-09-01 09:55:43.720858: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
[I 210901 09:55:46 parser:224] Extra args: {}
[I 210901 09:55:46 storage:50] Copying contents of /mnt/models to local
[I 210901 09:55:46 __main__:39] Loading Alibi model
[I 210901 09:55:46 explainer:50] Predict URL set to income-predictor-default.default
[I 210901 09:55:46 kfserver:151] Registering model: income
[I 210901 09:55:46 kfserver:121] Setting asyncio max_workers as 5
[I 210901 09:55:46 kfserver:128] Listening on port 8080
[I 210901 09:55:46 kfserver:130] Will fork 0 workers
[I 210901 09:55:46 process:123] Starting 4 processes
Traceback (most recent call last):
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 256, in _add_reader
key = self._selector.get_key(fd)
File "/usr/local/lib/python3.7/selectors.py", line 192, in get_key
raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '7 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/alibiexplainer/alibiexplainer/__main__.py", line 54, in <module>
main()
File "/alibiexplainer/alibiexplainer/__main__.py", line 50, in main
kfserving.KFServer().start(models=[explainer], nest_asyncio=True)
File "/kfserving/kfserving/kfserver.py", line 131, in start
self._http_server.start(self.workers)
File "/usr/local/lib/python3.7/site-packages/tornado/tcpserver.py", line 248, in start
self.add_sockets(sockets)
File "/usr/local/lib/python3.7/site-packages/tornado/tcpserver.py", line 166, in add_sockets
sock, self._handle_connection
File "/usr/local/lib/python3.7/site-packages/tornado/netutil.py", line 282, in add_accept_handler
io_loop.add_handler(sock, accept_handler, IOLoop.READ)
File "/usr/local/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 150, in add_handler
self.selector_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 329, in add_reader
return self._add_reader(fd, callback, *args)
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 259, in _add_reader
(handle, None))
File "/usr/local/lib/python3.7/selectors.py", line 359, in register
self._selector.register(key.fd, poller_events)
FileExistsError: [Errno 17] File exists
Traceback (most recent call last):
File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 256, in _add_reader
key = self._selector.get_key(fd)
File "/usr/local/lib/python3.7/selectors.py", line 192, in get_key
raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '7 is not registered'
```

**Environment:**

- Istio Version: 1.9.8
- Knative Version: 0.25.0
- KFServing Version: 0.6.1
- Kubernetes version: (use `kubectl version`): 1.19.13-eks

**Comment by yuzisun** [comment]
@lsuanet seems like multiprocessing issue, the default worker should be 1 though.

**Comment by lsuanet** [comment]
@yuzisun the default worker is indeed 0:

```
spec:
  containers:
    - name: kfserving-container
      image: >-
        index.docker.io/kfserving/alibi-explainer@sha256:6c2ffe46ba7a619af9208aaf02e12bb502e6b7a2dd3dcd181eb27cecdf3fe1f9
      args:
        - '--model_name'
        - income
        - '--http_port'
        - '8080'
        - '--predictor_host'
        - income-predictor-default.default
        - '--workers'
        - '0'
        - '--storage_uri'
        - /mnt/models
        - AnchorTabular
```

Setting this to 1 indeed fixes the issue.

**Comment by yuzisun** [comment]
@lsuanet the default worker is already changed to 1, wondering which release you are on?
https://github.com/kubeflow/kfserving/blob/master/python/kfserving/kfserving/kfserver.py#L46

**Comment by lsuanet** [comment]
@yuzisun I am on version `v0.6.1`.

The `--worker` argument is actually passed as a container argument, overwriting the KFServer default:
```yaml
containers:
  - name: kfserving-container
    image: >-
      index.docker.io/kfserving/alibi-explainer@sha256:6c2ffe46ba7a619af9208aaf02e12bb502e6b7a2dd3dcd181eb27cecdf3fe1f9
    args:
      - '--model_name'
      - income
      - '--http_port'
      - '8080'
      - '--predictor_host'
      - income-predictor-default.default
      - '--workers'
      - '0'
      - '--storage_uri'
      - /mnt/models
      - AnchorTabular
```
