### ISSUE TITLE
Wrong path to storage with PersistentVolumeClaim

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#1797]
/kind bug

**What steps did you take and what happened:**
I have nfs-storage, pv, pvsi. I am using CF-Client to draw model inference. However, I can't do it, because the repository is mounted in the wrong path.

`kubectl get sc`
```
NAME                          PROVISIONER                                                  RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
nfs-client (default)          cluster.local/mortal-skunk-nfs-subdir-external-provisioner   Delete          Immediate           true                   34d

```

`kubectl get pv,pvc -A`
```
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                 STORAGECLASS        REASON   AGE
persistentvolume/pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395   30Gi       RWX            Delete           Bound    default/torchserve-pv-claim           nfs-client                   30d

NAMESPACE                   NAME                                        STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
default                     persistentvolumeclaim/torchserve-pv-claim   Bound    pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395   30Gi       RWX            nfs-client          30d
```

`!kubectl describe pv pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395`
```
Name:            pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by: cluster.local/mortal-skunk-nfs-subdir-external-provisioner
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    nfs-client
Status:          Bound
Claim:           default/torchserve-pv-claim
Reclaim Policy:  Delete
Access Modes:    RWX
VolumeMode:      Filesystem
Capacity:        30Gi
Node Affinity:   <none>
Message:         
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.21.190
    Path:      /mnt/nfs/default-torchserve-pv-claim-pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395
    ReadOnly:  false
Events:        <none>
```

`kubectl describe pvc torchserve-pv-claim -n default`
```
Name:          torchserve-pv-claim
Namespace:     default
StorageClass:  nfs-client
Status:        Bound
Volume:        pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395
Labels:        <none>
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: cluster.local/mortal-skunk-nfs-subdir-external-provisioner
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      30Gi
Access Modes:  RWX
VolumeMode:    Filesystem
Used By:       <none>
Events:        <none>
```

```
namespace = 'default'
model_name = 'roberta-base'

pytorch_predictor=V1beta1PredictorSpec(
    pytorch=V1beta1TorchServeSpec(
        storage_uri='pvc://torchserve-pv-claim/models/torchserve',
        resources=V1ResourceRequirements(requests={'cpu':'1000m','memory':'4Gi'},
                                         limits={'cpu':'1000m', 'memory':'8Gi'})
    )
)
```

```
isvc = V1beta1InferenceService(api_version=constants.KFSERVING_V1BETA1,
                               kind=constants.KFSERVING_KIND,
                               metadata=client.V1ObjectMeta(name=model_name, namespace=namespace),
                               spec=V1beta1InferenceServiceSpec(predictor=pytorch_predictor))
print (isvc)

{'api_version': 'serving.kubeflow.org/v1beta1',
 'kind': 'InferenceService',
 'metadata': {'annotations': None,
              'cluster_name': None,
              'creation_timestamp': None,
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': None,
              'labels': None,
              'managed_fields': None,
              'name': 'roberta-base',
              'namespace': 'default',
              'owner_references': None,
              'resource_version': None,
              'self_link': None,
              'uid': None},
 'spec': {'explainer': None,
          'predictor': {'active_deadline_seconds': None,
                        'affinity': None,
                        'automount_service_account_token': None,
                        'batcher': None,
                        'canary_traffic_percent': None,
                        'container_concurrency': None,
                        'containers': None,
                        'dns_config': None,
                        'dns_policy': None,
                        'enable_service_links': None,
                        'ephemeral_containers': None,
                        'host_aliases': None,
                        'host_ipc': None,
                        'host_network': None,
                        'host_pid': None,
                        'hostname': None,
                        'image_pull_secrets': None,
                        'init_containers': None,
                        'lightgbm': None,
                        'logger': None,
                        'max_replicas': None,
                        'min_replicas': None,
                        'node_name': None,
                        'node_selector': None,
                        'onnx': None,
                        'overhead': None,
                        'pmml': None,
                        'preemption_policy': None,
                        'priority': None,
                        'priority_class_name': None,
                        'pytorch': {'args': None,
                                    'command': None,
                                    'env': None,
                                    'env_from': None,
                                    'image': None,
                                    'image_pull_policy': None,
                                    'lifecycle': None,
                                    'liveness_probe': None,
                                    'model_class_name': None,
                                    'name': None,
                                    'ports': None,
                                    'protocol_version': None,
                                    'readiness_probe': None,
                                    'resources': {'limits': {'cpu': '1000m',
                                                             'memory': '8Gi'},
                                                  'requests': {'cpu': '1000m',
                                                               'memory': '4Gi'}},
                                    'runtime_version': None,
                                    'security_context': None,
                                    'startup_probe': None,
                                    'stdin': None,
                                    'stdin_once': None,
                                    'storage_uri': 'pvc://torchserve-pv-claim/models/torchserve',
                                    'termination_message_path': None,
                                    'termination_message_policy': None,
                                    'tty': None,
                                    'volume_devices': None,
                                    'volume_mounts': None,
                                    'working_dir': None},
                        'readiness_gates': None,
                        'restart_policy': None,
                        'runtime_class_name': None,
                        'scheduler_name': None,
                        'security_context': None,
                        'service_account': None,
                        'service_account_name': None,
                        'share_process_namespace': None,
                        'sklearn': None,
                        'subdomain': None,
                        'tensorflow': None,
                        'termination_grace_period_seconds': None,
                        'timeout': None,
                        'tolerations': None,
                        'topology_spread_constraints': None,
                        'triton': None,
                        'volumes': None,
                        'xgboost': None},
          'transformer': None},
 'status': None}
```

```
KFServing = KFServingClient()
KFServing.create(isvc)

{'apiVersion': 'serving.kubeflow.org/v1beta1',
 'kind': 'InferenceService',
 'metadata': {'creationTimestamp': '2021-09-10T16:06:29Z',
  'generation': 1,
  'managedFields': [{'apiVersion': 'serving.kubeflow.org/v1beta1',
    'fieldsType': 'FieldsV1',
    'fieldsV1': {'f:spec': {'.': {},
      'f:predictor': {'.': {},
       'f:pytorch': {'.': {},
        'f:resources': {'.': {},
         'f:limits': {'.': {}, 'f:cpu': {}, 'f:memory': {}},
         'f:requests': {'.': {}, 'f:cpu': {}, 'f:memory': {}}},
        'f:storageUri': {}}}}},
    'manager': 'OpenAPI-Generator',
    'operation': 'Update',
    'time': '2021-09-10T16:06:27Z'}],
  'name': 'roberta-base',
  'namespace': 'default',
  'resourceVersion': '68999289',
  'selfLink': '/apis/serving.kubeflow.org/v1beta1/namespaces/default/inferenceservices/roberta-base',
  'uid': 'f98b7f70-d3d0-4be3-9dec-06dc314af93c'},
 'spec': {'predictor': {'pytorch': {'name': 'kfserving-container',
    'protocolVersion': 'v1',
    'resources': {'limits': {'cpu': '1', 'memory': '8Gi'},
     'requests': {'cpu': '1', 'memory': '4Gi'}},
    'runtimeVersion': '0.3.0',
    'storageUri': 'pvc://torchserve-pv-claim/models/torchserve'}}}}
```

**Get status created InferenceService**
```
!kubectl get inferenceservices -A
NAMESPACE                   NAME            URL                                                          READY     PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                     AGE
default                     roberta-base                                                                 Unknown    
```

```
microk8s kubectl logs roberta-base-predictor-default-7n6fj-deployment-5544c8b7767qjg6 -c kfserving-container
--ts-config file not found: /mnt/models/config/config.properties
```

Wwhy is the path  /mnt/models/config/ and not the /mnt/nfs/default-torchserve-pv-claim-pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395?

**What did you expect to happen:**
```
!kubectl get inferenceservices -A
NAMESPACE                   NAME            URL                                                          READY     PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                     AGE
default                     roberta-base                                                                 True    
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
- microk8s 1.20
- OS (e.g. from `/etc/os-release`): 20.04.3 LTS (Focal Fossa)

**Comment by yurkoff-mv** [comment]
I got a new error:
`!kubectl logs -n default roberta-base-predictor-default-575kp-deployment-7657bdcbf49g6j7  -c storage-initializer`

```
[I 210913 07:44:29 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/models/torchserve] dest_path[ [/mnt/models]
[I 210913 07:44:29 storage:45] Copying contents of /mnt/pvc/models/torchserve to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 76, in download
    (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX, _HTTP_PREFIX))
Exception: Cannot recognize storage type for /mnt/pvc/models/torchserve
'gs://', 's3://', 'file://', and 'http(s)://' are the current available storage type.
```
It is not clear on which path I have to put the configuration file and the mar-file of the model in order for everything to work and how to manage these paths.

**Comment by yurkoff-mv** [comment]
I solved the problem by adding the file `config.properties` to the directory ` /mnt/nfs/default-torchserve-pv-claim-pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395/torchserve/config` и mar-file to `/mnt/nfs/default-torchserve-pv-claim-pvc-eeca0c4b-85b3-45d2-9ce3-e3be473f1395/torchserve/model-store`.
However, I still did not understand how to solve the issue of managing these paths.

**Comment by yuzisun** [comment]
@yurkoff-mv check the expected model storage layout [here](https://kserve.github.io/website/modelserving/v1beta1/torchserve/#creating-model-storage-with-model-archive-file), the storage initializer copy the model data from your PVC to the local mount `/mnt/pvc`.

**Comment by yurkoff-mv** [comment]
Thanks for your reply. Did I understand correctly that the paths are rigidly defined and I just have to follow them?

**Comment by yuzisun** [comment]
@yurkoff-mv yes the paths are defined with a specified torchserve layout, let me know if you are having the issue.

**Comment by andyi2it** [comment]
/close

Closing this as the storage layout did not conform to the requirements and with the right layout should work.
