### ISSUE TITLE
Storage-initalizer doesn't set all env variables

### ISSUE THREAD

**Issue by bartgras** [kserve/kserve#1991]
/kind bug

**What steps did you take and what happened:**
I have KServe setup on Kubeflow. I follow [S3 storage setup guide](https://kserve.github.io/website/modelserving/storage/s3/s3/) with Minio as endpoint.

Issue: For some reason only `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are being set in init container `kserve/storage-initializer:v0.7.0`, others like e.g. `AWS_ENDPOINT_URL` are missing.

Details:

```
apiVersion: v1
kind: Secret
metadata:
  name: minio-access-for-deployment
  namespace: prod
  annotations:
    serving.kserve.org/s3-endpoint: minio-service.kubeflow:9000
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.org/s3-verifyssl: "0"
    serving.kserve.org/s3-region: us-east-1
type: Opaque
stringData: 
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer
  namespace: prod
secrets:
- name: minio-access-for-deployment
```

Created ISVC, only `initContainers` part:
```
  initContainers:
  - args:
    - s3://trained-models/9ca4758f-958e-43d9-8aa1-f5a00a1c8c02/
    - /mnt/models
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: minio-access-for-deployment
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: minio-access-for-deployment
    image: kserve/storage-initializer:v0.7.0
    imagePullPolicy: IfNotPresent
    name: storage-initializer
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /mnt/models
      name: kserve-provision-location
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-j44sg
      readOnly: true
```
Further down in the same ISVC I can see correct service account being set:
```
  serviceAccount: deployer
  serviceAccountName: deployer
```

`storage-initializer` logs:
```
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 220113 03:24:20 initializer-entrypoint:13] Initializing, args: src_uri [s3://trained-models/9ca4758f-958e-43d9-8aa1-f5a00a1c8c02/] dest_path[ [/mnt/models]
[I 220113 03:24:20 storage:52] Copying contents of s3://trained-models/9ca4758f-958e-43d9-8aa1-f5a00a1c8c02/ to local
[I 220113 03:24:21 credentials:1102] Found credentials in environment variables.
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kserve.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 69, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 114, in _download_s3
    for obj in bucket.objects.filter(Prefix=bucket_path):
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/usr/local/lib/python3.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 255, in __iter__
    response = self._make_request(current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/paginate.py", line 332, in _make_request
    return self._method(**current_kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
```

**What did you expect to happen:**
The `AWS_ENDPOINT_URL` env var to be set.

**Anything else you would like to add:**
I can see that in storage.py [_download_3d](https://github.com/kserve/kserve/blob/9fa4940c6c10e96a86d5cb1bc855f7405b1276c4/python/kserve/kserve/storage.py#L105) boto3 is trying to read `AWS_ENDPOINT_URL`.
I can see that these `Envois are being defined in s3_secret.go [BuildSecretEnvs](https://github.com/kserve/kserve/blob/9fa4940c6c10e96a86d5cb1bc855f7405b1276c4/pkg/credentials/s3/s3_secret.go#L95), but for some reason it's not being set in my case. 

**Environment:**

- Istio Version: 1.9.6
- Knative Version: 0.22.1
- KFServing Version: 0.7
- Kubeflow version: 1.4
- Kubernetes version: (use `kubectl version`): 1.21 (K3d)
- OS (e.g. from `/etc/os-release`): macOS

**Comment by yuzisun** [comment]
@bartgras you had a typo there it is serving.kserve.io not org

**Comment by bartgras** [comment]
Omg! you're right. Thanks and sorry for confusion.
