### ISSUE TITLE
No module named 'sklearn.svm.classes'

### ISSUE THREAD

**Issue by golimix** [kserve/kserve#2059]
```
nerdctl --insecure-registry run -it kserve/sklearnserver:v0.8.0 -v /alpine/html/models/sklearn/iris:/mnt/model --model_dir http://10.3.174.17:10080/models/sklearn/iris/model.joblib
[I 220223 08:59:59 storage:54] Copying contents of http://10.3.174.17:10080/models/sklearn/iris/model.joblib to local
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 35, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 43, in load
    self._model = joblib.load(existing_paths[0])
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.7/pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.svm.classes'
```

the sklearnserver:v0.8.0 doesn't work well with the ``gs://kfserving-samples/models/sklearn/iris``

after down to sklearnserver:v0.7.0 works well

**Comment by yuzisun** [comment]
@24king sklearnserver v0.8.0 has upgraded sklearn to v1.0.1 and you need to use the example from https://github.com/kserve/kserve/blob/master/docs/samples/v1beta1/sklearn/v1/sklearn.yaml#L8
