### ISSUE TITLE
[Question]Requests failed with errors from Transformer Pod to Predictor Pod

### ISSUE THREAD

**Issue by yangyang919** [kserve/kserve#2080]
/kind bug

**What steps did you take and what happened:**
Hi experts, this is more of a question. We have deployed our Transformer via InterferenceService. From deployment point of view, looks like everything is ok. But when triggering http request from CLI, the 404 Not Found error occurred. If checking logs in Predictor pod, looks like the request was actually received. But got 404 from a redirect to dex/auth. I feel the issue is something related to gateway stuff. Internal requests shouldn't need redirect right? Thanks for answering!

Error messages from Predictor:
`
C02YW2X4LVDQ:transformer i330955$ kubectl logs failure-rate-transformer-predictor-default-00001-deployment4gb4 kserve-container
[I 220308 03:51:21 storage:54] Copying contents of /mnt/models/data to local
[I 220308 03:51:22 model_server:150] Registering model: failure-rate-transformer
[I 220308 03:51:22 model_server:123] Listening on port 8080
[I 220308 03:51:22 model_server:125] Will fork 1 workers
[I 220308 03:51:22 model_server:128] Setting max asyncio worker threads as 5
[W 220308 03:57:23 web:2243] 404 GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTY0NjcxMTg0M3xFd3dBRUU5S2NuSkJPSE4wYzBwUE4zRk5lV2c9fDJYoUc7bK569oZySQSzn3qY8RjgXUJFYWmfEw78qq25 (127.0.0.1) 1.10ms
[W 220308 03:58:47 web:2243] 404 GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTY0NjcxMTkyN3xFd3dBRUZWamRVeEVNMFJ6Wm0xeWIxUkVjMnc9fPmDC7oMApZj-A9p-WSNAki9_AvLwFnAPQ8-KS_jWu65 (127.0.0.1) 0.83ms
[W 220308 06:08:40 web:2243] 404 GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTY0NjcxOTcyMHxFd3dBRUdvelZqRlJlVkpoTUVsclNuZ3dkSGM9fNwxxl_3mDqTo_coG_0rjUEm5O8BIyY-jCZVbAoEsdb8 (127.0.0.1) 0.53ms
[W 220308 06:21:33 web:2243] 404 GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Flogin%2Foidc&response_type=code&scope=profile+email+groups+openid&state=MTY0NjcyMDQ5M3xFd3dBRUdSSU0zbGpXVFV6TVhoamNuYzFlRk09fDahB_Msr1M2WjTrFmkb65Yu0TaVDWdYWx6JL4ur1bbE (127.0.0.1) 0.56ms`

Error messages from Transformer:
`
C02YW2X4LVDQ:transformer i330955$ kubectl logs failure-rate-transformer-transformer-default-00001-deploym852ck kserve-container
[I 220308 03:51:21 transformer:14] MODEL NAME failure-rate-transformer
[I 220308 03:51:21 transformer:15] PREDICTOR URL failure-rate-transformer-predictor-default.dev-profile
[I 220308 03:51:21 model_server:150] Registering model: failure-rate-transformer
[I 220308 03:51:21 model_server:123] Listening on port 8080
[I 220308 03:51:21 model_server:125] Will fork 1 workers
[I 220308 03:51:21 model_server:128] Setting max asyncio worker threads as 5
[W 220308 03:52:59 web:2243] 404 POST /v1/models/model:predict (127.0.0.1) 0.79ms
[W 220308 03:53:32 web:2243] 404 POST /v1/models/model:predict (127.0.0.1) 0.61ms
[W 220308 03:53:47 web:2243] 404 POST /v1/models/failure-rate-model:predict (127.0.0.1) 0.64ms
[E 220308 03:57:23 web:1793] Uncaught exception POST /v1/models/failure-rate-transformer:predict (127.0.0.1)
    HTTPServerRequest(protocol='http', host='failure-rate-transformer-transformer-default.dev-profile.svc.cluster.local', method='POST', uri='/v1/models/failure-rate-transformer:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.6/site-packages/kserve/handlers/predict.py", line 70, in post
        response = await model(body)
      File "/usr/local/lib/python3.6/site-packages/kserve/model.py", line 86, in __call__
        response = (await self.predict(request)) if inspect.iscoroutinefunction(self.predict) \
      File "/usr/local/lib/python3.6/site-packages/kserve/model.py", line 211, in predict
        return await self._http_predict(request)
      File "/usr/local/lib/python3.6/site-packages/kserve/model.py", line 187, in _http_predict
        body=json.dumps(request)
    tornado.httpclient.HTTPClientError: HTTP 404: Not Found
[E 220308 03:57:23 web:2243] 500 POST /v1/models/failure-rate-transformer:predict (127.0.0.1) 73.42ms`

**Comment by yangyang919** [comment]
Updates today, I feel the problem is on VirtualService / Gatewayside, here is what I did:

```
C02YW2X4LVDQ:transformer i330955$ kubectl logs failure-rate-transformer-transformer-default-00001-deploymflhp2kserve-container 
[I 220309 02:53:04 transformer:14] MODEL NAME failure-rate-transformer
[I 220309 02:53:04 transformer:15] PREDICTOR URL failure-rate-transformer-predictor-default.dev-profile
[I 220309 02:53:04 model_server:150] Registering model: failure-rate-transformer
[I 220309 02:53:04 model_server:123] Listening on port 8080
[I 220309 02:53:04 model_server:125] Will fork 1 workers
[I 220309 02:53:04 model_server:128] Setting max asyncio worker threads as 5
```

I took the value of PREDICTOR URL, this is also the URL that Transformer took to invoke Predictor. Then I directly invoked this URL from CLI:

```
curl -v -H "Host: ${SERVICE_HOSTNAME}" -H "Cookie: authservice_session=token" http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/failure-rate-transformer:predict -d @./input.json
I expect Predictor can be invoked. But I got 404 error, while Predictor does not receive the request
> POST /v1/models/failure-rate-transformer:predict HTTP/1.1
> Host: failure-rate-transformer-predictor-default.dev-profile
> User-Agent: curl/7.77.0
> Accept: */*
> Cookie: authservice_session=token
> Content-Length: 174
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< date: Wed, 09 Mar 2022 03:37:37 GMT
< server: istio-envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
```


I suspect something wrong on virtual service, gateway side, which makes the request couldn’t been forwarded. Any one has any idea on how to further debug? We are quite new to KNative, KServe world...Plus, in our inferenceService.yaml, we disabled istio injection, not sure whether this has some affects

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "failure-rate-transformer"
  namespace: "dev-profile"
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  transformer:
    containers:
    - image: image_url
      name: transformer-container
      command:
      - "python"
      - "-m"
      - "failure_rate_transformer"
    imagePullSecrets:
    - name: "image_auth"
  predictor:
    serviceAccountName: minio-sa
    sklearn:
      args: 
        - --model_dir=/mnt/models/data
      storageUri: "s3://mlpipeline/artifacts/model.tgz"
```
