### ISSUE TITLE
Unauthenticated access to gs://kfserving-samples has been blocked

### ISSUE THREAD

**Issue by thomwatkin** [kserve/kserve#2219]
/kind bug

It looks like unauthenticated access to the kfserving-samples GCS bucket has been removed.

While trying to run KServe examples I'm now receiving 401 errors from the storage URI.

**What steps did you take and what happened:**
1. Try to create an InferenceService from a notebook using the kfserving SDK, using Kubeflow v1.5.0
2. Pod fails to initialize
3. Check pod logs

```
kubectl logs sklearn-iris-predictor-default-00001-deployment-985cb595f-gmx9c storage-initializer
[I 220606 19:58:37 initializer-entrypoint:13] Initializing, args: src_uri [gs://kfserving-samples/models/sklearn/iris] dest_path[ [/mnt/models]
[I 220606 19:58:37 storage:50] Copying contents of gs://kfserving-samples/models/sklearn/iris to local
[W 220606 19:58:37 _default:285] Authentication failed using Compute Engine authentication due to unavailable metadata server.
[I 220606 19:58:37 requests:499] Refreshing credentials due to a 401 response. Attempt 1/2.
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 65, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 142, in _download_gcs
    for blob in blobs:
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 208, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 244, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 373, in _next_page
    response = self._get_next_page_response()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 433, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 78, in api_request
    return call()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 288, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 475, in api_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 333, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 371, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 511, in request
    self.credentials.refresh(auth_request)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 170, in refresh
    raise ValueError("Anonymous credentials cannot be refreshed.")
ValueError: Anonymous credentials cannot be refreshed.
```

Similarly, I'm unable to see any of the examples from a browser.

**What did you expect to happen:**
Example models should allow unauthenticated access so that they can be used.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version: v1.11.4
- Knative Version: v0.22.1
- KFServing Version: v0.6.1
- Kubeflow version: v1.5.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version: n/a
- Kubernetes version: (use `kubectl version`): v1.19.16-eks-25803e
- OS (e.g. from `/etc/os-release`): n/a

**Comment by yuzisun** [comment]
`kfserving-samples` gcs bucket is deprecated, please use `kfserving-examples` instead and we have updated all docs to reflect that.

**Comment by thomwatkin** [comment]
Thanks for the correction here - hadn't seen the updated docs.

I'll close this accordingly.
