### ISSUE TITLE
gs://kfserving-samples/models/tensorflow/flowers cannot be accessed

### ISSUE THREAD

**Issue by xfzhang1974** [kserve/kserve#2234]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

storage-initializer log
[I 220608 17:55:28 initializer-entrypoint:13] Initializing, args: src_uri [gs://kfserving-samples/models/tensorflow/flowers] dest_path[ [/mnt/models]
[I 220608 17:55:28 storage:52] Copying contents of gs://kfserving-samples/models/tensorflow/flowers to local
[W 220608 17:55:28 _metadata:104] Compute Engine Metadata server unavailable onattempt 1 of 3. Reason: [Errno 111] Connection refused
[W 220608 17:55:28 _metadata:104] Compute Engine Metadata server unavailable onattempt 2 of 3. Reason: [Errno 111] Connection refused
[W 220608 17:55:28 _metadata:104] Compute Engine Metadata server unavailable onattempt 3 of 3. Reason: [Errno 111] Connection refused
[W 220608 17:55:28 _default:287] Authentication failed using Compute Engine authentication due to unavailable metadata server.
[I 220608 17:55:28 requests:504] Refreshing credentials due to a 401 response. Attempt 1/2.
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kserve.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 67, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 152, in _download_gcs
    for blob in blobs:
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 372, in _next_page
    response = self._get_next_page_response()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 432, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 78, in api_request
    return call()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 290, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python3.7/site-packages/google/api_core/retry.py", line 188, in retry_target
    return target()
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 475, in api_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 333, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 371, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 516, in request
    self.credentials.refresh(auth_request)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 173, in refresh
    raise ValueError("Anonymous credentials cannot be refreshed.")
ValueError: Anonymous credentials cannot be refreshed.

It worked for me last week.

**Comment by yuzisun** [comment]
@xfzhang1974 Please use `gs://kfserving-examples/models/tensorflow/flowers` instead, the gcs bucket `kfserving-samples` has been deprecated.  KServe documentation has also updated to reflect that.

see https://github.com/kserve/kserve/pull/2215

**Comment by xfzhang1974** [comment]
Thanks for the update.
    On Saturday, June 11, 2022, 07:49:07 AM CDT, Dan Sun ***@***.***> wrote:  
 
 


@xfzhang1974 Please use gs://kfserving-examples/models/tensorflow/flowers instead, the gcs bucket kfserving-samples has been deprecated.

see #2215
