### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by wfg314** [kserve/kserve#2273]
/kind bug
Following 
    https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/transformer/feast:
I create an inferenceservice that include two deployment transformer and predictor, the inferenceservice's status is ok. but when I use this inferenceservice by send data to it,  I get error "socket.gaierror: [Errno -2] Name or service not known". The error finded in pod that belong to deployment transformer。

**What did you expect to happen:**
I expect to get right answer.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
My inferenceservice yaml:
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "transformer-wfg"
  annotations:
      sidecar.istio.io/inject: "false"
  namespace: "kubeflow-user-example-com"
spec:
  transformer:
    containers:
    - image: wfg1220/driver_transformer:1.0
      name: driver-container
      command:
      - "python"
      - "-m"
      - "driver_transformer"
      args:
      - --model_name
      - transformer-wfg
      - --predictor_host
      - transformer-wfg.kubeflow-user-example-com.example.com
  predictor:
    sklearn:
      storageUri: "pvc://fbr/windpowercurve/model/model.joblib"

My error:
2022-06-23T17:07:49.523757785+08:00 [E 220623 09:07:49 web:1789] Uncaught exception POST /v1/models/transformer-wfg:predict (127.0.0.1)
2022-06-23T17:07:49.523808863+08:00     HTTPServerRequest(protocol='http', host='transformer-wfg-transformer-default.kubeflow-user-example-com.svc.cluster.local', method='POST', uri='/v1/models/transformer-wfg:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
2022-06-23T17:07:49.523819780+08:00     Traceback (most recent call last):
2022-06-23T17:07:49.523826884+08:00       File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
2022-06-23T17:07:49.523830723+08:00         result = await result
2022-06-23T17:07:49.523835292+08:00       File "/usr/local/lib/python3.8/site-packages/kserve/handlers/predict.py", line 70, in post
2022-06-23T17:07:49.523839387+08:00         response = await model(body)
2022-06-23T17:07:49.523843349+08:00       File "/usr/local/lib/python3.8/site-packages/kserve/model.py", line 86, in __call__
2022-06-23T17:07:49.523846989+08:00         response = (await self.predict(request)) if inspect.iscoroutinefunction(self.predict) \
2022-06-23T17:07:49.523850688+08:00       File "/usr/local/lib/python3.8/site-packages/kserve/model.py", line 211, in predict
2022-06-23T17:07:49.523854306+08:00         return await self._http_predict(request)
2022-06-23T17:07:49.523860174+08:00       File "/usr/local/lib/python3.8/site-packages/kserve/model.py", line 182, in _http_predict
2022-06-23T17:07:49.523864025+08:00         response = await self._http_client.fetch(
2022-06-23T17:07:49.523886613+08:00       File "/usr/local/lib/python3.8/site-packages/tornado/simple_httpclient.py", line 338, in run
2022-06-23T17:07:49.523890618+08:00         stream = await self.tcp_client.connect(
2022-06-23T17:07:49.523893763+08:00       File "/usr/local/lib/python3.8/site-packages/tornado/tcpclient.py", line 265, in connect
2022-06-23T17:07:49.523897595+08:00         addrinfo = await self.resolver.resolve(host, port, af)
2022-06-23T17:07:49.523901888+08:00       File "/usr/local/lib/python3.8/site-packages/tornado/netutil.py", line 398, in resolve
2022-06-23T17:07:49.523905352+08:00         result = await IOLoop.current().run_in_executor(
2022-06-23T17:07:49.523909488+08:00       File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
2022-06-23T17:07:49.523929461+08:00         result = self.fn(*self.args, **self.kwargs)
2022-06-23T17:07:49.523933700+08:00       File "/usr/local/lib/python3.8/site-packages/tornado/netutil.py", line 382, in _resolve_addr
2022-06-23T17:07:49.523937540+08:00         addrinfo = socket.getaddrinfo(host, port, family, socket.SOCK_STREAM)
2022-06-23T17:07:49.523941372+08:00       File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
2022-06-23T17:07:49.523946179+08:00         for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2022-06-23T17:07:49.523950020+08:00     socket.gaierror: [Errno -2] Name or service not known
2022-06-23T17:07:49.524439957+08:00 [E 220623 09:07:49 web:2239] 500 POST /v1/models/transformer-wfg:predict (127.0.0.1) 1168.11ms

Send data to inferenceservice:
----------------------------------------------
from kserve import KServeClient
KServe = KServeClient()
import requests

name = "transformer-wfg"
namespace = "kubeflow-user-example-com"
isvc_resp = KServe.get(name, namespace=namespace)
isvc_url = isvc_resp['status']['address']['url']

print(isvc_url)

inference_input = {
  'instances': [
    [6.8],
    [6.0]
  ]
}
inference_input = {'windspeed':5.6,'windpower':560}
response = requests.post(isvc_url, json=inference_input)
print(response.text)

**Environment:**

- Istio Version: 1.11.0
- Knative Version: 0.22.1
- KFServing Version: 0.6.1
- Kubeflow version: 1.5.0
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:none
- Kubernetes version: (use `kubectl version`):v1.21.11+k3s1
- OS (e.g. from `/etc/os-release`): CentOS Linux 7

**Comment by yuzisun** [comment]
@wfg314 the predictor host you passed probably wrong on transformer, I do not think example.com actually exist

**Comment by wfg314** [comment]
@yuzisun But I get the predictor host by "kubectl get inferenceservice transformer-wfg -n kubeflow-user-example-com  -o jsonpath='{.status.url}' | cut -d "/" -f 3", the output is "transformer-wfg.kubeflow-user-example-com.example.com".

**Comment by yuzisun** [comment]
yes, but that's the example domain configuration, you will need to configure that to use your real domain. Also in this case you do not need to set the predictor host, kserve automatically fills that with internal predictor host.

**Comment by wfg314** [comment]
@yuzisun internal predictor host is ok, thank you.
