### ISSUE TITLE
Failure to install Kserve Python SDK with Python 3.8 or greater

### ISSUE THREAD

**Issue by Mgla96** [kserve/kserve#2314]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Failure to pip install Kserve Python SDK with Python 3.8 or greater

**What did you expect to happen:**
after doing a `pip install kserve` in a python:3.8 container (also replicated in python:3.9), then opening a python interactive session and doing `import kserve`, I expected to import the kserve SDK without any errors 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Example of error received when running python container, installing kserve sdk, and importing sdk

```bash
🐍🐍 ~ 🔧 docker run -it python:3.9-slim bash
root@b72024d94231:/# pip install kserve
Collecting kserve
  Downloading kserve-0.8.0.1-py3-none-any.whl (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.1/275.1 KB 6.0 MB/s eta 0:00:00
Collecting ray[serve]==1.9.0
  Downloading ray-1.9.0-cp39-cp39-manylinux2014_x86_64.whl (57.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 MB 17.3 MB/s eta 0:00:00
Collecting idna==3.2
  Downloading idna-3.2-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.6/59.6 KB 11.2 MB/s eta 0:00:00
Collecting azure-identity>=1.6.0
  Downloading azure_identity-1.10.0-py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.1/134.1 KB 33.1 MB/s eta 0:00:00
Collecting numpy~=1.19.2
  Downloading numpy-1.19.5-cp39-cp39-manylinux2010_x86_64.whl (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 29.8 MB/s eta 0:00:00
Collecting avro>=1.10.1
  Downloading avro-1.11.0.tar.gz (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.4/83.4 KB 22.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting urllib3>=1.15.1
  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.0/139.0 KB 26.7 MB/s eta 0:00:00
Collecting google-auth==1.34.0
  Downloading google_auth-1.34.0-py2.py3-none-any.whl (152 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.9/152.9 KB 28.6 MB/s eta 0:00:00
Collecting python-dateutil>=2.5.3
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 26.8 MB/s eta 0:00:00
Collecting minio<7.0.0,>=4.0.9
  Downloading minio-6.0.2-py2.py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 KB 13.9 MB/s eta 0:00:00
Collecting grpcio>=1.34.0
  Downloading grpcio-1.47.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 28.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.9/site-packages (from kserve) (58.1.0)
Collecting certifi==2021.5.30
  Downloading certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.5/145.5 KB 40.0 MB/s eta 0:00:00
Collecting cryptography==3.4.7
  Downloading cryptography-3.4.7-cp36-abi3-manylinux2014_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 28.2 MB/s eta 0:00:00
Collecting jmespath==0.10.0
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting cachetools==4.2.2
  Downloading cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting kubernetes>=12.0.0
  Downloading kubernetes-24.2.0-py2.py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 33.9 MB/s eta 0:00:00
Collecting psutil>=5.0
  Downloading psutil-5.9.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 281.1/281.1 KB 30.4 MB/s eta 0:00:00
Collecting boto3==1.20.24
  Downloading boto3-1.20.24-py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.8/131.8 KB 18.5 MB/s eta 0:00:00
Collecting googleapis-common-protos==1.53.0
  Downloading googleapis_common_protos-1.53.0-py2.py3-none-any.whl (198 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 198.2/198.2 KB 38.3 MB/s eta 0:00:00
Collecting cloudevents>=1.2.0
  Downloading cloudevents-1.2.0-py3-none-any.whl (26 kB)
Collecting azure-core==1.17.0
  Downloading azure_core-1.17.0-py2.py3-none-any.whl (165 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.8/165.8 KB 39.1 MB/s eta 0:00:00
Collecting table-logger>=0.3.5
  Downloading table_logger-0.3.6-py3-none-any.whl (14 kB)
Collecting tornado>=6.0.0
  Downloading tornado-6.2-cp37-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (423 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 424.0/424.0 KB 24.9 MB/s eta 0:00:00
Collecting adal>=1.2.2
  Downloading adal-1.2.7-py2.py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 KB 15.4 MB/s eta 0:00:00
Collecting six>=1.15
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting google-cloud-storage>=1.41.1
  Downloading google_cloud_storage-2.4.0-py2.py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.0/107.0 KB 16.5 MB/s eta 0:00:00
Collecting azure-storage-blob==12.8.1
  Downloading azure_storage_blob-12.8.1-py2.py3-none-any.whl (345 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.8/345.8 KB 21.6 MB/s eta 0:00:00
Collecting cffi==1.14.6
  Downloading cffi-1.14.6-cp39-cp39-manylinux1_x86_64.whl (405 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 405.7/405.7 KB 30.3 MB/s eta 0:00:00
Collecting argparse>=1.4.0
  Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting tritonclient==2.14.2
  Downloading tritonclient-2.14.2-py3-none-manylinux1_x86_64.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 30.3 MB/s eta 0:00:00
Collecting requests>=2.18.4
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 18.4 MB/s eta 0:00:00
Collecting msrest>=0.6.18
  Downloading msrest-0.7.1-py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 KB 9.7 MB/s eta 0:00:00
Collecting s3transfer<0.6.0,>=0.5.0
  Downloading s3transfer-0.5.2-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 20.7 MB/s eta 0:00:00
Collecting botocore<1.24.0,>=1.23.24
  Downloading botocore-1.23.54-py3-none-any.whl (8.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.5/8.5 MB 32.1 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 29.4 MB/s eta 0:00:00
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 35.8 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.8-py3-none-any.whl (39 kB)
Collecting protobuf>=3.12.0
  Downloading protobuf-4.21.2-cp37-abi3-manylinux2014_x86_64.whl (407 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 407.8/407.8 KB 21.7 MB/s eta 0:00:00
Collecting redis>=3.5.0
  Downloading redis-4.3.4-py3-none-any.whl (246 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 246.2/246.2 KB 12.0 MB/s eta 0:00:00
Collecting click>=7.0
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 10.3 MB/s eta 0:00:00
Collecting jsonschema
  Downloading jsonschema-4.6.1-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.8/80.8 KB 7.9 MB/s eta 0:00:00
Collecting pyyaml
  Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 KB 37.3 MB/s eta 0:00:00
Collecting attrs
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 15.6 MB/s eta 0:00:00
Collecting msgpack<2.0.0,>=1.0.0
  Downloading msgpack-1.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 KB 30.5 MB/s eta 0:00:00
Collecting filelock
  Downloading filelock-3.7.1-py3-none-any.whl (10 kB)
Collecting opencensus
  Downloading opencensus-0.10.0-py2.py3-none-any.whl (128 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 KB 33.1 MB/s eta 0:00:00
Collecting prometheus-client>=0.7.1
  Downloading prometheus_client-0.14.1-py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 KB 13.9 MB/s eta 0:00:00
Collecting smart-open
  Downloading smart_open-6.0.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.4/58.4 KB 14.4 MB/s eta 0:00:00
Collecting frozenlist
  Downloading frozenlist-1.3.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (156 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.2/156.2 KB 20.4 MB/s eta 0:00:00
Collecting gpustat>=1.0.0b1
  Downloading gpustat-1.0.0rc1.tar.gz (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 KB 18.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting colorful
  Downloading colorful-0.5.4-py2.py3-none-any.whl (201 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 202.0/202.0 KB 27.5 MB/s eta 0:00:00
Collecting aiosignal
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting uvicorn
  Downloading uvicorn-0.18.2-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.0/57.0 KB 3.1 MB/s eta 0:00:00
Collecting py-spy>=0.2.0
  Downloading py_spy-0.3.12-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 24.6 MB/s eta 0:00:00
Collecting aiohttp-cors
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl (27 kB)
Collecting starlette
  Downloading starlette-0.20.4-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 KB 18.1 MB/s eta 0:00:00
Collecting aiohttp>=3.7
  Downloading aiohttp-3.8.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 26.5 MB/s eta 0:00:00
Collecting fastapi
  Downloading fastapi-0.78.0-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 KB 4.6 MB/s eta 0:00:00
Collecting aioredis<2
  Downloading aioredis-1.3.1-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.3/65.3 KB 6.3 MB/s eta 0:00:00
Collecting python-rapidjson>=0.9.1
  Downloading python_rapidjson-1.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 14.5 MB/s eta 0:00:00
Collecting PyJWT<3,>=1.0.0
  Downloading PyJWT-2.4.0-py3-none-any.whl (18 kB)
Collecting msal<2.0.0,>=1.12.0
  Downloading msal-1.18.0-py2.py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.4/82.4 KB 20.0 MB/s eta 0:00:00
Collecting msal-extensions<2.0.0,>=0.3.0
  Downloading msal_extensions-1.0.0-py2.py3-none-any.whl (19 kB)
Collecting deprecation<3.0,>=2.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.8.2-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.6/114.6 KB 13.6 MB/s eta 0:00:00
Collecting google-cloud-core<3.0dev,>=2.3.0
  Downloading google_cloud_core-2.3.1-py2.py3-none-any.whl (29 kB)
Collecting google-resumable-media>=2.3.2
  Downloading google_resumable_media-2.3.3-py2.py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 KB 21.8 MB/s eta 0:00:00
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0
  Downloading websocket_client-1.3.3-py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.3/54.3 KB 14.3 MB/s eta 0:00:00
Collecting requests-oauthlib
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting pytz
  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 KB 25.0 MB/s eta 0:00:00
Collecting configparser
  Downloading configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (304 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.5/304.5 KB 22.5 MB/s eta 0:00:00
Collecting charset-normalizer<3.0,>=2.0
  Downloading charset_normalizer-2.1.0-py3-none-any.whl (39 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.2/114.2 KB 5.8 MB/s eta 0:00:00
Collecting hiredis
  Downloading hiredis-2.0.0-cp39-cp39-manylinux2010_x86_64.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 KB 14.6 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 10.8 MB/s eta 0:00:00
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.8.1-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 KB 28.0 MB/s eta 0:00:00
Collecting protobuf>=3.12.0
  Downloading protobuf-3.20.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 33.1 MB/s eta 0:00:00
Collecting google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5
  Downloading google_api_core-2.8.0-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 KB 15.7 MB/s eta 0:00:00
Collecting google-crc32c<2.0dev,>=1.0
  Downloading google_crc32c-1.3.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (36 kB)
Collecting nvidia-ml-py<=11.495.46,>=11.450.129
  Downloading nvidia_ml_py-11.495.46-py3-none-any.whl (25 kB)
Collecting blessed>=1.17.1
  Downloading blessed-1.19.1-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 KB 14.8 MB/s eta 0:00:00
Collecting portalocker<3,>=1.0
  Downloading portalocker-2.4.0-py2.py3-none-any.whl (16 kB)
Collecting isodate>=0.6.0
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 10.6 MB/s eta 0:00:00
Collecting msrest>=0.6.18
  Downloading msrest-0.7.0-py2.py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 KB 21.5 MB/s eta 0:00:00
  Downloading msrest-0.6.21-py2.py3-none-any.whl (85 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 KB 23.1 MB/s eta 0:00:00
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 KB 18.8 MB/s eta 0:00:00
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting oauthlib>=3.0.0
  Downloading oauthlib-3.2.0-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.5/151.5 KB 32.4 MB/s eta 0:00:00
Collecting pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2
  Downloading pydantic-1.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.4/12.4 MB 28.8 MB/s eta 0:00:00
Collecting starlette
  Downloading starlette-0.19.1-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.3/63.3 KB 15.4 MB/s eta 0:00:00
Collecting typing-extensions>=3.10.0
  Downloading typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting anyio<5,>=3.4.0
  Downloading anyio-3.6.1-py3-none-any.whl (80 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 KB 23.1 MB/s eta 0:00:00
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.6/115.6 KB 20.7 MB/s eta 0:00:00
Collecting opencensus-context>=0.1.2
  Downloading opencensus_context-0.1.2-py2.py3-none-any.whl (4.4 kB)
Collecting h11>=0.8
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 KB 14.0 MB/s eta 0:00:00
Collecting sniffio>=1.1
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting wcwidth>=0.1.4
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 KB 7.1 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 KB 23.5 MB/s eta 0:00:00
Building wheels for collected packages: avro, gpustat
  Building wheel for avro (pyproject.toml) ... done
  Created wheel for avro: filename=avro-1.11.0-py2.py3-none-any.whl size=115908 sha256=4a479731ef30f574f419c1f61e708ae71f42f88b201246ce630b71bccd55e32a
  Stored in directory: /root/.cache/pip/wheels/09/98/af/28b72da319fad61b62e4f94a70a1336523518d9b5ef0d86249
  Building wheel for gpustat (setup.py) ... done
  Created wheel for gpustat: filename=gpustat-1.0.0rc1-py3-none-any.whl size=18872 sha256=c1d7c98b6277b29f2811ac00ba4614d850a315eaccec0e346122c3abc9cde751
  Stored in directory: /root/.cache/pip/wheels/7c/4e/33/1a3f327bcffa30ccb8955326bbd5c6373447c23631005a8425
Successfully built avro gpustat
Installing collected packages: wcwidth, pytz, pyasn1, py-spy, opencensus-context, nvidia-ml-py, msgpack, colorful, certifi, argparse, wrapt, websocket-client, urllib3, typing-extensions, tornado, sniffio, smart-open, six, rsa, pyyaml, python-rapidjson, pyrsistent, pyparsing, PyJWT, pycparser, pyasn1-modules, psutil, protobuf, prometheus-client, portalocker, oauthlib, numpy, multidict, jmespath, idna, hiredis, h11, google-crc32c, frozenlist, filelock, configparser, click, charset-normalizer, cachetools, avro, attrs, async-timeout, yarl, uvicorn, tritonclient, table-logger, requests, python-dateutil, pydantic, packaging, jsonschema, isodate, grpcio, googleapis-common-protos, google-resumable-media, google-auth, deprecated, cffi, blessed, anyio, aiosignal, aioredis, starlette, requests-oauthlib, redis, minio, gpustat, google-api-core, deprecation, cryptography, botocore, azure-core, aiohttp, s3transfer, ray, opencensus, msrest, kubernetes, google-cloud-core, fastapi, cloudevents, aiohttp-cors, adal, msal, google-cloud-storage, boto3, azure-storage-blob, msal-extensions, azure-identity, kserve
Successfully installed PyJWT-2.4.0 adal-1.2.7 aiohttp-3.8.1 aiohttp-cors-0.7.0 aioredis-1.3.1 aiosignal-1.2.0 anyio-3.6.1 argparse-1.4.0 async-timeout-4.0.2 attrs-21.4.0 avro-1.11.0 azure-core-1.17.0 azure-identity-1.10.0 azure-storage-blob-12.8.1 blessed-1.19.1 boto3-1.20.24 botocore-1.23.54 cachetools-4.2.2 certifi-2021.5.30 cffi-1.14.6 charset-normalizer-2.1.0 click-8.1.3 cloudevents-1.2.0 colorful-0.5.4 configparser-5.2.0 cryptography-3.4.7 deprecated-1.2.13 deprecation-2.1.0 fastapi-0.78.0 filelock-3.7.1 frozenlist-1.3.0 google-api-core-2.8.0 google-auth-1.34.0 google-cloud-core-2.3.1 google-cloud-storage-2.4.0 google-crc32c-1.3.0 google-resumable-media-2.3.3 googleapis-common-protos-1.53.0 gpustat-1.0.0rc1 grpcio-1.47.0 h11-0.13.0 hiredis-2.0.0 idna-3.2 isodate-0.6.1 jmespath-0.10.0 jsonschema-4.6.1 kserve-0.8.0.1 kubernetes-24.2.0 minio-6.0.2 msal-1.18.0 msal-extensions-1.0.0 msgpack-1.0.4 msrest-0.6.21 multidict-6.0.2 numpy-1.19.5 nvidia-ml-py-11.495.46 oauthlib-3.2.0 opencensus-0.10.0 opencensus-context-0.1.2 packaging-21.3 portalocker-2.4.0 prometheus-client-0.14.1 protobuf-4.21.2 psutil-5.9.1 py-spy-0.3.12 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.21 pydantic-1.9.1 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 python-rapidjson-1.6 pytz-2022.1 pyyaml-6.0 ray-1.9.0 redis-4.3.4 requests-2.28.1 requests-oauthlib-1.3.1 rsa-4.8 s3transfer-0.5.2 six-1.16.0 smart-open-6.0.0 sniffio-1.2.0 starlette-0.19.1 table-logger-0.3.6 tornado-6.2 tritonclient-2.14.2 typing-extensions-4.3.0 urllib3-1.26.9 uvicorn-0.18.2 wcwidth-0.2.5 websocket-client-1.3.3 wrapt-1.14.1 yarl-1.7.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@b72024d94231:/# python3
Python 3.9.13 (main, Jun 23 2022, 11:19:48)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import kserve
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/kserve/__init__.py", line 16, in <module>
    from kserve.model import Model
  File "/usr/local/lib/python3.9/site-packages/kserve/model.py", line 26, in <module>
    from tritonclient.grpc import InferResult, service_pb2_grpc
  File "/usr/local/lib/python3.9/site-packages/tritonclient/grpc/__init__.py", line 41, in <module>
    from tritonclient.grpc import model_config_pb2
  File "/usr/local/lib/python3.9/site-packages/tritonclient/grpc/model_config_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Windows 10 Pro

**Comment by yuzisun** [comment]
@Mgla96 the protobuf 4.0 release broke the kserve sdk releases, see fixes in https://github.com/kserve/kserve/pull/2201, you can add the protobuf pin to fix this for now and we are releasing 0.9 shortly.
