### ISSUE TITLE
KServe controller crash on MetricsAggregator configuration

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2553]
/kind bug

**What steps did you take and what happened:**
KServe 0.10.0-rc0 controller crashes on creating an InferenceService with helm chart installation.

```bash
2022/11/20 15:32:57 http: panic serving 10.244.0.1:24365: Unable to unmarshall metricsAggregator json string due to json: cannot unmarshal bool into Go struct field MetricsAggregator.enableMetricAggregation of type string 
goroutine 1253 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x18901a0, 0xc000c95810})
	/usr/local/go/src/runtime/panic.go:844 +0x258
github.com/kserve/kserve/pkg/webhook/admission/pod.newMetricsAggregator(0xc000a752c0)
	/go/src/github.com/kserve/kserve/pkg/webhook/admission/pod/metrics_aggregate_injector.go:42 +0x12e
github.com/kserve/kserve/pkg/webhook/admission/pod.(*Mutator).mutate(0x18acd80?, 0x1e35348?, 0xc0001be318?)
	/go/src/github.com/kserve/kserve/pkg/webhook/admission/pod/mutator.go:114 +0x114
github.com/kserve/kserve/pkg/webhook/admission/pod.(*Mutator).Handle(_, {_, _}, {{{0xc001082ba0, 0x24}, {{0x0, 0x0}, {0xc000eea090, 0x2}, {0xc000eea092, ...}}, ...}})
	/go/src/github.com/kserve/kserve/pkg/webhook/admission/pod/mutator.go:65 +0x372
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).Handle(_, {_, _}, {{{0xc001082ba0, 0x24}, {{0x0, 0x0}, {0xc000eea090, 0x2}, {0xc000eea092, ...}}, ...}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/webhook.go:146 +0xa2
sigs.k8s.io/controller-runtime/pkg/webhook/admission.(*Webhook).ServeHTTP(0xc0006b35c0, {0x7f00563fb538?, 0xc000dbf8b0}, 0xc000d49500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/webhook/admission/http.go:99 +0xe90
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1({0x7f00563fb538, 0xc000dbf8b0}, 0x1e34400?)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:40 +0xd4
net/http.HandlerFunc.ServeHTTP(0x1e34430?, {0x7f00563fb538?, 0xc000dbf8b0?}, 0xc000ffba38?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1({0x1e34430?, 0xc00054ddc0?}, 0xc000d49500)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:117 +0xaa
net/http.HandlerFunc.ServeHTTP(0x2b58420?, {0x1e34430?, 0xc00054ddc0?}, 0x800?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2({0x1e34430, 0xc00054ddc0}, 0xc000d49500)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.1/prometheus/promhttp/instrument_server.go:84 +0xbf
net/http.HandlerFunc.ServeHTTP(0xb199ffb41?, {0x1e34430?, 0xc00054ddc0?}, 0xc0000ab860?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc001082af2?, {0x1e34430, 0xc00054ddc0}, 0xc000d49500)
	/usr/local/go/src/net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0x1e260e8?}, {0x1e34430, 0xc00054ddc0}, 0xc000d49500)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000915900, {0x1e353b8, 0xc00056fb30})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
```

**What did you expect to happen:**

**Anything else you would like to add:**

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
fixed in #2552
