### ISSUE TITLE
Error: Model with name BERTSeqClassification does not exist

### ISSUE THREAD

**Issue by praveeniitm** [kserve/kserve#2576]
/kind bug

**What steps did you take and what happened:**

Followed [Doc](https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/torchserve/v2/bert) to deploy bert sequence classifier with torchserve on Kserve.

**kubectl get pod**
```
NAME                                                              READY   STATUS    RESTARTS   AGE
sklearn-irisv2-predictor-default-00001-deployment-6476cfcdjjpws   2/2     Running   0          3h19m
torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp   2/2     Running   0          9m37s
```

**kubectl describe pod torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp**       
```                            
Name:             torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp
Namespace:        default
Priority:         0
Service Account:  default
Node:             kind-control-plane/172.18.0.3
Start Time:       Wed, 30 Nov 2022 00:56:33 +0530
Labels:           app=torchserve-bert-v2-predictor-default-00001
                  component=predictor
                  pod-template-hash=5676596ddd
                  service.istio.io/canonical-name=torchserve-bert-v2-predictor-default
                  service.istio.io/canonical-revision=torchserve-bert-v2-predictor-default-00001
                  serviceEnvelope=kservev2
                  serving.knative.dev/configuration=torchserve-bert-v2-predictor-default
                  serving.knative.dev/configurationGeneration=1
                  serving.knative.dev/configurationUID=35c2e5c5-e54b-42ad-98cd-8181f7c304af
                  serving.knative.dev/revision=torchserve-bert-v2-predictor-default-00001
                  serving.knative.dev/revisionUID=09ae5676-7bdf-456f-ac91-a54128317f88
                  serving.knative.dev/service=torchserve-bert-v2-predictor-default
                  serving.knative.dev/serviceUID=84917927-1410-4f13-bb51-3dd81520d7a5
                  serving.kserve.io/inferenceservice=torchserve-bert-v2
Annotations:      autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
                  autoscaling.knative.dev/minScale: 1
                  internal.serving.kserve.io/storage-initializer-sourceuri: gs://first_praveen_bucket/gcp
                  serving.knative.dev/creator: system:serviceaccount:kserve:kserve-controller-manager
Status:           Running
IP:               10.244.0.29
IPs:
  IP:           10.244.0.29
Controlled By:  ReplicaSet/torchserve-bert-v2-predictor-default-00001-deployment-5676596ddd
Init Containers:
  storage-initializer:
    Container ID:  containerd://0a502498a9a3b0d309ae4c7f9f1e93e4e6c79eb9477ede9edeef127c4e11de63
    Image:         kserve/storage-initializer:v0.9.0-rc0
    Image ID:      docker.io/kserve/storage-initializer@sha256:6cad6a39917c118c08eca833a16d347abf4b96342e00ddaf1535561077808192
    Port:          <none>
    Host Port:     <none>
    Args:
      gs://first_praveen_bucket/gcp
      /mnt/models
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 30 Nov 2022 00:56:34 +0530
      Finished:     Wed, 30 Nov 2022 00:58:02 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /mnt/models from kserve-provision-location (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-k7rbd (ro)
Containers:
  kserve-container:
    Container ID:  containerd://8a3794ffc838712991c43622821bc7cac51d4be6820461f6d54b81c75fe7f7e7
    Image:         index.docker.io/pytorch/torchserve-kfs@sha256:43c1c14b2768c0cd73ce40e23da0a56176532b3c0fcb8b2217c087da3054c372
    Image ID:      docker.io/pytorch/torchserve-kfs@sha256:43c1c14b2768c0cd73ce40e23da0a56176532b3c0fcb8b2217c087da3054c372
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      torchserve
      --start
      --model-store=/mnt/models/model-store
      --ts-config=/mnt/models/config/config.properties
    State:          Running
      Started:      Wed, 30 Nov 2022 00:58:02 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     1
      memory:  2Gi
    Environment:
      TS_SERVICE_ENVELOPE:  kservev2
      PORT:                 8080
      K_REVISION:           torchserve-bert-v2-predictor-default-00001
      K_CONFIGURATION:      torchserve-bert-v2-predictor-default
      K_SERVICE:            torchserve-bert-v2-predictor-default
    Mounts:
      /mnt/models from kserve-provision-location (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-k7rbd (ro)
  queue-proxy:
    Container ID:   containerd://a071b637707b0573b27f5ee7e6e1c174c7d4ec9dd79d1de3c7122208ed0f2095
    Image:          gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:a40f6e84de1a0d145d27084a94cc7fa221159e75cafde7d332ac8f4f0aed58fb
    Image ID:       gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:a40f6e84de1a0d145d27084a94cc7fa221159e75cafde7d332ac8f4f0aed58fb
    Ports:          8022/TCP, 9090/TCP, 9091/TCP, 8012/TCP, 8112/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Wed, 30 Nov 2022 00:58:02 +0530
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      25m
    Readiness:  http-get http://:8012/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                 default
      SERVING_SERVICE:                   torchserve-bert-v2-predictor-default
      SERVING_CONFIGURATION:             torchserve-bert-v2-predictor-default
      SERVING_REVISION:                  torchserve-bert-v2-predictor-default-00001
      QUEUE_SERVING_PORT:                8012
      QUEUE_SERVING_TLS_PORT:            8112
      CONTAINER_CONCURRENCY:             0
      REVISION_TIMEOUT_SECONDS:          300
      SERVING_POD:                       torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp (v1:metadata.name)
      SERVING_POD_IP:                     (v1:status.podIP)
      SERVING_LOGGING_CONFIG:            
      SERVING_LOGGING_LEVEL:             
      SERVING_REQUEST_LOG_TEMPLATE:      {"httpRequest": {"requestMethod": "{{.Request.Method}}", "requestUrl": "{{js .Request.RequestURI}}", "requestSize": "{{.Request.ContentLength}}", "status": {{.Response.Code}}, "responseSize": "{{.Response.Size}}", "userAgent": "{{js .Request.UserAgent}}", "remoteIp": "{{js .Request.RemoteAddr}}", "serverIp": "{{.Revision.PodIP}}", "referer": "{{js .Request.Referer}}", "latency": "{{.Response.Latency}}s", "protocol": "{{.Request.Proto}}"}, "traceId": "{{index .Request.Header "X-B3-Traceid"}}"}
      SERVING_ENABLE_REQUEST_LOG:        false
      SERVING_REQUEST_METRICS_BACKEND:   prometheus
      TRACING_CONFIG_BACKEND:            none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:    
      TRACING_CONFIG_DEBUG:              false
      TRACING_CONFIG_SAMPLE_RATE:        0.1
      USER_PORT:                         8080
      SYSTEM_NAMESPACE:                  knative-serving
      METRICS_DOMAIN:                    knative.dev/internal/serving
      SERVING_READINESS_PROBE:           {"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                  false
      SERVING_ENABLE_PROBE_REQUEST_LOG:  false
      METRICS_COLLECTOR_ADDRESS:         
      CONCURRENCY_STATE_ENDPOINT:        
      CONCURRENCY_STATE_TOKEN_PATH:      /var/run/secrets/tokens/state-token
      HOST_IP:                            (v1:status.hostIP)
      ENABLE_HTTP2_AUTO_DETECTION:       false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-k7rbd (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-k7rbd:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
  kserve-provision-location:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  10m                    default-scheduler  Successfully assigned default/torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp to kind-control-plane
  Normal   Pulled     10m                    kubelet            Container image "kserve/storage-initializer:v0.9.0-rc0" already present on machine
  Normal   Created    10m                    kubelet            Created container storage-initializer
  Normal   Started    10m                    kubelet            Started container storage-initializer
  Normal   Pulled     8m56s                  kubelet            Container image "index.docker.io/pytorch/torchserve-kfs@sha256:43c1c14b2768c0cd73ce40e23da0a56176532b3c0fcb8b2217c087da3054c372" already present on machine
  Normal   Created    8m56s                  kubelet            Created container kserve-container
  Normal   Started    8m56s                  kubelet            Started container kserve-container
  Normal   Pulled     8m56s                  kubelet            Container image "gcr.io/knative-releases/knative.dev/serving/cmd/queue@sha256:a40f6e84de1a0d145d27084a94cc7fa221159e75cafde7d332ac8f4f0aed58fb" already present on machine
  Normal   Created    8m56s                  kubelet            Created container queue-proxy
  Normal   Started    8m56s                  kubelet            Started container queue-proxy
  Warning  Unhealthy  8m44s (x4 over 8m54s)  kubelet            Readiness probe failed: Get "http://10.244.0.29:8012/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

```

**Port Forward for testing purpose**

INGRESS_GATEWAY_SERVICE=$(kubectl get svc --namespace istio-system --selector="app=istio-ingressgateway" --output jsonpath='{.items[0].metadata.name}')
kubectl port-forward --namespace istio-system svc/${INGRESS_GATEWAY_SERVICE} 8080:80
**start another terminal**
export INGRESS_HOST=localhost
export INGRESS_PORT=8080

**What did you expect to happen:**

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: "torchserve-bert-v2"
spec:
  predictor:
    pytorch:
      protocolVersion: v2
      storageUri: <GCP model path>
**GCP model path contains- 
├── config
│   ├── config.properties
├── model-store
│   ├── BERTSeqClassification.mar**

```

**Anything else you would like to add:**

**Request Input file-> bert_v2.json**
```
{
  "id": "d3b15cad-50a2-4eaf-80ce-8b0a428bd298",
  "inputs": [{
    "name": "4b7c7d4a-51e4-43c8-af61-04639f6ef4bc",
    "shape": -1,
    "datatype": "BYTES",
    "data": "{\"text\":\"Bloomberg has decided to publish a new report on the global economy.\", \"target\":1}"
  }
  ]
}
```

**Inference request URL**
```
SERVICE_HOSTNAME=$(kubectl get inferenceservice torchserve-bert-v2 -o jsonpath='{.status.url}' | cut -d "/" -f 3)

curl -v \
  -H "Host: ${SERVICE_HOSTNAME}" \
  -H "Content-Type: application/json" \
  -d @./bert_v2.json \
  http://${INGRESS_HOST}:${INGRESS_PORT}/v2/models/BERTSeqClassification/infer
```

**Response** 
```
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v2/models/BERTSeqClassification/infer HTTP/1.1
> Host: torchserve-bert-v2.default.example.com
> User-Agent: curl/7.84.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 271
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 66
< content-type: application/json; charset=UTF-8
< date: Tue, 29 Nov 2022 19:34:59 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 9
< 
* Connection #0 to host localhost left intact
{"error": "Model with name BERTSeqClassification does not exist."}% 
```

**kubectl logs torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp**         
 ```                                 
Defaulted container "kserve-container" out of: kserve-container, queue-proxy, storage-initializer (init)
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-11-29T19:28:20,943 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-11-29T19:28:22,146 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.6.0
TS Home: /usr/local/lib/python3.8/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 7
Max heap size: 4494 M
Python executable: /usr/bin/python
Config file: /mnt/models/config/config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8086
Metrics address: http://0.0.0.0:8082
Model Store: /mnt/models/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 4
Netty client threads: 0
Default workers per model: 7
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /mnt/models/model-store
Model config: N/A
2022-11-29T19:28:22,256 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-11-29T19:28:22,656 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"bert":{"1.0":{"defaultVersion":true,"marName":"BERTSeqClassification.mar","minWorkers":1,"maxWorkers":5,"batchSize":2,"maxBatchDelay":500,"responseTimeout":60}}}}
2022-11-29T19:28:22,850 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2022-11-29T19:28:22,925 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
[I 221129 19:28:24 __main__:75] Wrapper : Model names ['bert'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8086, model store /mnt/models/model-store
[I 221129 19:28:24 TorchserveModel:54] kfmodel Predict URL set to 0.0.0.0:8085
[I 221129 19:28:24 TorchserveModel:56] kfmodel Explain URL set to 0.0.0.0:8085
[I 221129 19:28:24 TSModelRepository:30] TSModelRepo is initialized
[I 221129 19:28:24 model_server:150] Registering model: bert
[I 221129 19:28:24 model_server:123] Listening on port 8080
[I 221129 19:28:24 model_server:125] Will fork 1 workers
[I 221129 19:28:24 model_server:128] Setting max asyncio worker threads as 11
2022-11-29T19:28:46,328 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model bert
2022-11-29T19:28:46,330 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model bert
2022-11-29T19:28:46,331 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model bert
2022-11-29T19:28:46,332 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model bert loaded.
2022-11-29T19:28:46,333 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: bert, count: 1
2022-11-29T19:28:46,530 [DEBUG] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/usr/bin/python, /usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000]
2022-11-29T19:28:46,627 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2022-11-29T19:28:48,722 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8085
2022-11-29T19:28:48,725 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2022-11-29T19:28:48,733 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8086
2022-11-29T19:28:48,735 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2022-11-29T19:28:48,739 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:8082
Model server started.
2022-11-29T19:28:52,241 [WARN ] pool-3-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2022-11-29T19:28:53,466 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:40.0|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,523 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:229.0811767578125|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,525 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:38.98243713378906|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,527 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:14.5|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,529 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:13237.20703125|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,530 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:4136.36328125|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:53,532 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:26.4|#Level:Host|#hostname:torchserve-bert-v2-predictor-default-00001-deployment-5676v48gp,timestamp:1669750133
2022-11-29T19:28:55,315 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2022-11-29T19:28:55,318 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - [PID]59
2022-11-29T19:28:55,322 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Torch worker started.
2022-11-29T19:28:55,323 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Python runtime: 3.8.0
2022-11-29T19:28:55,329 [DEBUG] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bert_1.0 State change null -> WORKER_STARTED
2022-11-29T19:28:55,515 [INFO ] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2022-11-29T19:28:55,948 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2022-11-29T19:28:56,424 [INFO ] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1669750136359
2022-11-29T19:28:57,594 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - model_name: bert, batchSize: 2
2022-11-29T19:29:01,332 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - generated new fontManager
2022-11-29T19:29:04,773 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Transformers version 4.11.0
2022-11-29T19:29:04,801 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Backend worker process died.
2022-11-29T19:29:04,802 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2022-11-29T19:29:04,827 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 210, in <module>
2022-11-29T19:29:04,829 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     worker.run_server()
2022-11-29T19:29:04,832 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 181, in run_server
2022-11-29T19:29:04,834 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2022-11-29T19:29:04,837 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 139, in handle_connection
2022-11-29T19:29:04,838 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2022-11-29T19:29:04,839 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 104, in load_model
2022-11-29T19:29:04,840 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     service = model_loader.load(
2022-11-29T19:29:04,842 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_loader.py", line 151, in load
2022-11-29T19:29:04,843 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2022-11-29T19:29:04,833 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2022-11-29T19:29:04,846 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/053bb446d6094183a82b99d6f359f99d/Transformer_handler_generalized.py", line 71, in initialize
2022-11-29T19:29:04,847 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     self.model = torch.jit.load(model_pt_path, map_location=self.device)
2022-11-29T19:29:04,922 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/torch/jit/_serialization.py", line 162, in load
2022-11-29T19:29:04,924 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG -     cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
2022-11-29T19:29:04,925 [INFO ] W-9000-bert_1.0-stdout MODEL_LOG - RuntimeError: version_ <= kMaxSupportedFileFormatVersionINTERNAL ASSERT FAILED at "../caffe2/serialize/inline_container.cc":147, please report a bug to PyTorch. Attempted to read a PyTorch file with version 10, but the maximum supported version for reading is 9. Your PyTorch installation may be too old.
2022-11-29T19:29:04,945 [DEBUG] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2022-11-29T19:29:04,946 [DEBUG] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:189) [model-server.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-11-29T19:29:05,849 [WARN ] W-9000-bert_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: bert, error: Worker died.
2022-11-29T19:29:05,850 [DEBUG] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bert_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2022-11-29T19:29:05,927 [WARN ] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bert_1.0-stderr
2022-11-29T19:29:05,929 [WARN ] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bert_1.0-stdout
2022-11-29T19:29:05,934 [INFO ] W-9000-bert_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.

```

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by praveeniitm** [comment]
pytorch version mismatch was there. Created pytorch trace model with torch 1.13 and inside kserve torch version was 1.11 so it was creating issue while loading the trace model inside kserve environments.
