### ISSUE TITLE
Error setting up KServe Torchserve example on AKS (Azure Kubernetes Service)

### ISSUE THREAD

**Issue by KaiKustermann** [kserve/kserve#2621]
I tried setting up [this](https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/torchserve/v2/bert) example on AKS (CPU YAML), and ran into following error. Torchserve seems to start without problems, then it just stopps immediately after starting. Do you have any idea where the issue could be?
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2022-12-26T17:43:36,505 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2022-12-26T17:43:36,815 [INFO ] main org.pytorch.serve.ModelServer -
Torchserve version: 0.6.0
TS Home: /usr/local/lib/python3.8/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 1
Max heap size: 494 M
Python executable: /usr/bin/python
Config file: /mnt/models/config/config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8085
Metrics address: http://0.0.0.0:8082
Model Store: /mnt/models/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 4
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /mnt/models/model-store
Model config: N/A
2022-12-26T17:43:36,838 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2022-12-26T17:43:36,914 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"BERTSeqClassification":{"1.0":{"defaultVersion":true,"marName":"BERTSeqClassification.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"responseTimeout":120}}}}
2022-12-26T17:43:36,982 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2022-12-26T17:43:36,984 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
[I 221226 17:43:37 __main__:75] Wrapper : Model names ['BERTSeqClassification'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8085, model store /mnt/models/model-store
[I 221226 17:43:37 TorchserveModel:54] kfmodel Predict URL set to 0.0.0.0:8085
[I 221226 17:43:37 TorchserveModel:56] kfmodel Explain URL set to 0.0.0.0:8085
[I 221226 17:43:37 TSModelRepository:30] TSModelRepo is initialized
[I 221226 17:43:37 model_server:150] Registering model: BERTSeqClassification
[I 221226 17:43:37 model_server:123] Listening on port 8080
[I 221226 17:43:37 model_server:125] Will fork 1 workers
[I 221226 17:43:37 model_server:128] Setting max asyncio worker threads as 5
2022-12-26T17:43:51,688 [INFO ] main org.pytorch.serve.ModelServer - Torchserve stopped.
java.lang.NullPointerException
        at org.pytorch.serve.wlm.Model.setModelState(Model.java:83)
        at org.pytorch.serve.wlm.ModelManager.createModel(ModelManager.java:294)
        at org.pytorch.serve.wlm.ModelManager.registerAndUpdateModel(ModelManager.java:91)
        at org.pytorch.serve.snapshot.SnapshotManager.initModels(SnapshotManager.java:136)
        at org.pytorch.serve.snapshot.SnapshotManager.restore(SnapshotManager.java:119)
        at org.pytorch.serve.ModelServer.initModelStore(ModelServer.java:152)
        at org.pytorch.serve.ModelServer.startRESTserver(ModelServer.java:356)
        at org.pytorch.serve.ModelServer.startAndWait(ModelServer.java:117)
        at org.pytorch.serve.ModelServer.main(ModelServer.java:98)
[I 221226 17:52:16 web:2239] 200 GET / (127.0.0.1) 1.49ms
[W 221226 17:53:53 web:2239] 405 POST / (127.0.0.1) 0.85ms
[I 221226 18:14:23 web:2239] 200 GET / (127.0.0.1) 0.48ms
[W 221226 18:16:02 web:2239] 405 POST / (127.0.0.1) 0.56ms
[W 221226 18:17:03 web:2239] 405 POST / (127.0.0.1) 0.63ms
[W 221226 18:18:01 web:2239] 405 POST / (127.0.0.1) 0.54ms
```

**Comment by KaiKustermann** [comment]
Solution: In config.properties file I added "maxBatchDelay":500 to the key model_snapshot. I dont know why, but then it works. Seems to be an issue with torchserve, as the error also comes up locally.
