### ISSUE TITLE
Deploy PyTorch model with TorchServe InferenceService Example does not work

### ISSUE THREAD

**Issue by hugcyrill** [kserve/kserve#2631]
/kind bug

**What steps did you take and what happened:**
I followed the Deploy PyTorch model with TorchServe InferenceService Example here: (https://kserve.github.io/website/modelserving/v1beta1/torchserve/)

The inference service was created and showed up as READY:TRUE.
However, when looking at the logs of the pod (container `kserve-container`), it showed that the worker died.

LOGS:
------------------

WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-01-04T17:19:27,271 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-01-04T17:19:27,654 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.6.0
TS Home: /usr/local/lib/python3.8/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Number of GPUs: 0
Number of CPUs: 8
Max heap size: 8026 M
Python executable: /usr/bin/python
Config file: /mnt/models/config/config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8081
Metrics address: http://0.0.0.0:8082
Model Store: /mnt/models/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 4
Netty client threads: 0
Default workers per model: 8
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: false
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /mnt/models/model-store
Model config: N/A
2023-01-04T17:19:27,663 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-01-04T17:19:27,688 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"mnist":{"1.0":{"defaultVersion":true,"marName":"mnist.mar","minWorkers":1,"maxWorkers":5,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
2023-01-04T17:19:27,760 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2023-01-04T17:19:27,761 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
2023-01-04T17:19:28,269 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model mnist
2023-01-04T17:19:28,269 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model mnist
2023-01-04T17:19:28,270 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model mnist
2023-01-04T17:19:28,270 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model mnist loaded.
2023-01-04T17:19:28,270 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: mnist, count: 1
2023-01-04T17:19:28,366 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2023-01-04T17:19:28,365 [DEBUG] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/usr/bin/python, /usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000]
2023-01-04T17:19:28,853 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8085
2023-01-04T17:19:28,854 [INFO ] main org.pytorch.serve.ModelServer - Initialize Management server with: EpollServerSocketChannel.
2023-01-04T17:19:28,855 [INFO ] main org.pytorch.serve.ModelServer - Management API bind to: http://0.0.0.0:8081
2023-01-04T17:19:28,855 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2023-01-04T17:19:28,856 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:8082
[I 230104 17:19:29 __main__:75] Wrapper : Model names ['mnist'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8081, model store /mnt/models/model-store
[I 230104 17:19:29 TorchserveModel:54] kfmodel Predict URL set to 0.0.0.0:8085
[I 230104 17:19:29 TorchserveModel:56] kfmodel Explain URL set to 0.0.0.0:8085
[I 230104 17:19:29 TSModelRepository:30] TSModelRepo is initialized
[I 230104 17:19:29 model_server:150] Registering model: mnist
[I 230104 17:19:29 model_server:123] Listening on port 8080
[I 230104 17:19:29 model_server:125] Will fork 1 workers
[I 230104 17:19:29 model_server:128] Setting max asyncio worker threads as 12
Model server started.
2023-01-04T17:19:29,672 [WARN ] pool-3-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2023-01-04T17:19:29,959 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,960 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:13.193183898925781|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,961 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:25.375598907470703|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,961 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:65.8|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,961 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:29446.06640625|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,961 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:2227.64453125|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:29,962 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:8.3|#Level:Host|#hostname:torchserve-predictor-default-00001-deployment-76d76564c7-smz2h,timestamp:1672852769
2023-01-04T17:19:30,226 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2023-01-04T17:19:30,226 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - [PID]48
2023-01-04T17:19:30,227 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Torch worker started.
2023-01-04T17:19:30,227 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Python runtime: 3.8.0
2023-01-04T17:19:30,227 [DEBUG] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mnist_1.0 State change null -> WORKER_STARTED
2023-01-04T17:19:30,234 [INFO ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2023-01-04T17:19:30,243 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2023-01-04T17:19:30,246 [INFO ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1672852770246
2023-01-04T17:19:30,297 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - model_name: mnist, batchSize: 1
2023-01-04T17:19:30,893 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - generated new fontManager
2023-01-04T17:19:31,509 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Backend worker process died.
2023-01-04T17:19:31,509 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2023-01-04T17:19:31,510 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 210, in <module>
2023-01-04T17:19:31,510 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     worker.run_server()
2023-01-04T17:19:31,510 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 181, in run_server
2023-01-04T17:19:31,510 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2023-01-04T17:19:31,511 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 139, in handle_connection
2023-01-04T17:19:31,511 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2023-01-04T17:19:31,511 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2023-01-04T17:19:31,511 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py", line 104, in load_model
2023-01-04T17:19:31,511 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     service = model_loader.load(
2023-01-04T17:19:31,512 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_loader.py", line 127, in load
2023-01-04T17:19:31,512 [DEBUG] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2023-01-04T17:19:31,512 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     envelope_class = self._load_default_envelope(envelope)
2023-01-04T17:19:31,512 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.8/dist-packages/ts/model_loader.py", line 172, in _load_default_envelope
2023-01-04T17:19:31,513 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     module = importlib.import_module(
2023-01-04T17:19:31,513 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2023-01-04T17:19:31,513 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -     return _bootstrap._gcd_import(name[level:], package, level)
2023-01-04T17:19:31,513 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2023-01-04T17:19:31,514 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2023-01-04T17:19:31,514 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG -   File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
2023-01-04T17:19:31,514 [INFO ] W-9000-mnist_1.0-stdout MODEL_LOG - ModuleNotFoundError: No module named 'ts.torch_handler.request_envelope.kfserving'
2023-01-04T17:19:31,512 [DEBUG] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2056) ~[?:?]
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2133) ~[?:?]
        at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:432) ~[?:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:189) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
2023-01-04T17:19:31,554 [WARN ] W-9000-mnist_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: mnist, error: Worker died.
2023-01-04T17:19:31,555 [DEBUG] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-mnist_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2023-01-04T17:19:31,555 [WARN ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mnist_1.0-stderr
2023-01-04T17:19:31,555 [WARN ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-mnist_1.0-stdout
2023-01-04T17:19:31,556 [INFO ] W-9000-mnist_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 1 seconds.
2023-01-04T17:19:31,564 [INFO ] W-9000-mnist_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mnist_1.0-stdout
2023-01-04T17:19:31,564 [INFO ] W-9000-mnist_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-mnist_1.0-stderr

**What did you expect to happen:**
I expected the worker to load the model and accept connections for inference.

**What's the InferenceService yaml:**
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"name":"torchserve","namespace":"default"},"spec":{"predictor":{"pytorch":{"storageUri":"gs://kfserving-examples/models/torchserve/image_classifier"}}}}
  creationTimestamp: "2023-01-04T17:19:19Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  name: torchserve
  namespace: default
  resourceVersion: "19132"
  uid: cb162ca6-382c-4936-a04f-b6baadfec913
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ""
      resources: {}
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier
status:
  address:
    url: http://torchserve.default.svc.cluster.local/v1/models/torchserve:predict
  components:
    predictor:
      address:
        url: http://torchserve-predictor-default.default.svc.cluster.local
      latestCreatedRevision: torchserve-predictor-default-00001
      latestReadyRevision: torchserve-predictor-default-00001
      latestRolledoutRevision: torchserve-predictor-default-00001
      traffic:
      - latestRevision: true
        percent: 100
        revisionName: torchserve-predictor-default-00001
      url: http://torchserve-predictor-default.default.example.com
  conditions:
  - lastTransitionTime: "2023-01-04T17:19:31Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2023-01-04T17:19:31Z"
    severity: Info
    status: "True"
    type: PredictorConfigurationReady
  - lastTransitionTime: "2023-01-04T17:19:31Z"
    status: "True"
    type: PredictorReady
  - lastTransitionTime: "2023-01-04T17:19:31Z"
    severity: Info
    status: "True"
    type: PredictorRouteReady
  - lastTransitionTime: "2023-01-04T17:19:31Z"
    status: "True"
    type: Ready
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  url: http://torchserve.default.example.com

**Anything else you would like to add:**
I am using the KServe "Quickstart" environment as described here: https://kserve.github.io/website/0.9/get_started/
I have tried different images for the inference service and it seems that the image pytorch/torchserve-kfs:0.4.1 is the last one to load the model. Anything newer and the model will not load.

**Environment:**

- Istio Version: 1.14.0
- Knative Version: 1.4.0
- KServe Version: 0.9.0-rc0
- Kubeflow version: N/A
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: on-prem K8s v1.22.17
- Minikube/Kind version: N/A
- Kubernetes version: (use `kubectl version`): v1.22.17
- OS (e.g. from `/etc/os-release`): 22.04.1 LTS

**Comment by yuzisun** [comment]
@hugcyrill i think you need to follow the 0.9 doc https://kserve.github.io/website/0.9/modelserving/v1beta1/torchserve/#creating-model-storage-with-model-archive-and-config-file, the doc you linked was for 0.7

**Comment by hugcyrill** [comment]
@yuzisun Thank you! That is exactly what happened. I think the problem is that the referenced example GCS bucket (gs://kfserving-examples/models/torchserve/image_classifier) has the `config.properties` with the `service_envelope` property. So if you simply follow the guide and do not create the model.mar and config.properties file yourself, you will run into this issue. 

I therefore suggest to change this section from the documentation [here](https://kserve.github.io/website/0.9/modelserving/v1beta1/torchserve/#creating-model-storage-with-model-archive-and-config-file):

_For remote storage you can choose to start the example using the prebuilt mnist MAR file stored on KServe example GCS bucket gs://kfserving-examples/models/torchserve/image_classifier, or generate the MAR file with torch-model-archiver and create the model store on remote storage according to the above layout._

**Comment by yuzisun** [comment]
@hugcyrill i think the example model was updated when releasing 0.9, are you running older version of kserve ? Looks like your torchserve runtime version is old which still refers to kfserving and in 0.9 the default torchserve version is 0.6.0.

**Comment by jagadeeshi2i** [comment]
@hugcyrill . Pls use `gs://kfserving-examples/models/torchserve/image_classifier/v1` for `v1` and `gs://kfserving-examples/models/torchserve/image_classifier/v2` for `v2`

I have updated the docs and will be fixed in  #2635

**Comment by hugcyrill** [comment]
Perfect thank you @jagadeeshi2i and @yuzisun!
