### ISSUE TITLE
AttributeError: 'FastAPI' object has no attribute 'debug' in e2e tests

### ISSUE THREAD

**Issue by yuzisun** [kserve/kserve#2691]
/kind bug

**What steps did you take and what happened:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/xgbserver/xgbserver/__main__.py", line 44, in <module>
    kserve.ModelServer(
  File "/kserve/kserve/model_server.py", line 148, in start
    asyncio.run(servers_task())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/kserve/kserve/model_server.py", line 146, in servers_task
    await asyncio.gather(*servers)
  File "/kserve/kserve/model_server.py", line 138, in serve
    server = UvicornProcess(self.http_port, [serversocket],
  File "/kserve/kserve/protocol/rest/server.py", line 128, in __init__
    app = self.server.create_application()
  File "/kserve/kserve/protocol/rest/server.py", line 67, in create_application
    return FastAPI(
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 146, in __init__
    self.middleware_stack: ASGIApp = self.build_middleware_stack()
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 152, in build_middleware_stack
    debug = self.debug
AttributeError: 'FastAPI' object has no attribute 'debug'
```

see https://github.com/tiangolo/fastapi/discussions/5977

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: v0.10.0
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
The issue is here https://github.com/kserve/kserve/blob/01853af81060cac139ea372a8786763f1c220cb1/python/xgb.Dockerfile#L8, xgbserver is still using the old pip version which does not resolve to the right starlette version.

ERROR: fastapi 0.88.0 has requirement starlette==0.22.0, but you'll have starlette 0.24.0 which is incompatible.
