### ISSUE TITLE
Kserve-controller-manager fails to reconcile a sample ISVC

### ISSUE THREAD

**Issue by lmyslinski** [kserve/kserve#2698]
/kind bug

**What steps did you take and what happened:**

- Running the iris sample from the docs (https://kserve.github.io/website/0.10/get_started/first_isvc/#2-create-an-inferenceservice)
- The isvc deployment fails to start with:

```
~> k logs sklearn-iris-predictor-default-00001-deployment-78486fb5bfq86lj                                                                                                                                                                                  ⎈ lke93188-ctx/kserve 15:30:17
Defaulted container "kserve-container" out of: kserve-container, queue-proxy
2023-02-16 14:30:02.962 1 root INFO [download():63] Copying contents of /mnt/models to local
2023-02-16 14:30:02.964 1 root ERROR [<module>():39] fail to locate model file for model sklearn-iris under dir /mnt/models,trying loading from model repository.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 42, in <module>
    kserve.ModelServer(registered_models=SKLearnModelRepository(args.model_dir)).start(
  File "/sklearnserver/sklearnserver/sklearn_model_repository.py", line 24, in __init__
    self.load_models()
  File "/kserve/kserve/model_repository.py", line 37, in load_models
    for name in os.listdir(self.models_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models'
```
The init container is never created and no mount is present so the error is not surprising.

The controller-manager says it's failing to reconcile, but I can't figure out what that means or where it could come from:

```
{"level":"info","ts":1676556803.4826725,"logger":"KsvcReconciler","msg":"revision status:","LatestRolledoutRevision":"","LatestReadyRevision":"","LatestCreatedRevision":"","PreviousRolledoutRevision":"","CanaryTrafficPercent":null}
{"level":"info","ts":1676556803.483066,"logger":"KsvcReconciler","msg":"knative service configuration diff (-desired, +observed):","diff":""}
{"level":"info","ts":1676556803.483083,"logger":"KsvcReconciler","msg":"Updating knative service","namespace":"kserve","name":"sklearn-iris-predictor-default"}
{"level":"info","ts":1676556803.7934475,"logger":"KsvcReconciler","msg":"Updating knative service","namespace":"kserve","name":"sklearn-iris-predictor-default"}
{"level":"info","ts":1676556803.9980865,"logger":"KsvcReconciler","msg":"Updating knative service","namespace":"kserve","name":"sklearn-iris-predictor-default"}
{"level":"info","ts":1676556804.1036541,"logger":"KsvcReconciler","msg":"Updating knative service","namespace":"kserve","name":"sklearn-iris-predictor-default"}
{"level":"info","ts":1676556804.201095,"logger":"KsvcReconciler","msg":"Updating knative service","namespace":"kserve","name":"sklearn-iris-predictor-default"}
{"level":"error","ts":1676556804.2134068,"logger":"v1beta1Controllers.InferenceService","msg":"Failed to reconcile","reconciler":"<*components.Predictor Value>","Name":"sklearn-iris","error":"fails to reconcile predictor: fails to update knative service: Operation cannot be fulfilled on services.serving.knative.dev \"sklearn-iris-predictor-default\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on services.serving.knative.dev \"sklearn-iris-predictor-default\": the object has been modified; please apply your changes to the latest version and try again\nfails to update knative service\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/knative.(*KsvcReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/reconcilers/knative/ksvc_reconciler.go:217\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:293\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:179\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571\nfails to reconcile predictor\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:295\ngithub.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:179\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1571","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
{"level":"error","ts":1676556804.287762,"logger":"v1beta1Controllers.InferenceService","msg":"Failed to update InferenceService status","InferenceService":"sklearn-iris","error":"Operation cannot be fulfilled on inferenceservices.serving.kserve.io \"sklearn-iris\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile\n\t/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:183\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

**What did you expect to happen:**

The ISVC starts correctly

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The installation process went pretty smoothly, seems like everything is running correctly:

```
NAMESPACE         NAME                                                              READY   STATUS             RESTARTS        AGE
cert-manager      cert-manager-59bf757d77-gn462                                     1/1     Running            0               22m
cert-manager      cert-manager-cainjector-547c9b8f95-f2x9q                          1/1     Running            0               22m
cert-manager      cert-manager-webhook-6787f645b9-xjl2h                             1/1     Running            0               22m
istio-system      istio-ingressgateway-6cc5d8b655-rq5k6                             1/1     Running            0               23m
istio-system      istiod-784bcfdd5d-rxwh6                                           1/1     Running            0               23m
knative-serving   activator-7cbbfbc85-rbwdr                                         1/1     Running            0               25m
knative-serving   autoscaler-8f986cff-zm2rk                                         1/1     Running            0               25m
knative-serving   controller-58dfb45d74-d58s8                                       1/1     Running            0               25m
knative-serving   domain-mapping-5d8db49bf6-m5gtb                                   1/1     Running            0               25m
knative-serving   domainmapping-webhook-584476fd67-5zhvs                            1/1     Running            0               25m
knative-serving   net-istio-controller-b98f9f78b-kl64m                              1/1     Running            0               23m
knative-serving   net-istio-webhook-7f6657c874-xsz9k                                1/1     Running            0               23m
knative-serving   webhook-6d5c55fd8c-54rr9                                          1/1     Running            0               25m
kserve            kserve-controller-manager-5d577f846b-6ss59                        2/2     Running            0               21m
kserve            sklearn-iris-predictor-default-00001-deployment-78486fb5bfq86lj   0/2     CrashLoopBackOff   8 (3m54s ago)   20m
kube-system       calico-kube-controllers-69499cbf66-xbj79                          1/1     Running            0               126m
kube-system       calico-node-b45sl                                                 1/1     Running            0               124m
kube-system       calico-node-hk5xc                                                 1/1     Running            0               125m
kube-system       calico-node-lnqvj                                                 1/1     Running            0               124m
kube-system       coredns-5c64b647bf-2lnv8                                          1/1     Running            0               126m
kube-system       coredns-5c64b647bf-q298z                                          1/1     Running            0               126m
kube-system       csi-linode-controller-0                                           4/4     Running            2 (123m ago)    126m
kube-system       csi-linode-node-2bktw                                             2/2     Running            0               124m
kube-system       csi-linode-node-4gkw7                                             2/2     Running            0               125m
kube-system       csi-linode-node-lkb2x                                             2/2     Running            0               124m
kube-system       kube-proxy-6gbbn                                                  1/1     Running            0               124m
kube-system       kube-proxy-8xlb4                                                  1/1     Running            0               124m
kube-system       kube-proxy-x2rfp                                                  1/1     Running            0               125m
```

**Environment:**

- Istio Version: 1.16.1
- Knative Version: 1.18.3
- KServe Version: 0.10.0
- Kubeflow version: N/E
- Cloud Environment: Linode LKE v1.25.4
- Minikube/Kind version: N/E
- Kubernetes version: (use `kubectl version`): v1.26.1
- OS (e.g. from `/etc/os-release`):

**Comment by lmyslinski** [comment]
Update, I've tried the same setup on Linode but with LKE `1.24.8` - same error

**Comment by lmyslinski** [comment]
A couple more observations:

- I've been using an EKS cluster on 1.24.10 with all the mentions mentioned above and had it running successfully. I could not setup any working setup anymore regardless of k8s version (1.25 or 1.24) or knative version (1.8 and 1.9).

- I've fallen back to using the quickstart, which uses istio 1.15, knative 1.7 and cert-manager 1.3. It does work, but it doesn't match anything what's stated on the website. The current working setup involves all the versions from the quickstart running on 1.24, yet none of the versions used match the ones recommended. Can you please clarify that?

**Comment by lmyslinski** [comment]
Also I've traced the error back to knative controller:

```
{"severity":"ERROR","timestamp":"2023-02-17T12:23:06.314986042Z","logger":"controller","caller":"controller/controller.go:566","message":"Reconcile error","commit":"3928479","knative.dev/pod":"controller-5c7746b887-hcggz","knative.dev/controller":"knative.dev.serving.pkg.reconciler.labeler.Reconciler","knative.dev/kind":"serving.knative.dev.Route","knative.dev/traceid":"ac6460f8-086c-4b0c-9661-52db4df35b08","knative.dev/key":"kserve/sklearn-iris-predictor-default","duration":"46.047162ms","error":"failed to set finalizers: Operation cannot be fulfilled on routes.serving.knative.dev \"sklearn-iris-predictor-default\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20221123011842-b78020c16606/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20221123011842-b78020c16606/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20221123011842-b78020c16606/controller/controller.go:491"}
```

I've tried debugging that, however without further context it's pretty hard to investigate. I'm assuming the issue might be caused by CRD schema mismatch between what knative controller is expecting versus what's found on the cluster, hence the error? Definitely seems like a version-related conflict

**Comment by lloydhamilton** [comment]
Hey could you print the outputs of 

```
kubectl describe pods sklearn-iris-predictor-default-00001-deployment-78486fb5bfq86lj
kubectl describe isvc sklearn-iris
```

I find these useful for debugging.

**Comment by lmyslinski** [comment]
@lloydhamilton Sorry, but I've destroyed the cluster and just ran with the versions from `quick_install.sh`. They work well so far, it's just that they're not up to date with what's on the website/recommended. We can close this issue and I'll open a new one with more data if the issue occurs again.
