### ISSUE TITLE
Custom KServe model gives an error which is hard to figure out.

### ISSUE THREAD

**Issue by iwyoo** [kserve/kserve#2798]
/kind bug

**What steps did you take and what happened:**
I used Python SDK with version `kserve==0.8.0` and it works fine.
After I updated it to `kserve==0.10.1`, I got following error.

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/miniconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/lib/python3.9/site-packages/timing_asgi/middleware.py", line 68, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/root/miniconda3/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/root/miniconda3/lib/python3.9/site-packages/kserve/protocol/rest/v1_endpoints.py", line 69, in predict
    response, response_headers = await self.dataplane.infer(model_name=model_name, body=body, headers=headers)
  File "/root/miniconda3/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 276, in infer
    response = await model(body, headers=headers)
  File "/root/miniconda3/lib/python3.9/site-packages/kserve/model.py", line 118, in __call__
    else self.predict(payload, headers)
TypeError: predict() takes 2 positional arguments but 3 were given
```

**What did you expect to happen:**
It runs normally without errors.

**What's the InferenceService yaml:**
I used custom-model with `KServe.Model` and `kserve.ModelServer().start([model])` (for test and developing purpose).

**Anything else you would like to add:**
I added a print line to know what 's going on. (`print("DEBUG:", inspect.getfullargspec(self.predict))`)

And I got `DEBUG: FullArgSpec(args=['self', 'request'], varargs=None, varkw=None, defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={'return': typing.Dict, 'request': typing.Union[bytes, typing.Dict]})`
The function arguments are different with current version... (very weird)

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.10.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.5

**Comment by sivanantha321** [comment]
@iwyoo The method signature of `predict` method is changed in kserve 0.10. Now it has a additional parameter called `headers`.  Have you incorporate this change in your code ? Also you can refer the [custom model example](https://github.com/kserve/kserve/blob/release-0.10/python/custom_model/model.py) for more information.

**Comment by iwyoo** [comment]
> @iwyoo The method signature of `predict` method is changed in kserve 0.10. Now it has a additional parameter called `headers`. Have you incorporate this change in your code ? Also you can refer the [custom model example](https://github.com/kserve/kserve/blob/release-0.10/python/custom_model/model.py) for more information.

Thank you for answer! The way the code should be different from 0.8.0. I confirmed that it works well in 0.10.1. I'll close the issue!
