### ISSUE TITLE
[TorchServe Model] Connection refused

### ISSUE THREAD

**Issue by MikhailKravets** [kserve/kserve#2872]
/kind bug

**What steps did you take and what happened:**

I've created an InferenceService from PyTorch model with torchserve-kfs runtime version 0.7.0 (see .yaml file below). Then I've made a request to the model with

```python
    inference_request = {
        "name": "predict",
        "shape": [1, 64, 48],
        "datatype": "FP32",
        "data": im.tolist()
    }
    url = "http://127.0.0.1/v2/models/vit_cifar/infer"
    resp = requests.post(url, json=inference_request)
```

Inference Service responded with 500 error and `kserve-controller` logged a message:

```shell
[I 230504 07:27:59 TorchserveModel:76] PREDICTOR_HOST : 0.0.0.0:8085
[E 230504 07:27:59 web:1798] Uncaught exception POST /v2/models/vit_cifar/infer (127.0.0.6)
    HTTPServerRequest(protocol='http', host='127.0.0.1', method='POST', uri='/v2/models/vit_cifar/infer', version='HTTP/1.1', remote_ip='127.0.0.6')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/usr/local/lib/python3.8/dist-packages/kserve/handlers/predict.py", line 70, in post
        response = await model(body)
      File "/usr/local/lib/python3.8/dist-packages/kserve/model.py", line 86, in __call__
        response = (await self.predict(request)) if inspect.iscoroutinefunction(self.predict) \
      File "/home/model-server/kserve_wrapper/TorchserveModel.py", line 78, in predict
        response = await self._http_client.fetch(
    ConnectionRefusedError: [Errno 111] Connection refused
[E 230504 07:27:59 web:2271] 500 POST /v2/models/vit_cifar/infer (127.0.0.6) 55.08ms
```

**What did you expect to happen:**

TorchserveModel passes request to a handler that runs the model.

**What's the InferenceService yaml:**

```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: pytorch-vit
  namespace: default
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      storageUri: "s3://bucket/vit/model-store"
      runtimeVersion: 0.7.0
```

**Anything else you would like to add:**

If it helps here is the `config.properties` file

```
inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071
enable_metrics_api=true
metrics_format=prometheus
number_of_netty_threads=4
job_queue_size=10
enable_envvars_config=true
install_py_dep_per_model=true
model_store=/mnt/models/model-store
model_snapshot={"name": "startup.cfg", "modelCount": 1, "models": {"vit_cifar": {"1.0": {"defaultVersion": true, "marName": "vit_cifar.mar", "minWorkers": 1, "maxWorkers": 3, "batchSize": 1, "maxBatchDelay": 300, "responseTimeout": 420}}}}
```

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.10.0
- Kubeflow version:
- Cloud Environment:
- Minikube version: v1.30.1
- Kubernetes version: (use `kubectl version`): 1.17.2
- OS (e.g. from `/etc/os-release`):

**Comment by andyi2it** [comment]
@MikhailKravets 
Can you confirm the kubernetes version, is it 1.17.2 or is it just the kubectl version?

**Comment by MikhailKravets** [comment]
@andyi2it , sorry it looks like a typo in the issue. Here is version of

kubectl: v1.25.4
Kubernetes: v1.26.3

**Comment by sivanantha321** [comment]
@MikhailKravets Can you try with the kserve 0.11.1 and torchserve 0.8.2. Kserve moved from tornado web server to uvicorn. There are many things fixed after torchserve 0.7.

**Comment by spolti** [comment]
TorchServe will be removed as part of https://github.com/kserve/kserve/issues/4469
For pyTorch models, we still can use the triton server.
