### ISSUE TITLE
(S3) SA Annotations not making it to Pod

### ISSUE THREAD

**Issue by npapapietro** [kserve/kserve#2990]
/kind bug

**What did you expect to happen:**

Reading the documentation posted [here](https://kserve.github.io/website/0.10/modelserving/storage/s3/s3/), it shows that I can either annotate the `Secret`  or the `ServiceAccount` (in the case of using an existing secret).  If the endpoint annotations can _only_ be used on the secret (in the non IRSA mode), then this might be a documentation fix until this feature can be implemented.

**What's the InferenceService yaml:**

Deployed this bit

<details><summary>Deployed with</summary>

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: app
type: Opaque
stringData:
  AWS_SECRET_ACCESS_KEY: abcd1234
  AWS_ACCESS_KEY_ID: admin
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3aware
  namespace: app
  annotations:
    serving.kserve.io/s3-endpoint: "minio.minio.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-2"
    serving.kserve.io/s3-useanoncredential: "false"
secrets:
  - name: minio
---
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-irisv2"
  namespace: app
spec:
  predictor:
    serviceAccountName: s3aware
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: "s3://models"
```

</details>

I even tried to add a 2nd secret explicitly by updating the SA with a 2nd Secret:

<details><summary>Updated with</summary>

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-endpoint
  namespace: app
type: Opaque
stringData:
  AWS_ENDPOINT_URL: "minio.minio.svc.cluster.local:9000"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3aware
  namespace: app
  annotations:
    serving.kserve.io/s3-endpoint: "minio.minio.svc.cluster.local:9000"
    serving.kserve.io/s3-usehttps: "0"
    serving.kserve.io/s3-region: "us-east-2"
    serving.kserve.io/s3-useanoncredential: "false"
secrets:
  - name: minio
  - name: minio-endpoint
```

</details>

This results in the this pod

<details><summary>Pod yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    internal.serving.kserve.io/storage-initializer-sourceuri: s3://models
    prometheus.kserve.io/path: /metrics
    prometheus.kserve.io/port: "8080"
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/enable-metric-aggregation: "false"
    serving.kserve.io/enable-prometheus-scraping: "false"
  creationTimestamp: "2023-06-14T22:47:00Z"
  generateName: sklearn-irisv2-predictor-default-7f79ff7847-
  labels:
    app: isvc.sklearn-irisv2-predictor-default
    component: predictor
    modelClass: mlserver_sklearn.SKLearnModel
    pod-template-hash: 7f79ff7847
    serving.kserve.io/inferenceservice: sklearn-irisv2
  name: sklearn-irisv2-predictor-default-7f79ff7847-mnttm
  namespace: app
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: sklearn-irisv2-predictor-default-7f79ff7847
    uid: a850be14-2e30-45fc-b853-893b7e17f962
  resourceVersion: "15949"
  uid: 7454fd28-deba-4841-8ed4-95fea6f67a12
spec:
  containers:
  - env:
    - name: MLSERVER_MODEL_NAME
      value: sklearn-irisv2
    - name: MLSERVER_MODEL_URI
      value: /mnt/models
    - name: MLSERVER_MODEL_IMPLEMENTATION
      value: mlserver_sklearn.SKLearnModel
    - name: MLSERVER_HTTP_PORT
      value: "8080"
    - name: MLSERVER_GRPC_PORT
      value: "9000"
    - name: MODELS_DIR
      value: /mnt/models
    image: docker.io/seldonio/mlserver:1.0.0
    imagePullPolicy: IfNotPresent
    name: kserve-container
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: 8080
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 2Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-k5slg
      readOnly: true
    - mountPath: /mnt/models
      name: kserve-provision-location
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - s3://models
    - /mnt/models
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: AWS_ACCESS_KEY_ID
          name: minio
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: AWS_SECRET_ACCESS_KEY
          name: minio
    image: kserve/storage-initializer:v0.10.1
    imagePullPolicy: IfNotPresent
    name: storage-initializer
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /mnt/models
      name: kserve-provision-location
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-k5slg
      readOnly: true
  nodeName: dell-b8kvfb3
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: s3aware
  serviceAccountName: s3aware
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-k5slg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  - emptyDir: {}
    name: kserve-provision-location
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T22:47:00Z"
    message: 'containers with incomplete status: [storage-initializer]'
    reason: ContainersNotInitialized
    status: "False"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T22:47:00Z"
    message: 'containers with unready status: [kserve-container]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T22:47:00Z"
    message: 'containers with unready status: [kserve-container]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-06-14T22:47:00Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: docker.io/seldonio/mlserver:1.0.0
    imageID: ""
    lastState: {}
    name: kserve-container
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        reason: PodInitializing
  hostIP: 172.23.233.1
  initContainerStatuses:
  - containerID: containerd://44c6d4f7142341515e229a7bd0c45f5da702ab00b48524b1e7f44ae23f2168ba
    image: docker.io/kserve/storage-initializer:v0.10.1
    imageID: docker.io/kserve/storage-initializer@sha256:f6273fb52288ab29b126daf52337c56bc17a36b8dc8ff51e7039f0be49d126ab
    lastState:
      terminated:
        containerID: containerd://44c6d4f7142341515e229a7bd0c45f5da702ab00b48524b1e7f44ae23f2168ba
        exitCode: 1
        finishedAt: "2023-06-14T22:58:13Z"
        message: |
          2023-06-14 22:58:10.252 1 root INFO [<module>():13] Initializing, args: src_uri [s3://models] dest_path[ [/mnt/models]
          2023-06-14 22:58:10.252 1 root INFO [download():63] Copying contents of s3://models to local
          2023-06-14 22:58:10.284 1 botocore.credentials INFO [load():1124] Found credentials in environment variables.
          Traceback (most recent call last):
            File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
              kserve.Storage.download(src_uri, dest_path)
            File "/kserve/kserve/storage.py", line 83, in download
              Storage._download_s3(uri, out_dir)
            File "/kserve/kserve/storage.py", line 167, in _download_s3
              for obj in bucket.objects.filter(Prefix=bucket_path):
            File "/usr/local/lib/python3.9/site-packages/boto3/resources/collection.py", line 81, in __iter__
              for page in self.pages():
            File "/usr/local/lib/python3.9/site-packages/boto3/resources/collection.py", line 171, in pages
              for page in pages:
            File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
              response = self._make_request(current_kwargs)
            File "/usr/local/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
              return self._method(**current_kwargs)
            File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 530, in _api_call
              return self._make_api_call(operation_name, kwargs)
            File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 960, in _make_api_call
              raise error_class(parsed_response, operation_name)
          botocore.exceptions.ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.
        reason: Error
        startedAt: "2023-06-14T22:58:08Z"
    name: storage-initializer
    ready: false
    restartCount: 7
    state:
      waiting:
        message: back-off 5m0s restarting failed container=storage-initializer pod=sklearn-irisv2-predictor-default-7f79ff7847-mnttm_app(7454fd28-deba-4841-8ed4-95fea6f67a12)
        reason: CrashLoopBackOff
  phase: Pending
  podIP: 10.42.0.30
  podIPs:
  - ip: 10.42.0.30
  qosClass: Burstable
  startTime: "2023-06-14T22:47:00Z"
```

</details>

**Environment:**

Deployed it via the helm charts with `kserve-resources` chart's values as 
```yaml
kserve:
  controller:
    deploymentMode: RawDeployment
```

- Istio Version: 1.18
- Knative Version: NA
- KServe Version: 0.10.1
- Kubeflow version: N/A
- Cloud Environment: N/A
- Minikube/Kind version: k3s ` v1.26.5+k3s1`
- Kubernetes version: (use `kubectl version`): 1.26
- OS (e.g. from `/etc/os-release`): WSL2 + Win11

**Comment by yuzisun** [comment]
Update the s3 storage documentation to clarify the annotation usage for the two methods with IAM role and static s3 credentials.
