### ISSUE TITLE
Model with name  mymodel-231313sd:predict  does not exist.

### ISSUE THREAD

**Issue by Rstar1998** [kserve/kserve#3007]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

So I successfully hosted a model on my kserve. 
When I did a `kubectl get inferenceservice` , I got 

NAME         :    mymodel-231313sd        
URL            :    http://mymodel-231313sd-default.mydomain.com                                                                    
READY       :    True        

I made `http://mymodel-231313sd-default.mydomain.com` public  

Now when I hit 
(public hit)
```
curl --location http://mymodel-231313sd-default.mydomain.com/v1/models/mymodel-231313sd:predict \
--header 'Content-Type: application/json' \
--data '{
  
}'
```
I get this error 
```
{
    "error": "Model with name mymodel-231313sd:predict does not exist."
}

```
But when I exec into the pod (using => kubectl exec -it podname sh ) and hit 
(inside pod)
```
curl --location 'http://localhost:8080/v1/models/mymodel-231313sd:predict' \
--header 'Content-Type: application/json' \
--data '{

}'
```

It works fine and gives me the necessary output.

Also all other apis like  `/` , ` /v1/models` , `/v1/models/mymodel-231313sd` are working properly on both things. Only this `/v1/models/mymodel-231313sd:predict` is not working properly.

Can someone help me out in this ? I think that colon in  :predict is causing some problem. Model name should not have :predict append which causes wrong model name to be passed. 

I am using 
kserve==0.11.0rc0
in mu custom model python file

**Comment by Rstar1998** [comment]
@yuzisun

**Comment by yuzisun** [comment]
@Rstar1998 Can you attach the python server logs?

**Comment by Rstar1998** [comment]
@yuzisun. Here are the Python logs for the same api hit.
```
2023-06-26 03:28:37.003 1 kserve ERROR [model_not_found_handler():100] Exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/rest/v1_endpoints.py", line 48, in model_ready
    model_ready = self.dataplane.model_ready(model_name)
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 204, in model_ready
    raise ModelNotFound(model_name)
kserve.errors.ModelNotFound: Model with name mymodel-231313sd:predict does not exist.
2023-06-26 03:28:37.004 uvicorn.access INFO:     125.22.87.250:0 1 - "GET /v1/models/mymodel-231313sd%3Apredict HTTP/1.1" 404 Not Found

```

**Comment by Rstar1998** [comment]
When I use this curl it gives a different error. 
```
curl --location --request POST 'http://mymodel-231313sd-default.mydomain.com/v1/models/mymodel-231313sd:predict' \
--header 'Content-Type: application/json' \
--data-raw '{
    "some_data": "some data"
}'
```

Python logs : 

```
2023-06-26 06:30:15.812 1 kserve ERROR [invalid_input_handler():84] Exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 217, in decode
    body = orjson.loads(body)
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/app/.heroku/python/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/app/.heroku/python/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/rest/v1_endpoints.py", line 69, in predict
    response, response_headers = await self.dataplane.infer(model_name=model_name, body=body, headers=headers)
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 271, in infer
    body = self.decode(body, headers)
  File "/app/.heroku/python/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 219, in decode
    raise InvalidInput(f"Unrecognized request format: {e}")
kserve.errors.InvalidInput: Unrecognized request format: Input is a zero-length, empty document: line 1 column 1 (char 0)
2023-06-26 06:30:15.812 uvicorn.access INFO:     125.22.87.250:0 1 - "POST /v1/models/mymodel-231313sd%3Apredict HTTP/1.1" 400 Bad Request


```
Curl version : 

```
curl 7.82.0 (x86_64-apple-darwin13.4.0) libcurl/7.82.0 OpenSSL/1.1.1n zlib/1.2.12 libssh2/1.10.0 nghttp2/1.46.0
Release-Date: 2022-03-05
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz NTLM NTLM_WB SPNEGO SSL TLS-SRP UnixSockets
```

**Comment by Rstar1998** [comment]
Resolved. 

Since I was using http it was redirecting causing issues
