### ISSUE TITLE
Load model failed: falcon, error: Worker died.

### ISSUE THREAD

**Issue by amnescher** [kserve/kserve#3021]
Try to deploy a InferenceService for falcon large language model using Torchserve.
I successfully generate the model.mar using a custom handler. Torchserve works fine locally on baremetal node, and performs the inference. However, model can't be loaded when deploying inferenceservice. 

my handler
```

from transformers import AutoTokenizer, AutoModelForCausalLM
import transformers
import torch
from ts.torch_handler.base_handler import BaseHandler
import logging
import zipfile
logger = logging.getLogger(__name__)
class FalconHandler(BaseHandler):
    def initialize(self, context):
        self.manifest = context.manifest
        properties = context.system_properties
        model_dir = properties.get("model_dir")

        with zipfile.ZipFile(model_dir + "/model.zip", "r") as zip_ref:
            zip_ref.extractall(model_dir + "/model")

        self.model_name = model_dir + "/model"
        self.tokenizer = AutoTokenizer.from_pretrained(self.model_name)
        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_name,
            local_files_only=True,
            trust_remote_code=True,
            load_in_4bit=False,
            torch_dtype=torch.bfloat16,
            device_map={"": 0},
        )
        self.pipeline = transformers.pipeline(
            "text-generation",
            model=self.model,
            tokenizer=self.tokenizer,
            torch_dtype=torch.bfloat16,
            trust_remote_code=True,
            device_map={"": 0},
        )
    def preprocess(self, data):
        return data
    def inference(self, requests):
        for idx, data in enumerate(requests):
            input_text = data.get("data")
            if input_text is None:
                input_text = data.get("body")
            if isinstance(input_text, (bytes, bytearray)):
                input_text = input_text.decode("utf-8")
        sequences = self.pipeline(
            input_text,
            max_length=200,
            do_sample=True,
            top_k=10,
            num_return_sequences=1,
            pad_token_id=self.tokenizer.eos_token_id,
        )
        results = []
        for seq in sequences:
            results.append(seq["generated_text"])
        return results

    def postprocess(self, data):
        return data

```
my config.properties 

```
inference_address=http://0.0.0.0:8085
management_address=http://0.0.0.0:8085
metrics_address=http://0.0.0.0:8082
grpc_inference_port=7070
grpc_management_port=7071
enable_metrics_api=true
metrics_format=prometheus
number_of_netty_threads=4
job_queue_size=10
handler: "handler.py",
enable_envvars_config=true
install_py_dep_per_model=true
model_store=//mnt/models/model-store
model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"falcon":{"1.0":{"defaultVersion":true,"marName":"falcon.mar","minWorkers":1,"maxWorkers":1,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
```

Logs of inference service. 

```
2023-07-05T13:36:17,260 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-07-05T13:36:17,574 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.7.0
TS Home: /usr/local/lib/python3.8/dist-packages
Current directory: /home/model-server
Temp directory: /home/model-server/tmp
Metrics config path: /usr/local/lib/python3.8/dist-packages/ts/configs/metrics.yaml
Number of GPUs: 1
Number of CPUs: 1
Max heap size: 494 M
Python executable: /usr/bin/python3.8
Config file: /mnt/models/config/config.properties
Inference address: http://0.0.0.0:8085
Management address: http://0.0.0.0:8085
Metrics address: http://0.0.0.0:8082
Model Store: /mnt/pvc/model-store
Initial Models: N/A
Log dir: /home/model-server/logs
Metrics dir: /home/model-server/logs
Netty threads: 4
Netty client threads: 0
Default workers per model: 1
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit Maximum Image Pixels: true
Prefer direct buffer: false
Allowed Urls: [file://.*|http(s)?://.*]
Custom python dependency for model allowed: true
Metrics report format: prometheus
Enable metrics API: true
Workflow Store: /mnt/pvc/model-store
Model config: N/A
2023-07-05T13:36:17,647 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager -  Loading snapshot serializer plugin...
2023-07-05T13:36:17,745 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Started restoring models from snapshot {"name":"startup.cfg","modelCount":1,"models":{"falcon":{"1.0":{"defaultVersion":true,"marName":"falcon.mar","minWorkers":1,"maxWorkers":1,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":120}}}}
2023-07-05T13:36:17,756 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Validating snapshot startup.cfg
2023-07-05T13:36:17,759 [INFO ] main org.pytorch.serve.snapshot.SnapshotManager - Snapshot startup.cfg validated successfully
[I 230705 13:36:18 __main__:70] Wrapper : Model names ['falcon'], inference address http//0.0.0.0:8085, management address http://0.0.0.0:8085, model store //mnt/models/model-store
[I 230705 13:36:18 TorchserveModel:52] kfmodel Predict URL set to 0.0.0.0:8085
[I 230705 13:36:18 TorchserveModel:54] kfmodel Explain URL set to 0.0.0.0:8085
[I 230705 13:36:18 storage:63] Copying contents of //mnt/models/model-store to local
[I 230705 13:36:18 TSModelRepository:27] TSModelRepo is initialized
[I 230705 13:36:18 model_server:150] Registering model: falcon
[I 230705 13:36:18 model_server:123] Listening on port 8080
[I 230705 13:36:18 model_server:125] Will fork 1 workers
[I 230705 13:36:18 model_server:128] Setting max asyncio worker threads as 28
2023-07-05T13:37:36,378 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Adding new version 1.0 for model falcon
2023-07-05T13:37:36,379 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model falcon
2023-07-05T13:39:46,617 [DEBUG] main org.pytorch.serve.wlm.ModelVersionedRefs - Setting default version to 1.0 for model falcon
2023-07-05T13:39:46,618 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model falcon loaded.
2023-07-05T13:39:46,619 [DEBUG] main org.pytorch.serve.wlm.ModelManager - updateModel: falcon, count: 1
2023-07-05T13:39:46,630 [DEBUG] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/usr/bin/python3.8, /usr/local/lib/python3.8/dist-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000, --metrics-config, /usr/local/lib/python3.8/dist-packages/ts/configs/metrics.yaml]
2023-07-05T13:39:46,643 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2023-07-05T13:39:46,861 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://0.0.0.0:8085
2023-07-05T13:39:46,862 [INFO ] main org.pytorch.serve.ModelServer - Initialize Metrics server with: EpollServerSocketChannel.
2023-07-05T13:39:46,863 [INFO ] main org.pytorch.serve.ModelServer - Metrics API bind to: http://0.0.0.0:8082
Model server started.
2023-07-05T13:39:47,376 [WARN ] pool-3-thread-1 org.pytorch.serve.metrics.MetricCollector - worker pid is not available yet.
2023-07-05T13:39:48,365 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,366 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:303.69482040405273|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,366 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:180.68961334228516|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,367 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:37.3|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,367 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUtilization.Percent:0.0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,367 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUsed.Megabytes:0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,368 [INFO ] pool-3-thread-1 TS_METRICS - GPUUtilization.Percent:0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,368 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:188752.41015625|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,368 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:2732.6640625|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:48,369 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:2.3|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564388
2023-07-05T13:39:50,824 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2023-07-05T13:39:50,827 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Successfully loaded /usr/local/lib/python3.8/dist-packages/ts/configs/metrics.yaml.
2023-07-05T13:39:50,827 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - [PID]225
2023-07-05T13:39:50,827 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Torch worker started.
2023-07-05T13:39:50,828 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Python runtime: 3.8.10
2023-07-05T13:39:50,828 [DEBUG] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-falcon_1.0 State change null -> WORKER_STARTED
2023-07-05T13:39:50,832 [INFO ] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2023-07-05T13:39:50,849 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2023-07-05T13:39:50,852 [INFO ] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req. to backend at: 1688564390852
2023-07-05T13:39:50,954 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - model_name: falcon, batchSize: 1
2023-07-05T13:40:48,864 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:33.3|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,867 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:297.0941963195801|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,867 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:187.2902374267578|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,867 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:38.7|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,868 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUtilization.Percent:0.0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,868 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUsed.Megabytes:0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,868 [INFO ] pool-3-thread-1 TS_METRICS - GPUUtilization.Percent:0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,868 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:188581.30859375|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,869 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:2904.1953125|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:40:48,869 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:2.4|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564448
2023-07-05T13:41:46,323 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Created a temporary directory at /home/model-server/tmp/tmppj2agp6a
2023-07-05T13:41:46,325 [INFO ] W-9000-falcon_1.0-stdout MODEL_LOG - Writing /home/model-server/tmp/tmppj2agp6a/_remote_module_non_scriptable.py
2023-07-05T13:41:46,786 [WARN ] W-9000-falcon_1.0-stderr MODEL_LOG - 
2023-07-05T13:41:48,358 [INFO ] pool-3-thread-1 TS_METRICS - CPUUtilization.Percent:0.0|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,360 [INFO ] pool-3-thread-1 TS_METRICS - DiskAvailable.Gigabytes:290.2432441711426|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,360 [INFO ] pool-3-thread-1 TS_METRICS - DiskUsage.Gigabytes:194.1411895751953|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,360 [INFO ] pool-3-thread-1 TS_METRICS - DiskUtilization.Percent:40.1|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,361 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUtilization.Percent:0.003662109375|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,361 [INFO ] pool-3-thread-1 TS_METRICS - GPUMemoryUsed.Megabytes:3|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,361 [INFO ] pool-3-thread-1 TS_METRICS - GPUUtilization.Percent:0|#Level:Host,device_id:0|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,362 [INFO ] pool-3-thread-1 TS_METRICS - MemoryAvailable.Megabytes:188135.93359375|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,362 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUsed.Megabytes:3348.7421875|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:48,362 [INFO ] pool-3-thread-1 TS_METRICS - MemoryUtilization.Percent:2.6|#Level:Host|#hostname:falcon-predictor-default-00001-deployment-5999fcb8bb-zrxtb,timestamp:1688564508
2023-07-05T13:41:50,954 [INFO ] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - Backend response time: 120000
2023-07-05T13:41:50,956 [ERROR] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - Number or consecutive unsuccessful inference 1
2023-07-05T13:41:50,957 [ERROR] W-9000-falcon_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker error
org.pytorch.serve.wlm.WorkerInitializationException: Backend worker did not respond in given time
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:201) [model-server.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2023-07-05T13:41:50,974 [WARN ] W-9000-falcon_1.0 org.pytorch.serve.wlm.BatchAggregator - Load model failed: falcon, error: Worker died.
```

**Comment by gavrissh** [comment]
@amnescher loading the falcon model takes a bit of time. This is not a kserve issue, rather timeout on the torchserve side.

You would need to set a higher responseTimeout value under model_snapshot and it should resolve this one,

`model_snapshot={"name":"startup.cfg","modelCount":1,"models":{"falcon":{"1.0":{"defaultVersion":true,"marName":"falcon.mar","minWorkers":1,"maxWorkers":1,"batchSize":1,"maxBatchDelay":5000,"responseTimeout":1200}}}}`
