### ISSUE TITLE
Kserve Sklearn arm64 image issue

### ISSUE THREAD

**Issue by Manindhar** [kserve/kserve#3082]
/kind bug

What steps did you take and what happened:
I am facing issue in running inference service on my minikube for Kserve.

When trying to create my first inference service - https://kserve.github.io/website/0.10/get_started/first_isvc/#run-your-first-inferenceservice

I am getting below error

**kubectl logs pod/sklearn-iris-new-predictor-default-00002-deployment-6ccd584j9mh -n kserve**
Defaulted container "kserve-container" out of: kserve-container, queue-proxy
INFO:root:Copying contents of /mnt/models to local
ERROR:root:fail to locate model file for model sklearn-iris-new under dir /mnt/models,trying loading from model repository.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 42, in <module>
    kserve.ModelServer(registered_models=SKLearnModelRepository(args.model_dir)).start(
  File "/sklearnserver/sklearnserver/sklearn_model_repository.py", line 24, in __init__
    self.load_models()
  File "/kserve/kserve/model_repository.py", line 37, in load_models
    for name in os.listdir(self.models_dir):
**FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models'**

Any help would be appreciated.

What did you expect to happen: The inference service takes the pre loaded image from minikube and starts the serving

What's the InferenceService yaml:
[To help us debug please run kubectl get isvc $name -n $namespace -oyaml and paste the output]
<img width="559" alt="image" src="https://github.com/kserve/kserve/assets/32701843/8fe6c20a-efd9-4240-bea4-c216865da059">

Anything else you would like to add:
[Miscellaneous information that will assist in solving the issue.]
<img width="911" alt="image" src="https://github.com/kserve/kserve/assets/32701843/80dda879-0ada-48d3-890c-e4498ea8ac30">

Environment:

Istio Version: 1.17.2
Knative Version:
KServe Version: 1.10.0
Kubeflow version:
Cloud Environment: local
Minikube/Kind version: v1.30.1 on Darwin 13.4 (arm64)
Kubernetes version: (use kubectl version): v1.27.2
OS (e.g. from /etc/os-release): Darwin 13.4 (arm64)

**Comment by amacharya** [comment]
Hello,

kserve v0.11.0
kind - kubernetes v1.25

I am still facing an issue.  - FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models'

any solution/workaround?

**Comment by nirmesh** [comment]
I am also facing same issue. any resolution?

**Comment by sivanantha321** [comment]
@nirmesh could you verify if the storage initilaizer init container is injected and successfully downloaded the model from the logs ?

**Comment by nirmesh** [comment]
@sivanantha321 Where exactly i can check that? i have been following this document "https://kserve.github.io/website/0.8/modelserving/storage/pvc/pvc/#deploy-inferenceservice-with-models-on-pvc"

I have tried below
![image](https://github.com/kserve/kserve/assets/278157/2fafce32-3adc-43d0-94c4-04697d7187b7)

When i describe the pod i see below
![Uploading image.png…]()

**Comment by israel-hdez** [comment]
@nirmesh May you re-upload the image of the pod?

**Comment by amacharya** [comment]
Follow this - https://kserve.github.io/website/0.11/get_started/

I was able to unblock myself, and it worked for me

**Comment by sivanantha321** [comment]
@Manindhar @nirmesh If you are running isvc in kserve namespace, the storage initializer won't be injected due to the webhook configurations. For now, try to run it in a namespace other than kserve.

**Comment by nirmesh** [comment]
@sivanantha321  i am running that in default namespace not in "kserve" still i am facing this issue
![image](https://github.com/kserve/kserve/assets/278157/2390f371-ce23-4e69-bb34-9bed0a2cad1f)

**Comment by sivanantha321** [comment]
@nirmesh It looks like you are getting a not a directory error. Can you check your folder structure and verify /mnt/models is indeed a directory ?

**Comment by nirmesh** [comment]
@sivanantha321 directory is present. can we connect on call ? i will share screen "nirmesh44@gmail.com" is my handle.

**Comment by amacharya** [comment]
> https://kserve.github.io/website/0.11/get_started/
> 
> I was able to unblock myself, and it worked for me

@nirmesh 
I hit on this issue previously on my local kind cluster.
What document are you following?

Follow this -  https://kserve.github.io/website/0.11/get_started/

I was able to unblock myself, and it worked for me

**Comment by nirmesh** [comment]
@amacharya it works for me as well when serving from google storage URI. My problem is i am getting that issue when i do that with pvc "https://kserve.github.io/website/0.8/modelserving/storage/pvc/pvc/#copy-model-to-pv" i am using here this model "https://github.com/kserve/modelmesh-minio-examples/raw/main/sklearn/mnist-svm.joblib" to test PVC concept

**Comment by kjoth** [comment]
I'm as well facing the same error, via googlestorage, s3 .

![image](https://github.com/kserve/kserve/assets/24207765/fb91e7ae-1aad-408f-bd75-0cc5df26b8b3)

**Comment by sivanantha321** [comment]
@kjoth Are you running the inference service in `kserve` namespace ?

**Comment by sivanantha321** [comment]
> @sivanantha321 directory is present. can we connect on call ? i will share screen "[nirmesh44@gmail.com](mailto:nirmesh44@gmail.com)" is my handle.

I am sorry, I have been busy from last week. I will look into it in few days.
