### ISSUE TITLE
validation error for InferenceResponse on V2 mnist for v0.11.0

### ISSUE THREAD

**Issue by lc2a** [kserve/kserve#3094]
Hi :)

**Environment:**
- Istio Version:  1.17.2
- Knative Version: knative-v1.11.0
- KServe Version: v0.11.0
- Kubernetes version: (use `kubectl version`): v1.25.6

I'm getting error for V2 MNist
**{"error":"ValidationError : 1 validation error for InferenceResponse\nid\n  none is not an allowed value (type=type_error.none.not_allowed)"}**

https://github.com/kserve/kserve/tree/master/docs/samples/v1beta1/torchserve/v2

```
admin@cli:~/kserve$ curl -v -H "Content-Type: application/json" -d @./mnist_v2_tensor.json http://mnist-v2-sa.models.mlde-kserve.abc.lan/v2/models/mnist/infer
*   Trying 10.90.1.50:80...
* Connected to mnist-v2-sa.models.mlde-kserve.abc.lan (10.90.1.50) port 80 (#0)
> POST /v2/models/mnist/infer HTTP/1.1
> Host: mnist-v2-sa.models.mlde-kserve.abc.lan
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 6801
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< content-length: 141
< content-type: application/json
< date: Mon, 21 Aug 2023 12:06:23 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 190
<
* Connection #0 to host mnist-v2-sa.models.mlde-kserve.abc.lan left intact
{"error":"ValidationError : 1 validation error for InferenceResponse\nid\n  none is not an allowed value (type=type_error.none.not_allowed)"}
```

```
2023-08-21 11:45:19.628 10 uvicorn.error ERROR [run_asgi():376] Exception in ASGI application
Traceback (most recent call last):
  File "/home/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/venv/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/venv/lib/python3.9/site-packages/timing_asgi/middleware.py", line 68, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/home/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/venv/lib/python3.9/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/home/venv/lib/python3.9/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/venv/lib/python3.9/site-packages/kserve/protocol/rest/v2_endpoints.py", line 135, in infer
    res = InferenceResponse.parse_obj(response)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for InferenceResponse
id
  none is not an allowed value (type=type_error.none.not_allowed)
```
  
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: mnist-v2-sa
  namespace: models
spec:
  predictor:
    serviceAccountName: sa
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      storageUri: s3://kmodels/mnist
```

**Comment by andyi2it** [comment]
@lc2a This is a known bug and we are awaiting a patch release of torchserve that would fix this.
Mostly in a week or two.
