### ISSUE TITLE
Internal error occurred: failed calling webhook "inferenceservice.kserve-webhook-server.defaulter"

### ISSUE THREAD

**Issue by mayankagarwal19911** [kserve/kserve#3102]
/kind bug

**What steps did you take and what happened:**
While running a simple kfserving on jupyter notebook for inference for Tensorflow model from https://github.com/kubeflow/pipelines/tree/master/components/kserve, run is getting failed with error 

`HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Internal error occurred: failed calling webhook \"inferenceservice.kserve-webhook-server.defaulter\": failed to call webhook: Post \" https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s \": no endpoints available for service \"kserve-webhook-server-service\"","reason":"InternalError","details":{"causes":[{"message":"failed calling webhook \"inferenceservice.kserve-webhook-server.defaulter\": failed to call webhook: Post \"https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s\": no endpoints available for service \"kserve-webhook-server-service\""}]},"code":500} https://kserve-webhook-server-service.kserve.svc:443/mutate-serving-kserve-io-v1beta1-inferenceservice?timeout=10s \": no endpoints available for service \"kserve-webhook-server-service\""}]},"code":500}
`

```
Upon checking  kserve-controller-manager logs, I found  below error but not clear what is it

Defaulted container "manager" out of: manager, kube-rbac-proxy
{"level":"info","ts":1693319897.5291374,"logger":"entrypoint","msg":"Setting up client for manager"}
{"level":"info","ts":1693319897.6200027,"logger":"entrypoint","msg":"Setting up manager"}
I0829 14:38:18.777328       1 request.go:645] Throttling request took 1.045446419s, request: GET:https://10.92.0.1:443/apis/accesscontextmanager.cnrm.cloud.google.com/v1beta1?timeout=32s
{"level":"info","ts":1693319902.0840657,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1693319902.084597,"logger":"entrypoint","msg":"Registering Components."}
{"level":"info","ts":1693319902.084629,"logger":"entrypoint","msg":"Setting up KServe v1alpha1 scheme"}
{"level":"info","ts":1693319902.0848315,"logger":"entrypoint","msg":"Setting up KServe v1beta1 scheme"}
{"level":"info","ts":1693319906.5020585,"logger":"entrypoint","msg":"Setting up core scheme"}
{"level":"info","ts":1693319906.5022612,"logger":"setup","msg":"Setting up v1beta1 controller"}
{"level":"info","ts":1693319906.5206127,"logger":"setup","msg":"Setting up v1beta1 TrainedModel controller"}
{"level":"info","ts":1693319906.5208576,"logger":"entrypoint","msg":"setting up webhook server"}
{"level":"info","ts":1693319906.5208886,"logger":"entrypoint","msg":"registering webhooks to the webhook server"}
{"level":"info","ts":1693319906.5210412,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-pods"}
{"level":"info","ts":1693319906.521174,"logger":"controller-runtime.builder","msg":"skip registering a mutating webhook, admission.Defaulter interface is not implemented","GVK":"serving.kserve.io/v1alpha1, Kind=TrainedModel"}
{"level":"info","ts":1693319906.521231,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"serving.kserve.io/v1alpha1, Kind=TrainedModel","path":"/validate-serving-kserve-io-v1alpha1-trainedmodel"}
{"level":"info","ts":1693319906.5213535,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-serving-kserve-io-v1alpha1-trainedmodel"}
{"level":"info","ts":1693319906.5215633,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"serving.kserve.io/v1beta1, Kind=InferenceService","path":"/mutate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1693319906.6196523,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/mutate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1693319906.6198652,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"serving.kserve.io/v1beta1, Kind=InferenceService","path":"/validate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1693319906.6199555,"logger":"controller-runtime.webhook","msg":"registering webhook","path":"/validate-serving-kserve-io-v1beta1-inferenceservice"}
{"level":"info","ts":1693319906.6201258,"logger":"entrypoint","msg":"Starting the Cmd."}
{"level":"info","ts":1693319906.6205666,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1693319906.6207047,"logger":"controller-runtime.manager.controller.inferenceservice","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","source":"kind source: /, Kind="}
{"level":"info","ts":1693319906.6209185,"logger":"controller-runtime.manager.controller.trainedmodel","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel","source":"kind source: /, Kind="}
{"level":"info","ts":1693319906.6208549,"logger":"controller-runtime.webhook.webhooks","msg":"starting webhook server"}
{"level":"info","ts":1693319906.621854,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1693319906.6221514,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":1693319906.6224241,"logger":"controller-runtime.webhook","msg":"serving webhook server","host":"","port":9443}
{"level":"info","ts":1693319906.7237031,"logger":"controller-runtime.manager.controller.trainedmodel","msg":"Starting Controller","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel"}
{"level":"info","ts":1693319906.9232864,"logger":"controller-runtime.manager.controller.inferenceservice","msg":"Starting EventSource","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","source":"kind source: /, Kind="}
{"level":"info","ts":1693319906.923972,"logger":"controller-runtime.manager.controller.trainedmodel","msg":"Starting workers","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel","worker count":1}
{"level":"info","ts":1693319907.0239754,"logger":"controller-runtime.manager.controller.inferenceservice","msg":"Starting Controller","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService"}
{"level":"info","ts":1693319907.0240514,"logger":"controller-runtime.manager.controller.inferenceservice","msg":"Starting workers","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","worker count":1}
{"level":"info","ts":1693319907.2252717,"logger":"v1beta1Controllers.InferenceService","msg":"Reconciling inference service","apiVersion":"serving.kserve.io/v1beta1","isvc":"tf-sample"}
E0829 14:38:27.227375       1 runtime.go:78] Observed a panic: runtime.boundsError{x:0, y:0, signed:true, code:0x0} (runtime error: index out of range [0] with length 0)
goroutine 842 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1af86e0, 0xc000022c20)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1af86e0, 0xc000022c20)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kserve/kserve/pkg/apis/serving/v1beta1.(*PredictorSpec).GetImplementation(...)
	/go/src/github.com/kserve/kserve/pkg/apis/serving/v1beta1/predictor.go:104
github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile(0xc000d54080, 0xc000b4ac00, 0x13, 0x2008260)
	/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:57 +0x1254
github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile(0xc000c11140, 0x1ffc460, 0xc000b6c630, 0xc00071a180, 0x8, 0xc00071a160, 0x9, 0xc000b6c630, 0x40941b, 0xc000360000, ...)
	/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:162 +0x622
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000db2780, 0x1ffc3a0, 0xc000c11d40, 0x1a44ba0, 0xc0000e0120)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000db2780, 0x1ffc3a0, 0xc000c11d40, 0xc000b6a600)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1ffc3a0, 0xc000c11d40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00034ff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008ebf50, 0x1fb67a0, 0xc000b6c570, 0xc000c11d01, 0xc000622cc0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00034ff50, 0x3b9aca00, 0x0, 0x1, 0xc000622cc0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1ffc3a0, 0xc000c11d40, 0xc000dffce0, 0x3b9aca00, 0x0, 0x1cdf801)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1ffc3a0, 0xc000c11d40, 0xc000dffce0, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4f6
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 842 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1af86e0, 0xc000022c20)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/kserve/kserve/pkg/apis/serving/v1beta1.(*PredictorSpec).GetImplementation(...)
	/go/src/github.com/kserve/kserve/pkg/apis/serving/v1beta1/predictor.go:104
github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components.(*Predictor).Reconcile(0xc000d54080, 0xc000b4ac00, 0x13, 0x2008260)
	/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/components/predictor.go:57 +0x1254
github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice.(*InferenceServiceReconciler).Reconcile(0xc000c11140, 0x1ffc460, 0xc000b6c630, 0xc00071a180, 0x8, 0xc00071a160, 0x9, 0xc000b6c630, 0x40941b, 0xc000360000, ...)
	/go/src/github.com/kserve/kserve/pkg/controller/v1beta1/inferenceservice/controller.go:162 +0x622
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000db2780, 0x1ffc3a0, 0xc000c11d40, 0x1a44ba0, 0xc0000e0120)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:263 +0x2f1
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000db2780, 0x1ffc3a0, 0xc000c11d40, 0xc000b6a600)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:235 +0x202
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.1(0x1ffc3a0, 0xc000c11d40)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:198 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc00034ff50)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0008ebf50, 0x1fb67a0, 0xc000b6c570, 0xc000c11d01, 0xc000622cc0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xa3
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00034ff50, 0x3b9aca00, 0x0, 0x1, 0xc000622cc0)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x1ffc3a0, 0xc000c11d40, 0xc000dffce0, 0x3b9aca00, 0x0, 0x1cdf801)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x1ffc3a0, 0xc000c11d40, 0xc000dffce0, 0x3b9aca00)
	/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.7.0/pkg/internal/controller/controller.go:195 +0x4f6
```

**What did you expect to happen:**
Pipeline should run successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- kserve version: v0.7.0
- kubeflow version: 2.xx
- Cluster: GKE

---

Impacted by this bug? Give it a 👍 We prioritize the issues with the most 👍

**Comment by yuzisun** [comment]
@mayankagarwal19911 It seems like the controller was crashing on an invalid inference service yaml without predictor defined, but 0.7 is too old and we'd recommend upgrading to newer version.
