### ISSUE TITLE
 KServe PODs is not restored after rebooting

### ISSUE THREAD

**Issue by yurkoff-mv** [kserve/kserve#3256]
/kind bug

**What steps did you take and what happened:**
After rebooting the POD node, KServe is not restored. This seems to be due to the fact that the Init container does not restart after a reboot.

**What did you expect to happen:**
Automatic re-creation of POD so that after a reboot you don’t have to turn everything over manually

**Environment:**
- Istio Version: 1.11.0
- Knative Version: v0.22.1
- KServe Version: v0.7.0
- Kubeflow version: 1.5
- Kubernetes version: (use kubectl version): v1.20
- OS (e.g. from /etc/os-release): Ubuntu 20.04

**Comment by sivanantha321** [comment]
@yurkoff-mv  Kserve 0.7.0 is no longer supported. Can you try with latest kserve version ?

**Comment by yurkoff-mv** [comment]
There is a similar problem in **KServe version 0.10**.
Here is the log from the container **storage-initializer**:
```
Init Containers:
  storage-initializer:
    Container ID:  containerd://a712bb9b5e4ca2009f037bcbec3b271d6505e4c4f783f338277508a746c60562
    Image:         kserve/storage-initializer:v0.7.0
    Image ID:      docker.io/kserve/storage-initializer@sha256:f92bde78bccdb6daf41d937f17f4e4eefda01bfc815c54d67d34a33fb617943e
    Port:          <none>
    Host Port:     <none>
    Args:
      /mnt/pvc/nllb-200-1dot3b
      /mnt/models
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   /usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 231120 14:21:56 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/my-model] dest_path[ [/mnt/models]
[I 231120 14:21:56 storage:52] Copying contents of /mnt/pvc/my-model to local
[I 231120 14:21:56 storage:263] Linking: /mnt/pvc/my-model/config to /mnt/models/config
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kserve.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 73, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kserve/storage.py", line 264, in _download_local
    os.symlink(src, dest_path)
FileExistsError: [Errno 17] File exists: '/mnt/pvc/my-model/config' -> '/mnt/models/config'
```

`microk8s kubectl get pods -n my-namespace`
```
NAME                                                              READY   STATUS                  RESTARTS   AGE
ml-pipeline-ui-artifact-8dcf69986-5jf5l                           2/2     Running                 4          12d
my-notebook-0                                                     2/2     Running                 2          3d7h
ml-pipeline-visualizationserver-7c8dfd5cb-95g26                   2/2     Running                 4          12d
my-model-predictor-default-00001-deployment-9857c666xttz          0/3     Init:CrashLoopBackOff   7          24m
```


**Environment:**

- Istio Version: 1.17.3
- Knative Version: v1.10.2
- KServe Version: v0.10
- Kubeflow version: 1.8
- Kubernetes version: (use kubectl version): v1.26
- OS (e.g. from /etc/os-release): Ubuntu 20.04

**Comment by sivanantha321** [comment]
@yurkoff-mv It seems it is related to the issue https://github.com/kserve/kserve/issues/2354. It is fixed in kserve 0.11.0 by PR #2794. Can you try with kserve 0.11.2 and report if the issue still persists ?

**Comment by yurkoff-mv** [comment]
Thank you! I try it.

**Comment by yuzisun** [comment]
@yurkoff-mv the current Kubeflow version should have already included the fix if you can verify
