### ISSUE TITLE
Failed to build Sklearn server image 

### ISSUE THREAD

**Issue by terrytangyuan** [kserve/kserve#3357]
/kind bug

The build on master branch is failing https://github.com/kserve/kserve/actions/runs/7456669420/job/20287677083

```

#17 [builder 10/12] RUN cd sklearnserver && poetry install --no-root --no-interaction --no-cache
#17 0.914 Installing dependencies from lock file
#17 1.515 
#17 1.515 Package operations: 25 installs, 24 updates, 0 removals
#17 1.515 
#17 1.516   • Installing pycparser (2.21)
#17 1.744   • Installing cffi (1.16.0)
#17 1.807   • Downgrading attrs (23.2.0 -> 23.1.0)
#17 1.809   • Installing cryptography (41.0.5)
#17 1.811   • Downgrading frozenlist (1.4.1 -> 1.4.0)
#17 1.812   • Downgrading idna (3.6 -> 3.4)
#17 1.814   • Downgrading rpds-py (0.16.2 -> 0.13.1)
#17 2.680   • Downgrading anyio (4.2.0 -> 4.1.0)
#17 2.681   • Downgrading google-auth (2.26.1 -> 2.23.4)
#17 2.682   • Downgrading googleapis-common-protos (1.62.0 -> 1.61.0)
#17 2.684   • Installing jmespath (1.0.1)
#17 2.685   • Downgrading referencing (0.32.1 -> 0.31.0)
#17 2.686   • Downgrading wcwidth (0.2.13 -> 0.2.12)
#17 2.688   • Downgrading typing-extensions (4.9.0 -> 4.8.0)
#17 2.688   • Installing pyjwt (2.8.0)
#17 2.801   • Downgrading yarl (1.9.4 -> 1.9.3)
#17 4.055   • Downgrading aiohttp (3.9.1 -> 3.9.0)
#17 4.056   • Installing botocore (1.32.6)
#17 4.057   • Downgrading distlib (0.3.8 -> 0.3.7)
#17 4.058   • Installing google-crc32c (1.5.0)
#17 4.060   • Downgrading jsonschema-specifications (2023.12.1 -> 2023.11.1)
#17 4.061   • Downgrading google-api-core (2.15.0 -> 2.14.0)
#17 4.062   • Installing msal (1.25.0)
#17 4.062   • Installing portalocker (2.8.2)
#17 4.182   • Downgrading psutil (5.9.7 -> 5.9.6)
#17 5.494 
#17 5.494   CalledProcessError
#17 5.495 
#17 5.495   Command '['/prod_venv/bin/python', '-m', 'pip', 'uninstall', 'aiohttp', '-y']' returned non-zero exit status 2.
#17 5.495 
#17 5.495   at /usr/local/lib/python3.9/subprocess.py:528 in run
#17 5.572        524│             # We don't call process.wait() as .__exit__ does that for us.
#17 5.572        525│             raise
#17 5.572        526│         retcode = process.poll()
#17 5.572        527│         if check and retcode:
#17 5.572     →  528│             raise CalledProcessError(retcode, process.args,
#17 5.572        529│                                      output=stdout, stderr=stderr)
#17 5.573        530│     return CompletedProcess(process.args, retcode, stdout, stderr)
#17 5.573        531│ 
#17 5.573        532│ 
#17 5.573 
#17 5.573 The following error occurred when trying to handle this error:
#17 5.573 
#17 5.573 
#17 5.573   EnvCommandError
#17 5.573 
#17 5.573   Command ['/prod_venv/bin/python', '-m', 'pip', 'uninstall', 'aiohttp', '-y'] errored with the following return code 2
#17 5.573   
#17 5.573   Output:
#17 5.573   ERROR: Exception:
#17 5.573   Traceback (most recent call last):
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
#17 5.573       status = run_func(*args)
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/commands/uninstall.py", line 65, in run
#17 5.573       session = self.get_default_session(options)
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
#17 5.573       self._session = self.enter_context(self._build_session(options))
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
#17 5.573       session = PipSession(
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 343, in __init__
#17 5.573       self.headers["User-Agent"] = user_agent()
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/network/session.py", line 175, in user_agent
#17 5.573       setuptools_dist = get_default_environment().get_distribution("setuptools")
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
#17 5.573       return select_backend().Environment.default()
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
#17 5.573       from . import pkg_resources
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
#17 5.573       from pip._vendor import pkg_resources
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
#17 5.573       def _initialize_master_working_set():
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
#17 5.573       f(*args, **kwargs)
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3287, in _initialize_master_working_set
#17 5.573       list(map(working_set.add_entry, sys.path))
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 623, in add_entry
#17 5.573       for dist in find_distributions(entry, True):
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2065, in find_on_path
#17 5.573       for dist in factory(fullpath):
#17 5.573     File "/prod_venv/lib/python3.9/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2127, in distributions_from_metadata
#17 5.573       if len(os.listdir(path)) == 0:
#17 5.573   FileNotFoundError: [Errno 2] No such file or directory: '/prod_venv/lib/python3.9/site-packages/google_api_core-2.15.0.dist-info'
#17 5.573   
#17 5.574 
#17 5.574   at /opt/poetry/lib/python3.9/site-packages/poetry/utils/env/base_env.py:354 in _run
#17 5.591       350│                 output = subprocess.check_output(
#17 5.591       351│                     cmd, stderr=stderr, env=env, text=True, **kwargs
#17 5.591       352│                 )
#17 5.591       353│         except CalledProcessError as e:
#17 5.591     → 354│             raise EnvCommandError(e)
#17 5.591       355│ 
#17 5.592       356│         return output
#17 5.592       357│ 
#17 5.592       358│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
#17 5.592 
#17 5.592 Cannot install aiohttp.
#17 5.592 
#17 ERROR: process "/bin/sh -c cd sklearnserver && poetry install --no-root --no-interaction --no-cache" did not complete successfully: exit code: 1
------
 > [builder 10/12] RUN cd sklearnserver && poetry install --no-root --no-interaction --no-cache:
5.591       352│                 )
5.591       353│         except CalledProcessError as e:
5.591     → 354│             raise EnvCommandError(e)
5.591       355│ 
5.592       356│         return output
5.592       357│ 
5.592       358│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
5.592 
5.592 Cannot install aiohttp.
5.592 
------
sklearn.Dockerfile:29
--------------------
  27 |     
  28 |     COPY sklearnserver/pyproject.toml sklearnserver/poetry.lock sklearnserver/
  29 | >>> RUN cd sklearnserver && poetry install --no-root --no-interaction --no-cache
  30 |     COPY sklearnserver sklearnserver
  31 |     RUN cd sklearnserver && poetry install --no-interaction --no-cache
--------------------
ERROR: failed to solve: process "/bin/sh -c cd sklearnserver && poetry install --no-root --no-interaction --no-cache" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.
```

**Comment by terrytangyuan** [comment]
I cannot reproduce this locally. This seems intermittent.
