### ISSUE TITLE
Serve the large language model with InferenceService，report an error：'type': 'InternalServerException', 'message': 'Worker died.'

### ISSUE THREAD

**Issue by FlyAIBox** [kserve/kserve#3445]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Reference to this document address:  https://kserve.github.io/website/master/modelserving/v1beta1/llm/torchserve/accelerate/

report an error：

**What did you expect to happen:**
curl -v \
  -H "Host: ${SERVICE_HOSTNAME}" \
  -H "Content-Type: application/json" \
  -d @./text.json \
  http://${INGRESS_HOST}:${INGRESS_PORT}/v1/models/bloom7b1:predict

* About to connect() to localhost port 8080 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> POST /v1/models/bloom7b1:predict HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Host: bloom7b1.kserve-test.example.com
> Content-Type: application/json
> Content-Length: 80
> 
* upload completely sent off: 80 out of 80 bytes
< HTTP/1.1 500 Internal Server Error
< content-length: 191
< content-type: application/json
< date: Sun, 18 Feb 2024 06:10:07 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 3156
< 
* Connection #0 to host localhost left intact
{"error":"HTTPStatusError : {'code': 500, 'type': 'InternalServerException', 'message': 'Worker died.'}, '500 Internal Server Error' for url 'http://0.0.0.0:8085/v1/models/bloom7b1:predict'"}

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  namespace: kserve-test
  name: "bloom7b1"
spec:
  predictor:
    pytorch:
      runtimeVersion: 0.8.2
      storageUri: gs://kfserving-examples/models/torchserve/llm/Huggingface_accelerate/bloom
      resources:
        limits:
          cpu: "1"
          memory: 20Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "1"
          memory: 20Gi
          nvidia.com/gpu: "1"

```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
pod log
```bash
2024-02-18T06:16:02,048 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - Worker cmdline: [/home/venv/bin/python, /home/venv/lib/python3.9/site-packages/ts/model_service_worker.py, --sock-type, unix, --sock-name, /home/model-server/tmp/.ts.sock.9000, --metrics-config, /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml]
2024-02-18T06:16:03,873 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - s_name_part0=/home/model-server/tmp/.ts.sock, s_name_part1=9000, pid=855
2024-02-18T06:16:03,874 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2024-02-18T06:16:03,883 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Successfully loaded /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml.
2024-02-18T06:16:03,883 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - [PID]855
2024-02-18T06:16:03,883 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Torch worker started.
2024-02-18T06:16:03,883 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Python runtime: 3.9.18
2024-02-18T06:16:03,883 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bloom7b1_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2024-02-18T06:16:03,884 [INFO ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2024-02-18T06:16:03,885 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2024-02-18T06:16:03,885 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2024-02-18T06:16:03,885 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2024-02-18T06:16:03,885 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1679) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
	at org.pytorch.serve.wlm.Model.pollBatch(Model.java:276) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:34) ~[model-server.jar:?]
	at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:186) [model-server.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2024-02-18T06:16:03,886 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bloom7b1_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2024-02-18T06:16:03,886 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2024-02-18T06:16:03,887 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bloom7b1_1.0-stderr
2024-02-18T06:16:03,887 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bloom7b1_1.0-stdout
2024-02-18T06:16:03,918 [INFO ] W-9000-bloom7b1_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bloom7b1_1.0-stdout
2024-02-18T06:16:03,918 [INFO ] W-9000-bloom7b1_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bloom7b1_1.0-stderr

```

**Environment:**

- Istio Version: 1.17.2
- Knative Version: 1.10.1
- KServe Version: 0.11.2
- Kubernetes version: (use kubectl version): 1.27.2
- OS (e.g. from /etc/os-release): centos:7

@yuzisun @matzew @terrytangyuan

**Comment by gigabyte132** [comment]
+1 I am facing the same issue on kserve 0.11.2

**Comment by terrytangyuan** [comment]
Can you check why worker has died? Was it OOM?

**Comment by thecloudgarage** [comment]
I am facing the same issue and clueless!

2024-11-27T16:39:43,306 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - s_name_part0=/home/model-server/tmp/.ts.sock, s_name_part1=9000, pid=1074
2024-11-27T16:39:43,307 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Listening on port: /home/model-server/tmp/.ts.sock.9000
2024-11-27T16:39:43,312 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Successfully loaded /home/venv/lib/python3.9/site-packages/ts/configs/metrics.yaml.
2024-11-27T16:39:43,312 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - [PID]1074
2024-11-27T16:39:43,312 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Torch worker started.
2024-11-27T16:39:43,312 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Python runtime: 3.9.18
2024-11-27T16:39:43,312 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bloom7b1_1.0 State change WORKER_STOPPED -> WORKER_STARTED
2024-11-27T16:39:43,313 [INFO ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Connecting to: /home/model-server/tmp/.ts.sock.9000
2024-11-27T16:39:43,313 [INFO ] epollEventLoopGroup-5-1 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2024-11-27T16:39:43,313 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - System state is : WORKER_STARTED
2024-11-27T16:39:43,313 [INFO ] W-9000-bloom7b1_1.0-stdout MODEL_LOG - Connection accepted: /home/model-server/tmp/.ts.sock.9000.
2024-11-27T16:39:43,313 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:1679) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:515) ~[?:?]
        at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:677) ~[?:?]
        at org.pytorch.serve.wlm.Model.pollBatch(Model.java:367) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.BatchAggregator.getRequest(BatchAggregator.java:36) ~[model-server.jar:?]
        at org.pytorch.serve.wlm.WorkerThread.run(WorkerThread.java:194) [model-server.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2024-11-27T16:39:43,314 [DEBUG] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - W-9000-bloom7b1_1.0 State change WORKER_STARTED -> WORKER_STOPPED
2024-11-27T16:39:43,314 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Auto recovery failed again
2024-11-27T16:39:43,314 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bloom7b1_1.0-stderr
2024-11-27T16:39:43,314 [WARN ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerLifeCycle - terminateIOStreams() threadName=W-9000-bloom7b1_1.0-stdout
2024-11-27T16:39:43,314 [INFO ] W-9000-bloom7b1_1.0 org.pytorch.serve.wlm.WorkerThread - Retry worker: 9000 in 89 seconds.
2024-11-27T16:39:43,324 [INFO ] W-9000-bloom7b1_1.0-stdout org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bloom7b1_1.0-stdout
2024-11-27T16:39:43,324 [INFO ] W-9000-bloom7b1_1.0-stderr org.pytorch.serve.wlm.WorkerLifeCycle - Stopped Scanner - W-9000-bloom7b1_1.0-stderr
