### ISSUE TITLE
Pytorch V2 Protocol case is not working

### ISSUE THREAD

**Issue by lswjkllc** [kserve/kserve#3478]
/kind bug

**What steps did you take and what happened:**
This case is not working ：https://kserve.github.io/website/0.11/modelserving/v1beta1/torchserve/#deploy-pytorch-model-with-v2-rest-protocol.
The isvc object is ready when using v2 protocal with new scheme:
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "torchserve-mnist-v2"
  labels:
    networking.kserve.io/visibility: cluster-local
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2
```

But, the response always return error when sending a http request for inference: 
```
{"detail":[{"loc":["body","inputs",0,"shape"],"msg":"value is not a valid list","type":"type_error.list"}]}
```

The request:
```
curl -v -H 'Content-Type: application/json' http://127.0.0.1:8080/v2/models/mnist/infer -d @./mnist_v2_bytes.json
```

Before request, I use 'kubectl port-forward' expose the service:
```
kubectl port-forward svc/torchserve-mnist-v2-predictor 8080:80 --address=0.0.0.0
```

**mnist_v2_bytes.json**:
```
{
    "inputs": [
        {
            "data": "iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAA10lEQVR4nGNgGFhgy6xVdrCszBaLFN/mr28+/QOCr69DMCSnA8WvHti0acu/fx/10OS0X/975CDDw8DA1PDn/1pBVEmLf3+zocy2X/+8USXt/82Ds+/+m4sqeehfOpw97d9VFDmlO++t4JwQNMm6f6sZcEpee2+DR/I4A05J7tt4JJP+IUsu+ncRp6TxO9RAQJY0XvrvMAuypNNHuCTz8n+PzVEcy3DtqgiY1ptx6t8/ewY0yX9ntoDA63//Xs3hQpMMPPsPAv68qmDAAFKXwHIzMzCl6AoAxXp0QujtP+8AAAAASUVORK5CYII=",
            "datatype": "BYTES",
            "name": "312a4eb0-0ca7-4803-a101-a6d2c18486fe",
            "shape": -1
        }
    ]
}
```

**What did you expect to happen:**
Expected Output:
```
{"id": "d3b15cad-50a2-4eaf-80ce-8b0a428bd298", "model_name": "mnist", "model_version": "1.0", "outputs": [{"name": "predict", "shape": [], "datatype": "INT64", "data": [1]}]}
```

**What's the InferenceService yaml:**
```
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"serving.kserve.io/v1beta1","kind":"InferenceService","metadata":{"annotations":{},"labels":{"networking.kserve.io/visibility":"cluster-local"},"name":"torchserve-mnist-v2","namespace":"default"},"spec":{"predictor":{"model":{"modelFormat":{"name":"pytorch"},"protocolVersion":"v2","storageUri":"gs://kfserving-examples/models/torchserve/image_classifier/v2"}}}}
    serving.kserve.io/deploymentMode: RawDeployment
  creationTimestamp: "2024-02-26T03:33:01Z"
  finalizers:
  - inferenceservice.finalizers
  generation: 1
  labels:
    networking.kserve.io/visibility: cluster-local
  name: torchserve-mnist-v2
  namespace: default
  resourceVersion: "5052482"
  uid: 69be0e38-90a9-48f1-8b5b-8de8a5f7ecc4
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      name: ""
      protocolVersion: v2
      resources: {}
      storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2
status:
  address:
    url: http://torchserve-mnist-v2-predictor.default.svc.cluster.local
  components:
    predictor:
      latestCreatedRevision: "1"
      url: http://torchserve-mnist-v2-predictor-default.example.com
  conditions:
  - lastTransitionTime: "2024-02-26T03:33:02Z"
    status: "True"
    type: IngressReady
  - lastTransitionTime: "2024-02-26T03:33:42Z"
    status: "True"
    type: PredictorReady
  - lastTransitionTime: "2024-02-26T03:33:42Z"
    status: "True"
    type: Ready
  modelStatus:
    copies:
      failedCopies: 0
      totalCopies: 1
    states:
      activeModelState: Loaded
      targetModelState: Loaded
    transitionStatus: UpToDate
  observedGeneration: 1
  url: http://torchserve-mnist-v2-default.example.com
```

**Environment:**

- KServe Version: 0.11
- Kubernetes version: 1.23.0
- OS (e.g. from `/etc/os-release`): centos 7.9

**Comment by sivanantha321** [comment]
@lswjkllc The input format is wrong. Refer [here](https://github.com/pytorch/serve/blob/master/kubernetes/kserve/kf_request_json/v2/mnist/mnist_v2_bytes.json)

**Comment by lswjkllc** [comment]
thank you @sivanantha321 

I change the request as below:
```
curl -v -H 'Content-Type: application/json' http://127.0.0.1:8080/v2/models/mnist/infer -d'{
>     "id": "d3b15cad-50a2-4eaf-80ce-8b0a428bd298",
>     "inputs": [
>         {
>             "data": ["iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAA10lEQVR4nGNgGFhgy6xVdrCszBaLFN/mr28+/QOCr69DMCSnA8WvHti0acu/fx/10OS0X/975CDDw8DA1PDn/1pBVEmLf3+zocy2X/+8USXt/82Ds+/+m4sqeehfOpw97d9VFDmlO++t4JwQNMm6f6sZcEpee2+DR/I4A05J7tt4JJP+IUsu+ncRp6TxO9RAQJY0XvrvMAuypNNHuCTz8n+PzVEcy3DtqgiY1ptx6t8/ewY0yX9ntoDA63//Xs3hQpMMPPsPAv68qmDAAFKXwHIzMzCl6AoAxXp0QujtP+8AAAAASUVORK5CYII="],
>             "datatype": "BYTES",
>             "name": "312a4eb0-0ca7-4803-a101-a6d2c18486fe",
>             "shape": [-1]
>         }
>     ]
> }'
```

The InferenceService is Reday and the Pod is Running.
But, return the error when sending the request above:
```
{"error":"HTTPStatusError : {'code': 503, 'type': 'InternalServerException', 'message': 'Prediction failed'}, '503 Service Unavailable' for url 'http://0.0.0.0:8085/v1/models/mnist:predict'"}
```

I guess the case('storageUri: gs://kfserving-examples/models/torchserve/image_classifier/v2'), it unavailable?

Are there any other examples available?

**Comment by sivanantha321** [comment]
If you notice the error it is using V1 endpoint. `'http://0.0.0.0:8085/v1/models/mnist:predict'"}`

**Comment by lswjkllc** [comment]
@sivanantha321 hello

The error also exist when requesting the url(http://0.0.0.0:8085/v1/models/mnist:predict) directly.

Stack error below:
```
2024-02-27 14:45:39.492 37650 root INFO [timing():48] kserve.io.kserve.protocol.rest.v1_endpoints.predict 18.291365146636963, ['http_status:500', 'http_method:POST', 'time:wall']
2024-02-27 14:45:39.493 37650 root INFO [timing():48] kserve.io.kserve.protocol.rest.v1_endpoints.predict 0.35211900000000007, ['http_status:500', 'http_method:POST', 'time:cpu']
2024-02-27 14:45:39.494 37650 uvicorn.error ERROR [run_asgi():376] Exception in ASGI application
Traceback (most recent call last):
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/timing_asgi/middleware.py", line 70, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/fastapi/routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/kserve/protocol/rest/v1_endpoints.py", line 69, in predict
    response, response_headers = await self.dataplane.infer(model_name=model_name, body=body, headers=headers)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/kserve/protocol/dataplane.py", line 276, in infer
    response = await model(body, headers=headers)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/kserve/model.py", line 116, in __call__
    response = (await self.predict(payload, headers)) if inspect.iscoroutinefunction(self.predict) \
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/kserve/model.py", line 319, in predict
    return await self._http_predict(payload, headers)
  File "/Users/kust/Workspace/projects/bocloud/torchserve/.py38/lib/python3.8/site-packages/kserve/model.py", line 286, in _http_predict
    raise HTTPStatusError(message, request=response.request, response=response)
httpx.HTTPStatusError: {'code': 503, 'type': 'InternalServerException', 'message': 'Prediction failed'}, '503 Service Unavailable' for url 'http://0.0.0.0:8085/v1/models/mnist:predict'
```

I don't know if it's a data format problem or a program problem.
I tried two format:
```
# first
{
    "id": "d3b15cad-50a2-4eaf-80ce-8b0a428bd298",
    "inputs": [
        {
            "data": ["iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAA10lEQVR4nGNgGFhgy6xVdrCszBaLFN/mr28+/QOCr69DMCSnA8WvHti0acu/fx/10OS0X/975CDDw8DA1PDn/1pBVEmLf3+zocy2X/+8USXt/82Ds+/+m4sqeehfOpw97d9VFDmlO++t4JwQNMm6f6sZcEpee2+DR/I4A05J7tt4JJP+IUsu+ncRp6TxO9RAQJY0XvrvMAuypNNHuCTz8n+PzVEcy3DtqgiY1ptx6t8/ewY0yX9ntoDA63//Xs3hQpMMPPsPAv68qmDAAFKXwHIzMzCl6AoAxXp0QujtP+8AAAAASUVORK5CYII="],
            "datatype": "BYTES",
            "name": "312a4eb0-0ca7-4803-a101-a6d2c18486fe",
            "shape": [-1]
        }
    ]
}

# second
{
    "instances": [
        {
            "data": "iVBORw0KGgoAAAANSUhEUgAAABwAAAAcCAAAAABXZoBIAAAAw0lEQVR4nGNgGFggVVj4/y8Q2GOR83n+58/fP0DwcSqmpNN7oOTJw6f+/H2pjUU2JCSEk0EWqN0cl828e/FIxvz9/9cCh1zS5z9/G9mwyzl/+PNnKQ45nyNAr9ThMHQ/UG4tDofuB4bQIhz6fIBenMWJQ+7Vn7+zeLCbKXv6z59NOPQVgsIcW4QA9YFi6wNQLrKwsBebW/68DJ388Nun5XFocrqvIFH59+XhBAxThTfeB0r+vP/QHbuDCgr2JmOXoSsAAKK7bU3vISS4AAAAAElFTkSuQmCC",
            "target": 0
        }
    ]
}
```

**Comment by lswjkllc** [comment]
KServe Version Upgrade to 0.11.2, reslove the problem.

**Comment by lswjkllc** [comment]
KServe Version Upgrade to 0.11.2, reslove the problem.
