### ISSUE TITLE
 You need to specify either `text` or `text_target`

### ISSUE THREAD

**Issue by yolk-pie-L** [kserve/kserve#3515]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

I try the README.md in the huggingface server https://github.com/kserve/kserve/blob/master/python/huggingfaceserver/README.md

```
root@63e5f92ee6b6:~/study# kubectl get isvc
NAME               URL                                           READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION                AGE
huggingface-bert   http://huggingface-bert.default.example.com   True           100                              huggingface-bert-predictor-00001   4m55s
```

Then I run 

```
curl -H "Host: huggingface-bert.default.example.com" xxx.us-west-2.elb.amazonaws.com -d '{"instances": ["The capital of france is [MASK]."] }'
```

The response is 

```
{"error":"ValueError : You need to specify either `text` or `text_target`."}
```

**What did you expect to happen:**

It should give out the result as in the README.md

```
{"predictions":["paris"]}
```

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The pod log

```
2024-03-13 03:19:49.874 uvicorn.access INFO:     172.31.19.236:0 1 - "POST /v1/models/bert%3Apredict HTTP/1.1" 500 Internal Server Error
2024-03-13 03:19:49.874 uvicorn.error ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/prod_venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/prod_venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/prod_venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/prod_venv/lib/python3.10/site-packages/timing_asgi/middleware.py", line 70, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/prod_venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/prod_venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/prod_venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/prod_venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/prod_venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/prod_venv/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/prod_venv/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/kserve/kserve/protocol/rest/v1_endpoints.py", line 76, in predict
    response, response_headers = await self.dataplane.infer(model_name=model_name,
  File "/kserve/kserve/protocol/dataplane.py", line 324, in infer
    response = await model(request, headers=headers)
  File "/kserve/kserve/model.py", line 132, in __call__
    else self.preprocess(body, headers)
  File "/huggingfaceserver/huggingfaceserver/model.py", line 170, in preprocess
    inputs = self.tokenizer(
  File "/prod_venv/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2797, in __call__
    raise ValueError("You need to specify either `text` or `text_target`.")
ValueError: You need to specify either `text` or `text_target`.
```

**Environment:**

- Istio Version: install through https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#install-a-networking-layer
- Knative Version: v1.13.1
- KServe Version: v0.12.0
- Kubeflow version: none
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]: aws elastic kubernetes service
- Kubernetes version: (use `kubectl version`): client version: v1.25.0, Server version: 1.29
- OS (e.g. from `/etc/os-release`):

**Comment by yolk-pie-L** [comment]
It may be I lack the header "Content-Type": "application/json"
