### ISSUE TITLE
UnicodeDecodeError for grpcurl request with Bytes column in DataFrame

### ISSUE THREAD

**Issue by jinholee-makinarocks** [kserve/kserve#3731]
/kind bug

**What steps did you take and what happened:**
- deploy serving.kserve.io/v1beta1/InferenceService with custom container predictor
- send grpc message with below command: 
[inputs_sample-3.json](https://github.com/user-attachments/files/15783785/inputs_sample-3.json)
```bash
grpcurl --plaintext --proto serving-grpcapi.proto -d @ localhost:80 inference.GRPCInferenceService.ModelInfer <<< $(cat inputs_sample-3.json)
```
- grpc server returns error message and terminal message is as following:
```bash
INFO:root:grpc method: /inference.GRPCInferenceService/ModelInfer
ERROR:grpc._cython.cygrpc:Unexpected [UnicodeDecodeError] raised by servicer method [/inference.GRPCInferenceService/ModelInfer]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 796, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 547, in _handle_unary_unary_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 404, in _finish_handler_with_unary_response
  File "/usr/local/lib/python3.9/dist-packages/kserve/protocol/grpc/servicer.py", line 94, in ModelInfer
    response_body, _ = await self._data_plane.infer(request=infer_request, headers=headers,
  File "/usr/local/lib/python3.9/dist-packages/kserve/protocol/dataplane.py", line 311, in infer
    response = await model(request, headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/kserve/model.py", line 122, in __call__
    else self.predict(payload, headers)
  File "/usr/local/lib/python3.9/dist-packages/runway/cli/inference_server.py", line 138, in predict
    result = getattr(self.model, self.model_method_name)(None, get_predict_input(payload))
  File "/usr/local/lib/python3.9/dist-packages/kserve/utils/utils.py", line 185, in get_predict_input
    return payload.as_dataframe()
  File "/usr/local/lib/python3.9/dist-packages/kserve/protocol/infer_type.py", line 328, in as_dataframe
    input_data = [str(val, "utf-8") if isinstance(val, bytes)
  File "/usr/local/lib/python3.9/dist-packages/kserve/protocol/infer_type.py", line 328, in <listcomp>
    input_data = [str(val, "utf-8") if isinstance(val, bytes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**What did you expect to happen:**
I expect grpcurl command to work well.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:1.14.3
- Knative Version:1.7.4
- KServe Version: kserve-controller==0.10.0, kserve-python==0.11.2
- Kubeflow version: None
- Cloud Environment:[k8s_istio]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):1.22.17
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
@jinholee-makinarocks Can you try with 0.13.0 ?

**Comment by jinholee-makinarocks** [comment]
@sivanantha321 same issue happened at 0.13.0.
```
jovyan@isvc-deployment-13-predictor-default-00002-deployment-7d85hcdrb:~$ pip freeze | grep kserve
kserve==0.13.0
```
```
│ /home/jovyan/.local/lib/python3.9/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_registry" has conflict with protected nam │
│                                                                                                                                                        │
│ You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ('settings_',)`.                                            │
│   warnings.warn(                                                                                                                                       │
│ 2024-06-19 04:55:18.472 1 kserve INFO [model_server.py:register_model():384] Registering model: isvc-deployment-13                                     │
│ 2024-06-19 04:55:18.473 1 kserve INFO [model_server.py:start():254] Setting max asyncio worker threads as 6                                            │
│ 2024-06-19 04:55:18.473 1 kserve INFO [model_server.py:serve():260] Starting uvicorn with 1 workers                                                    │
│ 2024-06-19 04:55:18.530 uvicorn.error INFO:     Started server process [1]                                                                             │
│ 2024-06-19 04:55:18.530 uvicorn.error INFO:     Waiting for application startup.                                                                       │
│ 2024-06-19 04:55:18.534 1 kserve INFO [server.py:start():63] Starting gRPC server on :8081                                                             │
│ 2024-06-19 04:55:18.534 uvicorn.error INFO:     Application startup complete.                                                                          │
│ 2024-06-19 04:55:18.534 uvicorn.error INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)                                          │
│ 2024-06-19 04:57:20.081 1 kserve INFO [interceptors.py:intercept_service():30] grpc method: /inference.GRPCInferenceService/ModelInfer                 │
│ ERROR:grpc._cython.cygrpc:Unexpected [UnicodeDecodeError] raised by servicer method [/inference.GRPCInferenceService/ModelInfer]                       │
│ Traceback (most recent call last):                                                                                                                     │
│   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in grpc._cython.cygrpc._handle_exceptions                                │
│   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 796, in _handle_rpc                                                           │
│   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 547, in _handle_unary_unary_rpc                                               │
│   File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 404, in _finish_handler_with_unary_response                                   │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/protocol/grpc/servicer.py", line 118, in ModelInfer                                     │
│     response_body, _ = await self._data_plane.infer(                                                                                                   │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/protocol/dataplane.py", line 343, in infer                                              │
│     response = await model(request, headers=headers)                                                                                                   │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/model.py", line 203, in __call__                                                        │
│     else self.predict(payload, headers)                                                                                                                │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/runway/cli/inference_server.py", line 138, in predict                                          │
│     result = getattr(self.model, self.model_method_name)(None, get_predict_input(payload))                                                             │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/utils/utils.py", line 181, in get_predict_input                                         │
│     return payload.as_dataframe()                                                                                                                      │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/protocol/infer_type.py", line 506, in as_dataframe                                      │
│     input_data = [                                                                                                                                     │
│   File "/home/jovyan/.local/lib/python3.9/site-packages/kserve/protocol/infer_type.py", line 507, in <listcomp>                                        │
│     str(val, "utf-8") if isinstance(val, bytes) else val                                                                                               │
│ UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte       
```

**Comment by jinholee-makinarocks** [comment]
@sivanantha321 . How should I do ?... any idea?

**Comment by sivanantha321** [comment]
We are looking into this. We will get back to you soon.

**Comment by sivanantha321** [comment]
@jinholee-makinarocks, We tested your input against our [custom model](https://github.com/kserve/kserve/blob/master/python/custom_model/model_grpc.py) with KServe 0.13.0. We are unable to reproduce your error. Here is the output we received.
```bash
grpcurl --plaintext --proto /home/ubuntu/go/src/github.com/kserve/kserve/python/kserve/kserve/protocol/grpc/grpc_predict_v2.proto -import-path /home/ubuntu/go/src/github.com/kserve/kserve/python/kserve/kserve/protocol/grpc -authority [custom-model-grpc.kserve-ci-e2e-test.example.com](http://custom-model-grpc.kserve-ci-e2e-test.example.com/) -d @ localhost:8080 inference.GRPCInferenceService.ModelInfer <<< $(cat inputs_sample-3.json)


{
  "modelName": "custom-model",
  "id": "8de2a767-9d37-48ce-99ea-fe8ffba5655d",
  "outputs": [
    {
      "name": "output-0",
      "datatype": "FP32",
      "shape": [
        "1",
        "5"
      ],
      "contents": {
        "fp32Contents": [
          13.944185,
          11.045145,
          9.6355,
          8.990225,
          8.953767
        ]
      }
    }
  ]
}
```

There are two things we noticed.
1. Your input file is missing model name field. Here is the modfied [inputs_sample-3.json](https://github.com/user-attachments/files/15913072/inputs_sample-3.json) with your data.
2. Your grpcurl does not have authority header.

Can you try with these changes ?

**Comment by jinholee-makinarocks** [comment]
@sivanantha321 . I tried to test as your comments without `authority` setting, the result is same...:
```
grpcurl --plaintext --proto serving-grpcapi.proto -d @ isvc-deployment-13.bug-rway-7241-project-93df.serving.dev.mrxrunway.ai:80 inference.GRPCInferenceService.ModelInfer <<< $(cat inputs_sample-3-2.json)
ERROR:
  Code: Unknown
  Message: Unexpected <class 'UnicodeDecodeError'>: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```
does it need to set the `authority` argument ? is it major ?

**Comment by jinholee-makinarocks** [comment]
@sivanantha321 What's the reason to decode `InferInput.data` as following:
https://github.com/kserve/kserve/blob/fbd87784da4ff08edc5305f7013abf837b071b28/python/kserve/kserve/protocol/infer_type.py#L507

I think you define field type (`repeated bytes`) of bytes_contents and expect the user also set data type of input to `"BYTE"`. It's why it looks like it's coded like this:
https://github.com/kserve/kserve/blob/fbd87784da4ff08edc5305f7013abf837b071b28/python/kserve/kserve/protocol/infer_type.py#L341

So, if the loaded ML model would have bytes input type argument as dataframe, can't we use kserve package ?
