### ISSUE TITLE
ImportError: cannot import name 'BentoService' from 'bentoml' (/usr/local/lib/python3.9/dist-packages/bentoml/__init__.py)

### ISSUE THREAD

**Issue by LOADBC** [kserve/kserve#3778]
/kind bug

I was trying out some samples on Predict on an InferenceService using BentoML 
https://github.com/kserve/kserve/tree/master/docs/samples/bentoml

i installed :-
-pip3 install bentoml scikit-learn
i created :-
-Create the BentoML Service file (iris_classifier.py)

```
from bentoml import env, artifacts, api, BentoService
from bentoml.handlers import DataframeHandler
from bentoml.artifact import SklearnModelArtifact

@env(auto_pip_dependencies=True)
@artifacts([SklearnModelArtifact('model')])
class IrisClassifier(BentoService):

    @api(DataframeHandler)
    def predict(self, df):
        return self.artifacts.model.predict(df)
```

-Create the model training and service saving script main.py

```
from sklearn import svm
from sklearn import datasets

from iris_classifier import IrisClassifier

if __name__ == "__main__":
    # Load training data
    iris = datasets.load_iris()
    X, y = iris.data, iris.target

    # Model Training
    clf = svm.SVC(gamma='scale')
    clf.fit(X, y)

    # Create a iris classifier service instance
    iris_classifier_service = IrisClassifier()

    # Pack the newly trained model artifact
    iris_classifier_service.pack('model', clf)

    # Save the prediction service to disk for model serving
    saved_path = iris_classifier_service.save()

```

-then i ran python3 main.py

-but i got this error:-

Traceback (most recent call last):
  File "/root/main.py", line 4, in <module>
    from iris_classifier import IrisClassifier
  File "/root/iris_classifier.py", line 1, in <module>
    from bentoml import env, artifacts, api, BentoService
ImportError: cannot import name 'env' from 'bentoml' (/usr/local/lib/python3.9/dist-packages/bentoml/__init__.py)

I would like to add that i am working on an environment and on a root of a cluster created by:-
./multikf.linux add node02 --with_kubeflow=false
docker exec -it <containner_id> bin/bash

**Environment:**

- KServe Version: 0.11
- Kubeflow version: no
- Kind version: 0.23.0

**Comment by YehCC52** [comment]
Hi, I'd like to work on this issue .I'm new to KServe .I would like to start by modifying the version of bentoML that corresponds to main.py and iris_classifier.py.
