### ISSUE TITLE
mlflow model cannot be deployed

### ISSUE THREAD

**Issue by sakasak0** [kserve/kserve#3797]
/kind bug

**What steps did you take and what happened:**

I tried to deploy a MLflow model using KServe.
However, the inferenceService Pod was in an error state. I checked the logs using `kubectl logs <pod_name>` and found a `pydantic.errors.PydanticImportError` .

```
$ kubectl -n <namespace> logs pytorch-tar-predictor-00001-deployment-5549cc798b-xfcb6
(omitted)
bin/activate
bin/deactivate
bin/conda-unpack
--> Sourcing new environment at ./envs/environment...
--> Calling conda-unpack...
usage: conda-unpack [-h] [--version]
conda-unpack: error: unrecognized arguments: --quiet
--> Disabling user-installed packages...
/opt/mlserver/envs/environment/lib/python3.8/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`.
warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
/opt/mlserver/envs/environment/lib/python3.8/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic:PyObject` has been moved to `pydantic.types:ImportString`.
warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')
Traceback (most recent call last):
File "/opt/mlserver/envs/environment/bin/mlserver", line 5, in <module>
from mlserver.cli import main
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/__init__.py", line 2, in <module>
from .server import MLServer
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/server.py", line 7, in <module>
from mlserver.repository.factory import ModelRepositoryFactory
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/repository/__init__.py", line 1, in <module>
from .repository import (
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/repository/repository.py", line 8, in <module>
from ..settings import ModelParameters, ModelSettings
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/mlserver/settings.py", line 8, in <module>
from pydantic import PyObject, Extra, Field, BaseSettings as _BaseSettings
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/pydantic/__init__.py", line 386, in __getattr__
return _getattr_migration(attr_name)
File "/opt/mlserver/envs/environment/lib/python3.8/site-packages/pydantic/_migration.py", line 296, in wrapper
raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.7/migration/#basesettings-has-moved-to-pydantic-settings for more details.
For further information visit https://errors.pydantic.dev/2.7/u/import-error
```

This appears to be because MLServer did not support Pydantic V2 until version `1.5.0`. MLServer v1.6.0 supports Pydantic V2, so I hope patching the MLServer image tag to `1.6.0`.
I was able to deploy the model after downgrading the pydantic version
References:
- https://github.com/SeldonIO/MLServer/releases/tag/1.6.0
- https://hub.docker.com/layers/seldonio/mlserver/1.6.0/images/sha256-00d793258d1ae582bfb0c236650e4d3afe3ae866be4b95532ec52c9497ac2f52?context=explore

**What did you expect to happen:**

The inference service was deployed.

**What's the InferenceService yaml:**

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "pytorch-tar"
spec:
  predictor:
    serviceAccountName: mlf-ksrv
    model:
      modelFormat:
        name: mlflow
      protocolVersion: v2
      storageUri: "s3://mlf-bucket/3/51632a54df1c400180bc68d502c18944/artifacts/pytorch-model/"
```

**Anything else you would like to add:**
I'm considering modifying the MLServer tag (1.15.0 -> 1.16.0) in the following files referencing this request [#3740](https://github.com/kserve/kserve/pull/3740).
files
- `charts/kserve-resources/README.md` 
- `charts/kserve-resources/values.yaml`
- `config/runtimes/kustomization.yaml` 

If you're okay with it, I'd like to fix this and commit the changes.     
Could you please let me know if any of the following files should also be modified?
- `kserve/install/vNN.NN.NN/kserve-cluster-resources.yaml`
ex) [kserve-cluster-resources.yaml#L80](https://github.com/kserve/kserve/blob/master/install/v0.13.0-rc0/kserve-cluster-resources.yaml#L80 )

**Environment:**

- Istio Version: v1.21.0
- Knative Version: v1.13.1
- KServe Version: v0.12.0
- Kubeflow version:
- Cloud Environment: k8s_istio
- Minikube/Kind version:
- Kubernetes version: v1.29.3
- OS: ubuntu22.04

**Comment by sakasak0** [comment]
I confirmed that the issue was resolved by modifying the following three files and building KServe locally:

* charts/kserve-resources/README.md
* charts/kserve-resources/values.yaml
* config/runtimes/kustomization.yaml

The changes (git diff) are as follows:

```
diff --git a/charts/kserve-resources/README.md b/charts/kserve-resources/README.md
index 167d75f6..ebe302c2 100644
--- a/charts/kserve-resources/README.md
+++ b/charts/kserve-resources/README.md
@@ -72,7 +72,7 @@ $ helm install kserve oci://ghcr.io/kserve/charts/kserve --version v0.13.0
 | kserve.servingruntime.lgbserver.tag | string | `"v0.13.0"` |  |
 | kserve.servingruntime.mlserver.image | string | `"docker.io/seldonio/mlserver"` |  |
 | kserve.servingruntime.mlserver.modelClassPlaceholder | string | `"{{.Labels.modelClass}}"` |  |
-| kserve.servingruntime.mlserver.tag | string | `"1.5.0"` |  |
+| kserve.servingruntime.mlserver.tag | string | `"1.6.0"` |  |
 | kserve.servingruntime.modelNamePlaceholder | string | `"{{.Name}}"` |  |
 | kserve.servingruntime.paddleserver.image | string | `"kserve/paddleserver"` |  |
 | kserve.servingruntime.paddleserver.tag | string | `"v0.13.0"` |  |
diff --git a/charts/kserve-resources/values.yaml b/charts/kserve-resources/values.yaml
index 82fbb719..42f51828 100644
--- a/charts/kserve-resources/values.yaml
+++ b/charts/kserve-resources/values.yaml
@@ -95,7 +95,7 @@ kserve:
       tag: 2.6.2
     mlserver:
       image: docker.io/seldonio/mlserver
-      tag: 1.5.0
+      tag: 1.6.0
       modelClassPlaceholder: "{{.Labels.modelClass}}"
     sklearnserver:
       image: kserve/sklearnserver
diff --git a/config/runtimes/kustomization.yaml b/config/runtimes/kustomization.yaml
index 92dedae5..2eab8ed1 100644
--- a/config/runtimes/kustomization.yaml
+++ b/config/runtimes/kustomization.yaml
@@ -25,7 +25,7 @@ images:

 - name: mlserver
   newName: docker.io/seldonio/mlserver
-  newTag: 1.5.0
+  newTag: 1.6.0

 - name: kserve-xgbserver
   newName: kserve/xgbserver
```

Would you like me to create a pull request with these changes?
Resolving this would be helpful as it would allow us to use pydantic v2.x for model development.
