### ISSUE TITLE
fail to locate model file for model <model-name> under dir /mnt/models,trying loading from model repository

### ISSUE THREAD

**Issue by PSKP-95** [kserve/kserve#3816]
/kind bug

**What steps did you take and what happened:**
new deployment of kserve 0.12.0 on rancher started giving this issue. we are using ceph for storing models. storage initilizer pulled model successfully. but when kserve-container started, it gave error `ERROR:root:fail to locate model file for model 7fcc38e8-a0cd-4474-93c3-3f61d9c7bde6 under dir /mnt/models,trying loading from model repository.` but container **did not fail**. Then when I tried to do inference, it gave `kserve.errors.ModelNotFound: Model with name 7fcc38e8-a0cd-4474-93c3-3f61d9c7bde6 does not exist.` 

**kserve-container logs**
```
INFO:root:Copying contents of /mnt/models to local
ERROR:root:fail to locate model file for model 7fcc38e8-a0cd-4474-93c3-3f61d9c7bde6 under dir /mnt/models,trying loading from model repository.
INFO:kserve:Setting max asyncio worker threads as 5
INFO:kserve:Starting uvicorn with 1 workers
2024-07-23 18:26:58.971 uvicorn.error INFO:     Started server process [1]
2024-07-23 18:26:58.972 uvicorn.error INFO:     Waiting for application startup.
2024-07-23 18:26:58.978 1 kserve INFO [start():62] Starting gRPC server on [::]:8081
2024-07-23 18:26:58.979 uvicorn.error INFO:     Application startup complete.
2024-07-23 18:26:58.979 uvicorn.error INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2024-07-23 18:40:47.727 1 kserve ERROR [model_not_found_handler():113] Exception:
Traceback (most recent call last):
  File "/prod_venv/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/prod_venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/prod_venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/prod_venv/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/prod_venv/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/prod_venv/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/prod_venv/lib/python3.9/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/prod_venv/lib/python3.9/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/kserve/kserve/protocol/rest/v2_endpoints.py", line 136, in infer
    model_ready = self.dataplane.model_ready(model_name)
  File "/kserve/kserve/protocol/dataplane.py", line 214, in model_ready
    raise ModelNotFound(model_name)
kserve.errors.ModelNotFound: Model with name 7fcc38e8-a0cd-4474-93c3-3f61d9c7bde6 does not exist.
2024-07-23 18:40:47.730 uvicorn.access INFO:     127.0.0.6:0 1 - "POST /v2/models/7fcc38e8-a0cd-4474-93c3-3f61d9c7bde6/infer HTTP/1.1" 404 Not Found
2024-07-23 18:40:47.730 kserve.trace kserve.io.kserve.protocol.rest.v2_endpoints.infer: 0.005957126617431641
2024-07-23 18:40:47.730 kserve.trace kserve.io.kserve.protocol.rest.v2_endpoints.infer: 0.005691999999999808
```

**storage initializer logs**

```
INFO:root:Initializing, args: src_uri [s3://xxxxx/xxxxx/8aaa96cb907284db0190a190ce5d0018/8aaa96cb907284db0190a190f8b1001b/model.pkl] dest_path[ [/mnt/models]
INFO:root:Copying contents of s3://xxxxx/xxxxx/8aaa96cb907284db0190a190ce5d0018/8aaa96cb907284db0190a190f8b1001b/model.pkl to local
INFO:botocore.credentials:Found credentials in environment variables.
INFO:root:Downloaded object xxxxx/8aaa96cb907284db0190a190ce5d0018/8aaa96cb907284db0190a190f8b1001b/model.pkl to /mnt/models/model.pkl
INFO:root:Successfully copied s3://xxxxx/xxxxx/8aaa96cb907284db0190a190ce5d0018/8aaa96cb907284db0190a190f8b1001b/model.pkl to /mnt/models
```

![image](https://github.com/user-attachments/assets/56711629-5c46-4d3e-af3c-a066eef060e5)

**What did you expect to happen:**
It should get the model from `/mnt/models` and give inference.

**What's the InferenceService yaml:**
I cant access custom resources. Will get it from ops and add it later.

**Anything else you would like to add:**

![image](https://github.com/user-attachments/assets/c4383846-f803-427c-bcc2-14df1781fcdd)

**Environment:**

- Istio Version: 1.20.0
- Knative Version: 1.13.1
- KServe Version: 0.12.0
- Kubeflow version: none
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] none
- Minikube/Kind version: none
- Kubernetes version: (use `kubectl version`): 1.26.13
- OS (e.g. from `/etc/os-release`):

**Comment by ishaan-mehta** [comment]
Hi @PSKP-95, how did you solve this? I am seeing the same issue.

**Comment by PSKP-95** [comment]
Hi @ishaan-mehta , I forgot what was the issue & solution. Sorry.

**Comment by MarcoLuw** [comment]
Hi @PSKP-95, as I'm facing the same issue, it will be great if you can remember the solution again.
The issue is that Kserve could not locate the model in **/mnt/models**, although the model did exist in this directory

**Comment by PSKP-95** [comment]
Hi @MarcoLuw , I am not able to remember it but here are few thing you can check

- Check if your model file type is supported by ClusterServingRuntime/ServingRuntime selected.
- Check if you can load your model locally. You can check serving runtime code.
- Make sure all files required present and process user can access that path.
