### ISSUE TITLE
kserve/storage-initializer:v0.13.0 fetch error via AWS s3 role

### ISSUE THREAD

**Issue by life-learner1** [kserve/kserve#3843]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I got an error when download from AWS S3 with IAM role, but it only happens when I use storage-initializer:v0.13.0, if I use storage-initializer:v0.10.0, it works well, please check.

Here is the error output:
```log
2024-08-07 06:56:01.558 1 kserve INFO [initializer-entrypoint:<module>():16] Initializing, args: src_uri [s3://ai-models/intention-and-similar/] dest_path[ [/mnt/models]
2024-08-07 06:56:01.558 1 kserve INFO [storage.py:download():66] Copying contents of s3://ai-models/intention-and-simila/ to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 17, in <module>
    Storage.download(src_uri, dest_path)
  File "/kserve/kserve/storage/storage.py", line 86, in download
    Storage._download_s3(uri, out_dir)
  File "/kserve/kserve/storage/storage.py", line 225, in _download_s3
    for obj in bucket.objects.filter(Prefix=bucket_path):
  File "/prod_venv/lib/python3.9/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/prod_venv/lib/python3.9/site-packages/boto3/resources/collection.py", line 171, in pages
    for page in pages:
  File "/prod_venv/lib/python3.9/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/client.py", line 565, in _api_call 
    return self._make_api_call(operation_name, kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
  File "/prod_venv/lib/python3.9/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/prod_venv/lib/python3.9/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/prod_venv/lib/python3.9/site-packages/botocore/signers.py", line 190, in sign
    auth = self.get_auth_instance(**kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/signers.py", line 310, in get_auth_instance
    frozen_credentials = credentials.get_frozen_credentials()
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 634, in get_frozen_credentials
    self._refresh()
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 522, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 538, in _protected_refresh
    metadata = self._refresh_using()
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 685, in fetch_credentials
    return self._get_cached_credentials()
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 695, in _get_cached_credentials
    response = self._get_credentials()
  File "/prod_venv/lib/python3.9/site-packages/botocore/credentials.py", line 929, in _get_credentials
    return client.assume_role_with_web_identity(**kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/prod_venv/lib/python3.9/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Unknown) when calling the AssumeRoleWithWebIdentity operation: Unknown
```

**What did you expect to happen:**
Download the file from S3

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ii2day** [comment]
I still have this problem using v0.10.0, but I am using minio
