### ISSUE TITLE
Controller-gen panic under golang 1.22

### ISSUE THREAD

**Issue by fyuan1316** [kserve/kserve#3853]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```bash
make test
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
/kserve/bin/controller-gen "crd:maxDescLen=0" paths=./pkg/apis/serving/... output:crd:dir=config/crd/full
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc2188f]

goroutine 138 [running]:
go/types.(*Checker).handleBailout(0xc0008aca00, 0xc00004fd40)
	/usr/local/opt/go/libexec/src/go/types/check.go:367 +0x88
panic({0xbf19580?, 0xc4cbec0?})
	/usr/local/opt/go/libexec/src/runtime/panic.go:770 +0x132
go/types.(*StdSizes).Sizeof(0x0, {0xbfe42b0, 0xc4d4620})
	/usr/local/opt/go/libexec/src/go/types/sizes.go:228 +0x30f
go/types.(*Config).sizeof(...)
	/usr/local/opt/go/libexec/src/go/types/sizes.go:333
go/types.representableConst.func1({0xbfe42b0?, 0xc4d4620?})
	/usr/local/opt/go/libexec/src/go/types/const.go:76 +0x9e
go/types.representableConst({0xbfea510, 0xc4a07a8}, 0xc0008aca00, 0xc4d4620, 0xc00004f4b0)
	/usr/local/opt/go/libexec/src/go/types/const.go:92 +0x192
go/types.(*Checker).representation(0xc0008aca00, 0xc001402380, 0xc4d4620)
	/usr/local/opt/go/libexec/src/go/types/const.go:256 +0x65
go/types.(*Checker).implicitTypeAndValue(0xc0008aca00, 0xc001402380, {0xbfe42d8, 0xc0000de1c0})
	/usr/local/opt/go/libexec/src/go/types/expr.go:375 +0x2d7
go/types.(*Checker).assignment(0xc0008aca00, 0xc001402380, {0xbfe42d8, 0xc0000de1c0}, {0xbd58800, 0x14})
	/usr/local/opt/go/libexec/src/go/types/assignments.go:52 +0x2e5
go/types.(*Checker).initConst(0xc0008aca00, 0xc000d03b00, 0xc001402380)
	/usr/local/opt/go/libexec/src/go/types/assignments.go:126 +0x2c5
go/types.(*Checker).constDecl(0xc0008aca00, 0xc000d03b00, {0xbfe6e80, 0xc00076d9e0}, {0xbfe83b0, 0xc000771800}, 0x0)
	/usr/local/opt/go/libexec/src/go/types/decl.go:490 +0x311
go/types.(*Checker).objDecl(0xc0008aca00, {0xbfef660, 0xc000d03b00}, 0x0)
	/usr/local/opt/go/libexec/src/go/types/decl.go:191 +0xa49
go/types.(*Checker).packageObjects(0xc0008aca00)
	/usr/local/opt/go/libexec/src/go/types/resolver.go:693 +0x4dd
go/types.(*Checker).checkFiles(0xc0008aca00, {0xc000b8a6f0, 0x1, 0x1})
	/usr/local/opt/go/libexec/src/go/types/check.go:408 +0x1a5
go/types.(*Checker).Files(...)
	/usr/local/opt/go/libexec/src/go/types/check.go:372
sigs.k8s.io/controller-tools/pkg/loader.(*loader).typeCheck(0xc0002a9440, 0xc0000cc740)
	/Users/yuan/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:286 +0x36a
sigs.k8s.io/controller-tools/pkg/loader.(*Package).NeedTypesInfo(0xc0000cc740)
	/Users/yuan/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/loader.go:99 +0x39
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check(0xc000d1cae0, 0xc0000cc740)
	/Users/yuan/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:268 +0x2b7
sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check.func1(0x66?)
	/Users/yuan/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:262 +0x53
created by sigs.k8s.io/controller-tools/pkg/loader.(*TypeChecker).check in goroutine 71
	/Users/yuan/go/pkg/mod/sigs.k8s.io/controller-tools@v0.12.0/pkg/loader/refs.go:260 +0x1c5
make: *** [manifests] Error 2
```
**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

Golang: 1.22

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by fyuan1316** [comment]
It seems that the changes in Go 1.22 caused this, and controller-gen version 0.12.0 hasn't addressed this issue yet.
https://github.com/kubernetes-sigs/controller-tools/issues/880

**Comment by spolti** [comment]
Pease use golang 1.21.
This issue is caused by a version mismatch.

I guess that, to fix it you need to remove the controller-gen binary and go mod cache.

**Comment by sivanantha321** [comment]
This is no longer valid. KServe is now using go 1.22. https://github.com/kserve/kserve/pull/3912
