### ISSUE TITLE
aiffairness image dependency issue

### ISSUE THREAD

**Issue by spolti** [kserve/kserve#3901]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
While building the AIF image, this issue happens when we try to run it:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/aiffairness/aifserver/__init__.py", line 15, in <module>
    from .model import AIFModel  # noqa # pylint: disable=unused-import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/aiffairness/aifserver/model.py", line 20, in <module>
    from aif360.metrics import BinaryLabelDatasetMetric
  File "/prod_venv/lib/python3.11/site-packages/aif360/metrics/__init__.py", line 1, in <module>
    from aif360.metrics.metric import Metric
  File "/prod_venv/lib/python3.11/site-packages/aif360/metrics/metric.py", line 2, in <module>
    from collections import Hashable
ImportError: cannot import name 'Hashable' from 'collections' (/usr/local/lib/python3.11/collections/__init__.py)
```

To fix that, it is necessary to change the import from `collections` to collections.abc`. However, the `metric.py` file is coming from the aif360 package.

**Comment by spolti** [comment]
@yuzisun @terrytangyuan f.y.i

**Comment by spolti** [comment]
I did a quick test but was not able to fix it by updating aif360 to the next versions, the package distutils was missing, so I tried to install `(pip)setuptools` and `(atp-get)python3-distutils and python3-setuptools` and had no luck

**Comment by terrytangyuan** [comment]
This is removed after Python 3.10. We can probably remove AIF if it's not being maintained?

**Comment by spolti** [comment]
that might be a good idea.
Or we can keep it with python 3.10 only.
