### ISSUE TITLE
Direct PVC mount does not support pvc path for a single file

### ISSUE THREAD

**Issue by greenmoon55** [kserve/kserve#3942]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

Provide a PVC url in the isvc: `pvc://foo/models/iris/model.joblib`

pod spec:
```
    volumeMounts:
    - mountPath: /mnt/models
      name: kserve-pvc-source
      readOnly: true
      subPath: models/iris/model.joblib
```

Error message in the storage initializer
 ```
2024-09-17 14:56:59.405 1 kserve INFO [storage.py:download():72] Copying contents of /mnt/models to local
2024-09-17 14:56:59.406 1 kserve INFO [storage.py:download():116] Successfully copied /mnt/models to None
2024-09-17 14:56:59.406 1 kserve INFO [storage.py:download():117] Model downloaded in 0.00023183300072560087 seconds.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/sklearnserver/sklearnserver/__main__.py", line 35, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 41, in load
    for file in os.listdir(model_path):
                ^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/mnt/models'
```
Getting this error from `docker.io/kserve/sklearnserver:latest`

```
2024-09-17 14:56:59.405 1 kserve INFO [storage.py:download():72] Copying contents of /mnt/models to local
2024-09-17 14:56:59.406 1 kserve INFO [storage.py:download():116] Successfully copied /mnt/models to None
2024-09-17 14:56:59.406 1 kserve INFO [storage.py:download():117] Model downloaded in 0.00023183300072560087 seconds.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/sklearnserver/sklearnserver/__main__.py", line 35, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 41, in load
    for file in os.listdir(model_path):
                ^^^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/mnt/models'
```

Code pointer 
https://github.com/kserve/kserve/blob/9ec6842546682b338f0141bba2bda769a953a850/pkg/webhook/admission/pod/storage_initializer_injector.go#L257

**What did you expect to happen:**

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by aitorhh** [comment]
Anything that you find to solve this issue already?

**Comment by greenmoon55** [comment]
@aitorhh Not really. I just noticed this limitation when I was testing something.

**Comment by aitorhh** [comment]
After some testing, for reference:

```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-pvc"
  annotations:
    storage.kserve.io/readonly: "false"
spec:
  predictor:
    model:
      args: ["--enable_docs_url=True"]
      modelFormat:
        name: sklearn
      storageUri: "pvc://model-store/sklearn-iris"
```

Basically `storageUri` should be and folder path (https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L258).

Inside the `sklearn-iris/` folder it loads the `model.joblib`.

I've updated the documentation, and created the PR: https://github.com/kserve/website/pull/400

**Comment by mgw2168-1** [comment]
> After some testing, for reference:经过一番测试，供参考：
> 
> ```
> apiVersion: "serving.kserve.io/v1beta1"
> kind: "InferenceService"
> metadata:
>   name: "sklearn-iris-pvc"
>   annotations:
>     storage.kserve.io/readonly: "false"
> spec:
>   predictor:
>     model:
>       args: ["--enable_docs_url=True"]
>       modelFormat:
>         name: sklearn
>       storageUri: "pvc://model-store/sklearn-iris"
> ```
> 
> Basically `storageUri` should be and folder path (https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L258).基本上，`storageUri` 应该是 和 文件夹路径 （https://github.com/kserve/kserve/blob/master/pkg/webhook/admission/pod/storage_initializer_injector.go#L258）。
> 
> Inside the `sklearn-iris/` folder it loads the `model.joblib`.在 `sklearn-iris/` 文件夹中，它加载了 `model.joblib`。
> 
> I've updated the documentation, and created the PR: [kserve/website#400](https://github.com/kserve/website/pull/400)我已经更新了文档，并创建了 PR： [kserve/website#400](https://github.com/kserve/website/pull/400)

If using a folder path, an error will be reported as follows：
```
2024-11-04 08:23:27.511 1 kserve INFO [storage.py:download():66] Copying contents of /mnt/models to local
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 35, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 52, in load
    self._model = joblib.load(model_files[0])
  File "/prod_venv/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/prod_venv/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.9/pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.svm.classes'
```
pvc.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

model-store-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: model-store-pod
spec:
  volumes:
    - name: model-store
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: model-store
      image: ubuntu:18.04
      command: [ "sleep" ]
      args: [ "infinity" ]
      volumeMounts:
        - mountPath: "/pv"
          name: model-store
      resources:
        limits:
          memory: "1Gi"
          cpu: "1"
```
pvc-inferenceService.yaml
```
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-pvc"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "pvc://task-pv-claim/pv"
```
and `${PVC_NAME}/${MODEL_NAME}/ ` folder have model model.joblib

**Comment by mgw2168-1** [comment]
@aitorhh Can you present a complete case? including pv, pvc, model-store, InfereneceService. Thank you!

**Comment by sivanantha321** [comment]
@mgw2168-1 I believe it is due to scikit learn version mismatch. The model you are using maybe created using different scikit-learn version.

**Comment by mgw2168-1** [comment]
> @mgw2168-1 I believe it is due to scikit learn version mismatch. The model you are using maybe created using different scikit-learn version.

Thank you for your reply. In the end, it was successfully run using tensorflow.
