### ISSUE TITLE
Server Blocking Inferences and Ray/Workers Issues

### ISSUE THREAD

**Issue by ajstewart** [kserve/kserve#3950]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

### Blocking Inferences

This first bit is not really an issue but I wanted to clarify nonetheless.

When writing a custom predictor such as that described here: https://kserve.github.io/website/master/modelserving/v1beta1/custom/custom_model/

The eventual `predict` call ends up here:
https://github.com/kserve/kserve/blob/2376eeb3256034fcaa5ee8f494c014576a2b4f5e/python/kserve/kserve/model.py#L235-L243

Which is a sync function being run in the async event loop. This has the effect of making the entire server unresponsive for the duration of the inference call. 

I stumbled on this when my pod was being killed by the liveness check because an inference for my model takes ~3 seconds and there were quite a few queued up, so the liveness probe didn't get a response in time. I also see errors in the `queue-proxy` under load because of this, I believe because the inference service becomes unresponsive.

So it would seem like whatever model I hosted using the custom predictor, I have to have a `containerConcurrency = 1`. Otherwise it just doesn't run very well.

I've talked about this before here: https://github.com/kserve/kserve/discussions/3592 where I kind of deduce this and end up tuning my scaling and inferences around the limit.

But I'm revisiting it and I want to ask - am I missing something here? Is there anything I can do to achieve a higher concurrency per container?

Is this the same case of non-custom predictors? E.g. `TorchServe`.

Or are there recommendations of how to tune around this blocking call?

### Ray

I thought one solution would be to use the parallel hosting described in the docs but I am running into the same issue here: https://github.com/kserve/kserve/issues/3661

Is Ray still currently broken on 0.13? It seems like there is work done on Ray for 0.14.

### Workers

This may be a bug, but when experimenting with the `--workers` argument (not really a solution for production but I wanted to see it's performance) I am getting (Python 3.10.13):

```
2024-09-23 15:09:24 2024-09-23 14:09:24.363 1017 kserve INFO [model_server.py:serve():260] Starting uvicorn with 2 workers
2024-09-23 15:09:24 2024-09-23 14:09:24.366 1017 kserve INFO [server.py:start():63] Starting gRPC server on [::]:8081
2024-09-23 15:09:24 Traceback (most recent call last):
2024-09-23 15:09:24   File "/app/segmentation_predictor.py", line 296, in <module>
2024-09-23 15:09:24     ModelServer().start([model])
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/site-packages/kserve/model_server.py", line 319, in start
2024-09-23 15:09:24     asyncio.run(servers_task())
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2024-09-23 15:09:24     return loop.run_until_complete(main)
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
2024-09-23 15:09:24     return future.result()
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/site-packages/kserve/model_server.py", line 317, in servers_task
2024-09-23 15:09:24     await asyncio.gather(*servers)
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/site-packages/kserve/model_server.py", line 297, in serve
2024-09-23 15:09:24     multiprocessing.set_start_method("fork")
2024-09-23 15:09:24   File "/usr/local/lib/python3.10/multiprocessing/context.py", line 247, in set_start_method
2024-09-23 15:09:24     raise RuntimeError('context has already been set')
2024-09-23 15:09:24 RuntimeError: context has already been set
```

when the multiprocessing attempts to start. My model implementation is pretty much the same as the example so I don't think I am doing anything odd that would cause this. I could try and see if I can replicate it on the example.

**What did you expect to happen:**

For inferences to not completely block all calls to the server.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version: 0.13.1
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by sivanantha321** [comment]
@ajstewart You should make predict method async. Follow the updated example [here](https://github.com/kserve/kserve/tree/master/python/custom_model). The website doc needs update

**Comment by ajstewart** [comment]
> @ajstewart You should make predict method async. Follow the updated example [here](https://github.com/kserve/kserve/tree/master/python/custom_model). The website doc needs update

Hi, thanks for your reply!

Looking at that example, won't that still block the event loop? It will block here as the model call is not an async safe method:

https://github.com/kserve/kserve/blob/b344a0adb1cfd831c1b8f029baf6ec992163e482/python/custom_model/model_remote.py#L67

It would be preferable to have the underlying FastAPI route call be defined as a synchronous function so FastAPI handles the entire route in its thread pool.

This is easier said than done, but you'd need a sync version of this route for use with sync predict calls:

https://github.com/kserve/kserve/blob/b344a0adb1cfd831c1b8f029baf6ec992163e482/python/kserve/kserve/protocol/rest/v2_endpoints.py#L125-L132

Though it's likely that the model inference is CPU bound so I guess this is also questionable and this is where some kind of process pool would be better (hence I was looking at Ray to at least separate the model call).

For light models with a very fast inference you won't really see any problem.

I was thinking recently that actually the blocking may help slightly with keeping the inference service up in my case as it self regulates the concurrency (i.e. 1). If suddenly the model was truly async then you really need to make sure everything is tuned correctly otherwise it will be very easy to bring the server down! Can can be bad for users who can end up seeing a a load of errors on calls because the queue-proxy raising 502s.

**Comment by ajstewart** [comment]
With the release of 0.14 I have been able to get Ray Serve to work.

Would this be the recommended way to separate the server process from the model inference process? Seems to work well with the Ray Actor processes performing the actual inference that could last a few seconds, leaving the server still responsive.

And just to confirm I'm not missing something here? Without Ray it seems difficult to get a responsive server when the inference can take on the order of seconds and is CPU bound?

**Comment by InderjeetVishnoi** [comment]
Hi @ajstewart 

I am facing issues making ray serve to work with kserve. Getting errors for RayModel import.

Did you fork kserve repo to make it work?

**Comment by ajstewart** [comment]
> Hi [@ajstewart](https://github.com/ajstewart)
> 
> I am facing issues making ray serve to work with kserve. Getting errors for RayModel import.
> 
> Did you fork kserve repo to make it work?

Hi, no I did not. It worked with 0.14 without any issues (though I haven't tried it recently).

Note that you need to install kserve with the optional dependency - `kserve[ray]`

If you still have issues I suggest you open a new issue so the maintainers can help.

**Comment by ajstewart** [comment]
Given the more recent discussion in #5019 this is perhaps still relevant, but perhaps that one should be the one to remain open rather than both.
