### ISSUE TITLE
Huggingface runtime (hf backend) fails to return for all following calls if wrong endpoint is hit

### ISSUE THREAD

**Issue by tylerhyang** [kserve/kserve#3957]
/kind bug

**What steps did you take and what happened:**
I am following through the steps of deploying the google-t5/t5-small in an AWS cluster with KServe v0.13.1.  The model deploys fine but will stall indefinitely for inference requests if the following happens:
1. reach the model with the intended endpoint
```
 curl -H "Content-Type: application/json" https://{some-domain}/{some-path}/t5-large-from-huggingface/openai/v1/completions -d '{
    "model": "google-t5/t5-small",
    "prompt": "translate English to German: The house is wonderful.",
    "stream": true,
    "max_tokens": 30
}'
data: {"id":"000586a1-a06c-4eea-baeb-c2d1471710de","choices":[{"finish_reason":"length","index":0,"logprobs":null,"text":"Das "}],"created":1727135334,"model":"google-t5/t5-small","system_fingerprint":null,"object":"text_completion","usage":null}

data: {"id":"000586a1-a06c-4eea-baeb-c2d1471710de","choices":[{"finish_reason":"length","index":0,"logprobs":null,"text":"Haus "}],"created":1727135334,"model":"google-t5/t5-small","system_fingerprint":null,"object":"text_completion","usage":null}

data: {"id":"000586a1-a06c-4eea-baeb-c2d1471710de","choices":[{"finish_reason":"length","index":0,"logprobs":null,"text":"ist "}],"created":1727135334,"model":"google-t5/t5-small","system_fingerprint":null,"object":"text_completion","usage":null}

data: {"id":"000586a1-a06c-4eea-baeb-c2d1471710de","choices":[{"finish_reason":"length","index":0,"logprobs":null,"text":"wunderbar.</s>"}],"created":1727135334,"model":"google-t5/t5-small","system_fingerprint":null,"object":"text_completion","usage":null}

data: [DONE]
```
2. attempt to communicate with t5-small with the `/openai/v1/chat/completions`.  This does not return any response.

3. try to reach the original completions endpoint again which will wait until to operation times out:
```
 curl -H "Content-Type: application/json" https://{some-domain}/{some-path}/t5-large-from-huggingface/openai/v1/completions -d '{
    "model": "google-t5/t5-small",
    "prompt": "translate English to German: The house is wonderful.",
    "stream": true,
    "max_tokens": 30
}'
curl: (56) Recv failure: Operation timed out
```
**What did you expect to happen:**
if there is an error, it should return an error code.  I also expected subsequent working calls to succeed.

**What's the InferenceService yaml:**
```
spec:
  predictor:
    canaryTrafficPercent: 100
    maxReplicas: 1
    minReplicas: 1
    model:
      args:
        - '--backend'
        - auto
        - '--model_id'
        - google-t5/t5-large
        - '--model_name'
        - google-t5/t5-large
      modelFormat:
        name: huggingface
      name: ''
      resources:
        limits:
          nvidia.com/gpu: '1'
        requests:
          cpu: '10'
          memory: 64Gi
      runtime: my-huggingface-runtime
      storageUri: google-t5/t5-large
    serviceAccountName: my-deployment-sa
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
    volumes:
      - emptyDir: {}
        name: model-provision
```
**Anything else you would like to add:**
I've taken a look at the isvc logs for the first call that fails:
```
2024-09-23 23:50:20.385 uvicorn.access INFO:     [IP] 1 - "POST /openai/v1/chat/completions HTTP/1.1" 200 OK
Exception in thread Thread-5 (generate):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/prod_venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/prod_venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1576, in generate
    result = self._greedy_search(
  File "/prod_venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2548, in _greedy_search
    unfinished_sequences = unfinished_sequences & ~stopping_criteria(input_ids, scores)
  File "/prod_venv/lib/python3.10/site-packages/transformers/generation/stopping_criteria.py", line 169, in __call__
    is_done = is_done | criteria(input_ids, scores, **kwargs)
  File "/huggingfaceserver/huggingfaceserver/stop_sequence_stopping_criteria.py", line 45, in __call__
    if torch.any(torch.all(input_ids[:, -len(seq) :] == seq, dim=1)):
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```
and subsequent calls that stall return 200:
```
2024-09-24 16:58:23.846 uvicorn.access INFO:    [IP] 1 - "POST /openai/v1/completions HTTP/1.1" 200 OK
```
this leads me to believe that the process is handled but the failing request is not being closed properly and blocking the successful call from being emitted
**Environment:**

- Istio Version: v1.22.4
- Knative Version: v1.13.2
- KServe Version: v0.13.1
- Kubeflow version: n/a
- Cloud Environment: aws
- Minikube/Kind version: n/a
- Kubernetes version: (use `kubectl version`): 1.30.1
- OS (e.g. from `/etc/os-release`): linux/amd64

**Comment by gavrissh** [comment]
This issue might be fixed with this change #4055
