### ISSUE TITLE
vLLM engine crashes when `--num-scheduler-steps > 1` and `max_tokens` is undefined

### ISSUE THREAD

**Issue by kevinmingtarja** [kserve/kserve#3971]
/kind bug

**What steps did you take and what happened:**
- Create an `InferenceService` with the Hugging Face server + vLLM backend, and use an LLM as the model
- Enable vLLM's multistep scheduling (`--num-scheduler-steps > 1`), which is recommended as of [v0.6.0](https://github.com/vllm-project/vllm/releases/tag/v0.6.0) to improve performance
- Make a request to `/openai/v1/chat/completions` without setting `max_tokens` -> ERROR
- Subsequent requests will fail (`kserve.errors.ModelNotReady: Model with name ... is not ready`) as well, even with `max_tokens` set

```bash
Traceback (most recent call last):
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 48, in _log_task_completion
    return_value = task.result()
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 733, in run_engine_loop
    result = task.result()
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 673, in engine_step
    request_outputs = await self.engine.step_async(virtual_engine)
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 340, in step_async
    outputs = await self.model_executor.execute_model_async(
  File "/prod_venv/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 185, in execute_model_async
    output = await make_async(self.driver_worker.execute_model
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/prod_venv/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 327, in execute_model
    output = self.model_runner.execute_model(
  File "/prod_venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/prod_venv/lib/python3.10/site-packages/vllm/worker/multi_step_model_runner.py", line 458, in execute_model
    outputs = self._final_process_outputs(model_input,
  File "/prod_venv/lib/python3.10/site-packages/vllm/worker/multi_step_model_runner.py", line 308, in _final_process_outputs
    output_proc_callback()
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 984, in _process_model_outputs
    self.output_processor.process_outputs(
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/output_processor/multi_step.py", line 120, in process_outputs
    self._process_seq_outputs(seq, valid_samples,
  File "/prod_venv/lib/python3.10/site-packages/vllm/engine/output_processor/multi_step.py", line 144, in _process_seq_outputs
    remaining_tokens = sampling_params.max_tokens - (seq.get_output_len() +
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/prod_venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/prod_venv/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/prod_venv/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/prod_venv/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/kserve/kserve/protocol/rest/openai/endpoints.py", line 123, in create_chat_completion
    completion = await self.dataplane.create_chat_completion(
  File "/kserve/kserve/protocol/rest/openai/dataplane.py", line 100, in create_chat_completion
    return await model.create_chat_completion(completion_request)
  File "/kserve/kserve/protocol/rest/openai/openai_chat_adapter_model.py", line 218, in create_chat_completion
    Completion, await self.create_completion(completion_request)
  File "/huggingfaceserver/huggingfaceserver/vllm/vllm_model.py", line 83, in create_completion
    return await self.openai_serving_completion.create_completion(request)
  File "/huggingfaceserver/huggingfaceserver/vllm/vllm_completions.py", line 197, in create_completion
    raise OpenAIError(str(e))
```

**Basically the issue is `vllm/engine/output_processor/multi_step.py` requires `SamplingParams.max_tokens` to be set.**

**What did you expect to happen:**
We should be able to omit `max_tokens` without facing any errors.

**What's the InferenceService yaml:**
```yaml
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: llama3
spec:
  predictor:
    model:
      args:
      - --model_name=llama3
      - --model_id=meta-llama/Llama-3.1-8B-Instruct
      - --max-model-len=16384
      - --num-scheduler-steps=8
      env:
      - name: HF_TOKEN
        value: ... 
      image: kserve/huggingfaceserver:latest
      modelFormat:
        name: huggingface
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "2"
          nvidia.com/gpu: "1"
```

**Anything else you would like to add:**
Without multistep scheduling, this works fine, there won't be any error if we don't specify `max_tokens`.

**Potential Fix**
There's an upstream [issue](https://github.com/vllm-project/vllm/issues/6707) on vLLM, which was already [fixed](https://github.com/vllm-project/vllm/pull/6954). I believe the reason why it's not also fixed yet in KServe is because KServe wrote its own frontend (`huggingfaceserver/huggingfaceserver/vllm`) for vLLM, and the fix on vLLM was to their own frontend (`vllm/entrypoints/openai`), in particular to the `to_sampling_params` function. If the fix was to the vLLM engine then KServe would've gotten the fix too after upgrading the version.

I believe both frontends are similar enough though that this would be a simple fix to port over to KServe. I can have a PR up quickly.

**Environment:**

- Istio Version: v1.20.3
- Knative Version: v1.13.1
- KServe Version: latest
- Cloud Environment: k8s_istio
- Kubernetes version: (use `kubectl version`): v1.29.7-eks-a18cd3a

**Comment by spolti** [comment]
@kevinmingtarja hi, would you mind sending the PR?

**Comment by kevinmingtarja** [comment]
> @kevinmingtarja hi, would you mind sending the PR?

yep, I just made a PR for the fix!
