### ISSUE TITLE
In the Kubeflow 1.9.1, How do i access at KServe through istio-ingress-gateway svc

### ISSUE THREAD

**Issue by reconlabs-luke** [kserve/kserve#4011]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I used [this code](https://github.com/kserve/kserve/blob/v0.13.0/docs/samples/istio-dex/README.md) that you guys support

**What did you expect to happen:**
```
Traceback (most recent call last):
  File "/Users/reconlabs/Desktop/luke/recon/management-mlops/test2.py", line 119, in <module>
    _auth_session = get_istio_auth_session(url=KUBEFLOW_ENDPOINT, username=KUBEFLOW_USERNAME, password=KUBEFLOW_PASSWORD)
  File "/Users/reconlabs/Desktop/luke/recon/management-mlops/test2.py", line 33, in get_istio_auth_session
    raise RuntimeError(f"HTTP status code '{resp.status_code}' for GET against: {url}")
RuntimeError: HTTP status code '403' for GET against: http://localhost:8080
```
- It raised 403 error

![image](https://github.com/user-attachments/assets/8663eb04-8514-4f5c-841a-fcdac9ab4911)
- It seems that the kubeflow added some button for dex
- How to access at KServe ?

**Environment:**

- Istio Version: 1.22.1
- Knative Version: 1.12.4
- KServe Version: 0.13.0
- Kubeflow version: 1.9.1
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm] istio_dex
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`): v1.31.1
- OS (e.g. from `/etc/os-release`): Mac

**Comment by reconlabs-luke** [comment]
I solved using below code i change

```python
response = session.get(f"{HOST}/oauth2/start?rd=%2Foauth2", **_kargs, allow_redirects=True)
```
