### ISSUE TITLE
Storage initializer s3 download botocore PermanentRedirect error with endpoint url

### ISSUE THREAD

**Issue by bentohset** [kserve/kserve#4047]
/kind bug

**What steps did you take and what happened:**
Running storage initializer download with the following environment variables (global endpoint path style with separate region env) causes botocore PermanentRedirect error:
```bash
# env file
AWS_ACCESS_KEY_ID=XXXXXXXXXXXX
AWS_DEFAULT_REGION=eu-central-1
AWS_ENDPOINT_URL=https://s3.amazonaws.com # using legacy path style without region in endpoint
AWS_SECRET_ACCESS_KEY=XXXXXXXXXX
S3_ENDPOINT=s3.amazonaws.com # using legacy path style without region in endpoint
S3_USE_HTTPS=1
S3_VERIFY_SSL=1

# command
docker run --env-file env.list -it kserve/storage-initializer:latest s3://redacted-bucket-name/test_data/tfmodel/ /tmp/model/
```

causes the following error:

```
INFO:root:Initializing, args: src_uri [s3://REDACTED/test_data/tfmodel/] dest_path[ [/tmp/model]
INFO:kserve:Copying contents of s3://REDACTED/test_data/tfmodel/ to local
INFO:botocore.credentials:Found credentials in environment variables.
Traceback (most recent call last):
  File "/app/scripts/initializer-entrypoint", line 27, in <module>
    CommunityStorage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.11/site-packages/kserve/storage/storage.py", line 91, in download
    model_dir = Storage._download_s3(uri, out_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kserve/storage/storage.py", line 231, in _download_s3
    for obj in bucket.objects.filter(Prefix=bucket_path):
  File "/usr/local/lib/python3.11/site-packages/boto3/resources/collection.py", line 79, in __iter__
    for page in self.pages():
  File "/usr/local/lib/python3.11/site-packages/boto3/resources/collection.py", line 169, in pages
    for page in pages:
  File "/usr/local/lib/python3.11/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (PermanentRedirect) when calling the ListObjects operation: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint
```

Did some digging and found the issue is resolved when downgrading `boto3` package to versions < 1.25.0.
Seems like the issue is caused by `s3 = boto3.resource("s3", **kwargs)` not reading the correct `AWS_DEFAULT_REGION` when `{"endpoint_url": endpoint_url}` is passed in `kwargs`

A few ways in which I could download without errors:
1. When `AWS_ENDPOINT_URL` is not passed, then storage-initializer downloads from S3 without errors. But I understand some storage options (eg. alicloud) uses the S3 API to download.
2. Editing the `AWS_ENDPOINT_URL` to include the region (eg. `s3.eu-central-1.amazonaws.com `)
3. Downgrade `boto3` package to version 1.24.96

**What did you expect to happen:**
File should download from s3 without any change to the current environment variables provided. Some of our users have the old environment variables used when `AWS_ENDPOINT_URL=https://s3.amazonaws.com` before boto3 started to complain about region not being in endpoint url.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
latest kserve-storage-initializer from main branch

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by bentohset** [comment]
cc @lizzzcai

**Comment by lizzzcai** [comment]
Hi @bentohset , I think a fix should support both scenarios to avoid migration to users who are using the old spec, and those using S3 compatible storage. The doc [example](https://kserve.github.io/website/latest/modelserving/storage/s3/s3/#create-s3-secret) need to be updated as well. Feel free to open a PR if you are interested in contributing.

**Comment by bentohset** [comment]
Based on s3 [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#path-style-access) and their [plans](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/) for endpoint path style (eg. `s3.amazonaws.com` `s3.eu-central-1.amazonaws.com`). I think it would suffice to insert the region into the endpoint url if such an endpoint url and region is provided.

```python
   pattern = r"^(https?)://s3\.(amazonaws|aws)\.com$"
   region = "eu-central-1"
   if endpoint_url:
        match = re.match(pattern, endpoint_url)
        if match and region:
            protocol = match.group(1)
            domain = match.group(2)
            endpoint_url = f"{protocol}://s3.{region}.{domain}.com"
```

From AWS documentation these are the possible endpoint formats:
- global path-style`https://s3.amazonaws.com`
- region path-style`https://s3.us-east-2.amazonaws.com`
- virtual-hosted-style `https://bucketname.s3.us-east-2.amazonaws.com` (should still pass `ENDPOINT_URL = https://s3.us-east-2.amazonaws.com` with `S3_USER_VIRTUAL_BUCKET=True` so not affected)

I don't foresee it affecting other s3 storage options (alicloud, minio etc.) since they have different endpoints (`https://oss-ap-southeast-1.aliyuncs.com` and `https://minio.minio.svc:9000`)

**Comment by lizzzcai** [comment]
Hi @bentohset , is this possible to support:
1. global path-style https://s3.amazonaws.com + region or use default region
2. region path-style https://s3.us-east-2.amazonaws.com, ignore user provided region if any.
3. virtual-hosted-style https://bucketname.s3.us-east-2.amazonaws.com ignore user provided region if any.

via parameter setting of the SDK.
The solution you purpose is very specified to s3, I am not sure if there are any corner cases.

**Comment by bentohset** [comment]
Tried many combinations of SDK parameter setting but was unable to make it work. Raised an [issue](https://github.com/boto/boto3/issues/4360) in boto3 opensource repo to get an answer. Seems like as of September 23 2020, there will need to be region in the endpoint url. `boto3>=1.25.0` holds true for this.

Since this is a regression issue, would it be safe to just insert region into the endpoint url for global path style and region != us-east-1

**Comment by bentohset** [comment]
Found the exact [PR](https://github.com/boto/botocore/pull/2785) in botocore that seems to change the endpoint url rules. The issue occurs in `botocore` version from 1.27.96 to 1.28.0 [here](https://github.com/boto/botocore/compare/1.27.96...1.28.5)

Found another way in which we can support backward compatibility. Which is by setting `addressing_style` to `virtual` for `https://s3.amazonaws.com` + region. Tested this against endpoint url `https://s3.eu-central-1.amazonaws.com` and has no issues as well. 

```python
def get_S3_config():
    from botocore import UNSIGNED

    # default s3 config
    c = Config()

    # anon environment variable defined in s3_secret.go
    anon = "true" == os.getenv("awsAnonymousCredential", "false").lower()
    # S3UseVirtualBucket environment variable defined in s3_secret.go
    # use virtual hosted-style URLs if enabled
    virtual = "true" == os.getenv("S3_USER_VIRTUAL_BUCKET", "false").lower()
    # S3UseAccelerate environment variable defined in s3_secret.go
    # use transfer acceleration if enabled
    accelerate = "true" == os.getenv("S3_USE_ACCELERATE", "false").lower()

    c = c.merge(Config(s3={"addressing_style": "virtual"})) # force addressing style to be virtual

    if anon:
        c = c.merge(Config(signature_version=UNSIGNED))
    if virtual:
        c = c.merge(Config(s3={"addressing_style": "virtual"}))
    if accelerate:
        c = c.merge(Config(s3={"use_accelerate_endpoint": accelerate}))

    return c

```
