### ISSUE TITLE
Huggingface server does not start with vLLM backend due to `--task` option being provided both by kserve and vllm

### ISSUE THREAD

**Issue by hsteude** [kserve/kserve#4076]
/kind bug

**What steps did you take and what happened:**
I tried starting a huggingface server locally (for development purposes). To do so, I created a fresh virtual env, installed the huggingface server package and vLLM, like so:
```sh
python -m virtualenv .venv
source .venv/bin/activate
python -m pip install -e .
python -m pip install vllm
```

I then tried starting a huggingface server with these arguments:
```sh
python -m huggingfaceserver --model_id=Qwen/Qwen2.5-1.5B-Instruct --model_name='debug-model' --max_model_len=256
```

Unfortunately, I ran into this exception:

```txt
❯ python -m huggingfaceserver --model_id=Qwen/Qwen2.5-1.5B-Instruct --model_name='debug-model' --max_model_len=256
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/jovyan/kserve/python/huggingfaceserver/huggingfaceserver/__main__.py", line 141, in <module>
    parser = maybe_add_vllm_cli_parser(parser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/kserve/python/huggingfaceserver/huggingfaceserver/vllm/utils.py", line 57, in maybe_add_vllm_cli_parser
    return AsyncEngineArgs.add_cli_args(parser)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/kserve/python/huggingfaceserver/.venv/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 1167, in add_cli_args
    parser = EngineArgs.add_cli_args(parser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/kserve/python/huggingfaceserver/.venv/lib/python3.11/site-packages/vllm/engine/arg_utils.py", line 212, in add_cli_args
    parser.add_argument(
  File "/opt/conda/lib/python3.11/argparse.py", line 1468, in add_argument
    return self._add_action(action)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/argparse.py", line 1850, in _add_action
    self._optionals._add_action(action)
  File "/opt/conda/lib/python3.11/argparse.py", line 1670, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/argparse.py", line 1482, in _add_action
    self._check_conflict(action)
  File "/opt/conda/lib/python3.11/argparse.py", line 1619, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/opt/conda/lib/python3.11/argparse.py", line 1628, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --task: conflicting option string: --task
```

**What did you expect to happen:**

I expected the server to start without errors.

**What's the InferenceService yaml:**
not relevant

**Anything else you would like to add:**
I was able to fix this in a rather dirty way, by adding a few lines to the `maybe_add_vllm_cli_parser` function in line 54 of the file `python/huggingfaceserver/vllm/utils.py`:

```python
def maybe_add_vllm_cli_parser(parser: ArgumentParser) -> ArgumentParser:
    if not _vllm:
        return parser

    #remove the `--task` argument from the parser if it exists
    for action in parser._actions:
        if "--task" in action.option_strings:
            parser._handle_conflict_resolve(None, [("--task", action)])
            break

    return AsyncEngineArgs.add_cli_args(parser)
```

**Environment:**

- KServe Version: 0.14.0
- vllm Version: 0.6.4.post1
- OS (e.g. from `/etc/os-release`): Ubuntu Container (KF-notebook) 20.04.6 LTS (Focal Fossa) with a MIG partitioned A30 GPU.

**Comment by sivanantha321** [comment]
Fixed in #4147
