### ISSUE TITLE
Flaky inference graph test

### ISSUE THREAD

**Issue by greenmoon55** [kserve/kserve#4133]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

https://github.com/kserve/kserve/actions/runs/12382817271/job/34564302417
I have seen it a few times. The inference graph test is flaky.
```
Will run 5 of 5 specs
•••&Deployment{ObjectMeta:{igraw1  default  ce94c8f1-a874-4d59-a984-4d1bea773f74 253 1 2024-12-17 22:54:11 +0000 UTC <nil> <nil> map[app:isvc.igraw1 serving.kserve.io/inferencegraph:igraw1] map[serving.kserve.io/deploymentMode:RawDeployment] [{serving.kserve.io/v1alpha1 InferenceGraph igraw1 ba2c97b6-2166-420a-9fc6-7848f24e30f7 0xc0017d1888 0xc0017d1889}] [] [{inferencegraph.test Update apps/v1 2024-12-17 22:54:11 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:serving.kserve.io/deploymentMode":{}},"f:labels":{".":{},"f:app":{},"f:serving.kserve.io/inferencegraph":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"ba2c97b6-2166-420a-9fc6-7848f24e30f7\"}":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:serving.kserve.io/deploymentMode":{}},"f:labels":{".":{},"f:app":{},"f:serving.kserve.io/inferencegraph":{}},"f:name":{},"f:namespace":{}},"f:spec":{"f:automountServiceAccountToken":{},"f:containers":{"k:{\"name\":\"igraw1\"}":{".":{},"f:args":{},"f:env":{".":{},"k:{\"name\":\"PROPAGATE_HEADERS\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:name":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:securityContext":{".":{},"f:allowPrivilegeEscalation":{},"f:capabilities":{".":{},"f:drop":{}},"f:privileged":{},"f:readOnlyRootFilesystem":{},"f:runAsNonRoot":{}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}} }]},Spec:DeploymentSpec{Replicas:*1,Selector:&v1.LabelSelector{MatchLabels:map[string]string{app: isvc.igraw1,},MatchExpressions:[]LabelSelectorRequirement{},},Template:{{igraw1  default    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[app:isvc.igraw1 serving.kserve.io/inferencegraph:igraw1] map[serving.kserve.io/deploymentMode:RawDeployment] [] [] []} {[] [] [{igraw1 kserve/router:v0.10.0 [] [--graph-json {"nodes":{"root":{"routerType":"Sequence","steps":[{"serviceUrl":"http://someservice.exmaple.com/"}]}},"resources":{}}]  [] [] [{PROPAGATE_HEADERS Authorization,Intuit_tid nil}] {map[cpu:{{100 -3} {<nil>} 100m DecimalSI} memory:{{524288000 0} {<nil>} 500Mi BinarySI}] map[cpu:{{100 -3} {<nil>} 100m DecimalSI} memory:{{104857600 0} {<nil>} 100Mi BinarySI}] []} [] <nil> [] [] nil nil nil nil /dev/termination-log File IfNotPresent SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[ALL],},Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:*true,ReadOnlyRootFilesystem:*true,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,AppArmorProfile:nil,} false false false}] [] Always 0xc0017d18a8 <nil> ClusterFirst map[]   0xc0017d18b0  false false false <nil> &PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,FSGroupChangePolicy:nil,SeccompProfile:nil,AppArmorProfile:nil,} []   nil default-scheduler [] []  <nil> nil [] <nil> <nil> <nil> map[] [] <nil> nil <nil> [] []}},Strategy:DeploymentStrategy{Type:RollingUpdate,RollingUpdate:&RollingUpdateDeployment{MaxUnavailable:25%,MaxSurge:25%,},},MinReadySeconds:0,RevisionHistoryLimit:*10,Paused:false,ProgressDeadlineSeconds:*600,},Status:DeploymentStatus{ObservedGeneration:0,Replicas:0,UpdatedReplicas:0,AvailableReplicas:0,UnavailableReplicas:0,Conditions:[]DeploymentCondition{},ReadyReplicas:0,CollisionCount:nil,},}
•panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1cc2703]

goroutine 278 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:111 +0x1e5
panic({0x1f1ff20?, 0x3be2180?})
	/opt/hostedtoolcache/go/1.22.10/x64/src/runtime/panic.go:770 +0x132
github.com/kserve/kserve/pkg/controller/v1alpha1/inferencegraph.handleInferenceGraphRawDeployment({0x2999ca0, 0xc00067c120}, {0x29ac2a0, 0xc0008de540}, 0xc000124230, 0xc000ab1d40, 0x2?)
	/home/runner/work/kserve/kserve/pkg/controller/v1alpha1/inferencegraph/raw_ig.go:151 +0x343
github.com/kserve/kserve/pkg/controller/v1alpha1/inferencegraph.(*InferenceGraphReconciler).Reconcile(0xc000b1ed20, {0x298afc0, 0xc001c545a0}, {{{0xc00151d9e0?, 0x5?}, {0xc00151d9d6?, 0xc001657d10?}}})
	/home/runner/work/kserve/kserve/pkg/controller/v1alpha1/inferencegraph/controller.go:177 +0x765
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x2990c08?, {0x298afc0?, 0xc001c545a0?}, {{{0xc00151d9e0?, 0xb?}, {0xc00151d9d6?, 0x0?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:114 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0009e8000, {0x298aff8, 0xc0009b5220}, {0x200cec0, 0xc00158df00})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:311 +0x3bc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0009e8000, {0x298aff8, 0xc0009b5220})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:261 +0x1be
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:222 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 229
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.5/pkg/internal/controller/controller.go:218 +0x486
FAIL	github.com/kserve/kserve/pkg/controller/v1alpha1/inferencegraph	8.710s
```

**What did you expect to happen:**
No failures.

**What's the InferenceService yaml:**
[To help us debug please run `kubectl get isvc $name -n $namespace -oyaml` and paste the output]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KServe Version:
- Kubeflow version:
- Cloud Environment:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube/Kind version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by spolti** [comment]
@israel-hdez did you see it recently in the tests you've done?

**Comment by khushiiagrawal** [comment]
@greenmoon55  @yuzisun   @spolti  is this issue still open to work on ? would be happy to contribute :)

**Comment by spolti** [comment]
Hi @khushiiagrawal it has been a while since we don't spot this issue anymore.
There are a few issues labeled as  good-first-issue, feel free
To take any. 
I am closing this,
We reopen or create a new one in case we see it again.
