### ISSUE TITLE
The "file://" storage type does not work

### ISSUE THREAD

**Issue by pugangxa** [kserve/kserve#621]
/kind bug
In the document and the python message it's said the "file://" storage type is supported, but there's no way to use it. It should be deprecated since we already have the pvc type.

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
No matter what I set, there's kind of message like:
```
INFO:root:Initializing, args: src_uri [file://test] dest_path[ [/mnt/models]
INFO:root:Copying contents of file://test to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 55, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 179, in _download_local
    raise Exception("Local path %s does not exist." % (uri))
Exception: Local path file://test does not exist.
```
**What did you expect to happen:**
Remove the "file://" type.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by Iamlovingit** [comment]
> /kind bug
> In the document and the python message it's said the "file://" storage type is supported, but there's no way to use it. It should be deprecated since we already have the pvc type.
> 
> **What steps did you take and what happened:**
> [A clear and concise description of what the bug is.]
> No matter what I set, there's kind of message like:
> 
> ```
> INFO:root:Initializing, args: src_uri [file://test] dest_path[ [/mnt/models]
> INFO:root:Copying contents of file://test to local
> Traceback (most recent call last):
>   File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
>     kfserving.Storage.download(src_uri, dest_path)
>   File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 55, in download
>     return Storage._download_local(uri, out_dir)
>   File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 179, in _download_local
>     raise Exception("Local path %s does not exist." % (uri))
> Exception: Local path file://test does not exist.
> ```
> 
> **What did you expect to happen:**
> Remove the "file://" type.
> 
> **Anything else you would like to add:**
> [Miscellaneous information that will assist in solving the issue.]
> 
> **Environment:**
> 
> * Istio Version:
> * Knative Version:
> * KFServing Version:
> * Kubeflow version:
> * Minikube version:
> * Kubernetes version: (use `kubectl version`):
> * OS (e.g. from `/etc/os-release`):

yes, there is a bug in `local file` situation. i build the local file in storage images, and change the storage.py code. you can read this  #567 .

**Comment by pugangxa** [comment]
I see. After PR #156 the local file in fact means pvc. The "file://" type storage is not supported so I removed it in PR #622

**Comment by Iamlovingit** [comment]
> I see. After PR #156 the local file in fact means pvc. The "file://" type storage is not supported so I removed it in PR #622

agree

**Comment by yuzisun** [comment]
File:// is originally used for local model server development, I’d suggest we still keep this.

**Comment by pugangxa** [comment]
> File:// is originally used for local model server development, I’d suggest we still keep this.

Just see this, I had some discussion in the slack:
```
About local dev development, do you mean to package the model together with the server image or just exist in the OS path and mounted?
I think it should be to package together because we do not know which host k8s will distribute right?
If we still keep it, we need fix it by skipping the injector so that we can pass the init-container. But I think it can be replaced by PVC now (for local development we can also put it to PVC) and we can remove it. 
```

**Comment by pvgbabu** [comment]
Hi All, I got similar issue while trying to do kFserving sklearn inference , is any one able to fix this. 
My cluster is PKS and uses  nfs_storage
Please let us know. 

kubectl logs sklearn-iris-predictor-default-q8pbn-deployment-5dc9d76c56f68nz -n kubeflow kfserving-container
[I 200520 14:11:43 storage:35] Copying contents of /mnt/models to local
Traceback (most recent call last):
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/sklearnserver/sklearnserver/main.py", line 33, in
model.load()
File "/sklearnserver/sklearnserver/model.py", line 33, in load
model_path = kfserving.Storage.download(self.model_dir)
File "/kfserving/kfserving/storage.py", line 58, in download
(_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX))
Exception: Cannot recognize storage type for /mnt/models
'gs://', 's3://', and 'file://' are the current available storage type.

**Comment by pugangxa** [comment]
> Hi All, I got similar issue while trying to do kFserving sklearn inference , is any one able to fix this.
> My cluster is PKS and uses nfs_storage
> Please let us know.

For NFS I think you should create pvc for this nfs path, and then use the "pvc://" storage type rather than the "file://" type.

**Comment by pvgbabu** [comment]
Thanks@pugangxa. do you have any sample yaml or example to create pvc for  dynamic volume provisioned nfs storage

**Comment by Iamlovingit** [comment]
There is a sample about pvc.
https://github.com/kubeflow/kfserving/blob/master/docs/samples/pvc/README.md#create-a-inferenceservice-for-on-prem-cluster

**Comment by aurorazl** [comment]
I submit a PR[https://github.com/kubeflow/kfserving/pull/1081](url) to support storageUri like file://.

**Comment by spolti** [comment]
Closing as the attached PR was closed as stale.
