### ISSUE TITLE
key error in kf_serving_watch.py when running kfs-pipeline.ipynb sample

### ISSUE THREAD

**Issue by kpeters** [kserve/kserve#758]
Hi,

**Goal**: I'm trying to run the top example of kfserving pipeline samples (see: https://github.com/kubeflow/kfserving/blob/master/docs/samples/pipelines/kfs-pipeline.ipynb)

**What I changed**:
client = kfp.Client()
namespace = 'anonymous' 

**What I expected to happen**:
For a model to be deployed through kubeflow pipelines

**What actually happened**:
The step in the pipeline failed with exit code 1
```
Traceback (most recent call last):
  File "kfservingdeployer.py", line 177, in <module>
    autoscaling_target=autoscaling_target
  File "kfservingdeployer.py", line 105, in deploy_model
    KFServing.create(kfsvc, watch=True, timeout_seconds=120)
  File "/usr/local/lib/python3.6/site-packages/kfserving/api/kf_serving_client.py", line 102, in create
    timeout_seconds=timeout_seconds)
  File "/usr/local/lib/python3.6/site-packages/kfserving/api/kf_serving_watch.py", line 48, in watch
    url = kfserivce['status'].get('url', '')
KeyError: 'status'
```

**Other info**: 
- kubernetes v1.14.9-eks
- kubeflow v1.0.1
- knative v0.11.1
- kfserving v0.3.0
- Notebook server setup from kubeflow central dashboard, image used is tensorflow-1.15.2-cpu:1.0.0

Any tips to get this example up and running would be highly appreciated! 

Kind regards, Koen

**Comment by kpeters** [comment]
Update

Today after setting up the cluster and deploying kubeflow, kfserving and prerequisites I tried the sklearn-iris CLI example (https://github.com/kubeflow/kfserving/blob/master/README.md#test-kfserving-installation )

Success!
However, setting up a notebook server after this deployment no longer worked: _Insufficient CPU_
Maybe that partially explains why the example wouldn't run? Although the error from my original post doesn't clarify, maybe my cluster had no more resources.

deleted deployments sklearn-iris, pytorch-operator and tensorboard to create some room
also changed namespace='anonymous' to namespace='kubeflow', as the passed namespace should be equal to the namespace where kfserving is running (from description in: https://github.com/kubeflow/pipelines/blob/master/components/kubeflow/kfserving/component.yaml)

After these changes I no longer run into the original posted error but this one:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/kfserving/api/kf_serving_client.py", line 92, in create
    inferenceservice)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 178, in create_namespaced_custom_object
    (data) = self.create_namespaced_custom_object_with_http_info(group, version, namespace, plural, body, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/apis/custom_objects_api.py", line 277, in create_namespaced_custom_object_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 377, in request
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 266, in POST
    body=body)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '631ffd1e-33ff-4464-878a-70c9d0ac3a2d', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 03 Apr 2020 09:18:17 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "kfservingdeployer.py", line 177, in <module>
    autoscaling_target=autoscaling_target
  File "kfservingdeployer.py", line 105, in deploy_model
    KFServing.create(kfsvc, watch=True, timeout_seconds=120)
  File "/usr/local/lib/python3.6/site-packages/kfserving/api/kf_serving_client.py", line 96, in create
    %s\n" % e)
RuntimeError: Exception when calling CustomObjectsApi->create_namespaced_custom_object:                 (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '631ffd1e-33ff-4464-878a-70c9d0ac3a2d', 'Content-Type': 'text/plain; charset=utf-8', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 03 Apr 2020 09:18:17 GMT', 'Content-Length': '19'})
HTTP response body: 404 page not found
```

What would be best, should I create a new issue for the new error? And can someone confirm the original error occurs when insufficient CPUs are available?

**Comment by yuzisun** [comment]
Fixed in commit 
https://github.com/kserve/kserve/blob/7baebda3ea4b2d856550e77eb0ee6e36da5d6fc5/python/kserve/kserve/api/kserve_client.py#L296
